-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = game:GetService("UserInputService");
local l_LocalPlayer_0 = game:GetService("Players").LocalPlayer;
local v3 = l_LocalPlayer_0.PlayerScripts:WaitForChild("PlayerModule", 5);
local v4 = nil;
if not v3 then
    warn("PlayerModule not found. Mobile controls are disabled");
else
    v4 = require(v3);
end;
local l_v4_Controls_0 = v4:GetControls();
local l_Shared_0 = l_ReplicatedStorage_0.Slerp.Shared;
local v7 = require(l_Shared_0.IK2L);
local l_Client_0 = l_ReplicatedStorage_0.Slerp.Client;
local v9 = require(l_Client_0.CameraShaker);
local v10 = require(l_Client_0.CameraShaker.CameraShakeInstance);
local l_Shared_1 = l_ReplicatedStorage_0.Slerp.Shared;
local v12 = require(l_Shared_1.Signal);
local _ = require(script.Parent.Types);
local v14 = {};
local v15 = nil;
local v16 = nil;
local l_CurrentCamera_0 = workspace.CurrentCamera;
local v18 = 0;
local function v20(v19) --[[ Line: 54 ]] --[[ Name: shakeCamera ]]
    l_CurrentCamera_0.CFrame = l_CurrentCamera_0.CFrame * v19;
end;
local function v24() --[[ Line: 58 ]] --[[ Name: enableAllHumanoidStateTypes ]]
    if not v16 then
        return;
    else
        local l_humanoid_0 = v16.humanoid;
        for _, v23 in Enum.HumanoidStateType:GetEnumItems() do
            l_humanoid_0:SetStateEnabled(v23, true);
        end;
        return;
    end;
end;
local function v29(v25) --[[ Line: 68 ]] --[[ Name: disableAllHumanoidStateTypeseExcept ]]
    if not v16 then
        return;
    else
        local l_humanoid_1 = v16.humanoid;
        for _, v28 in Enum.HumanoidStateType:GetEnumItems() do
            if v28 ~= v25 and v28 ~= Enum.HumanoidStateType.Dead and v28 ~= Enum.HumanoidStateType.Jumping then
                l_humanoid_1:SetStateEnabled(v28, false);
            end;
        end;
        return;
    end;
end;
local v30 = Enum.RenderPriority.Camera.Value + 1;
local v31 = v9.new(v30, v20);
local v32 = {
    currentSustainedShake = "None", 
    maxThrottle = 1, 
    lastDir = Vector3.zAxis, 
    throttleJoystickAngleX = 0, 
    rotateJoystickAngleX = 0, 
    rotateJoystickAngleZ = 0
};
local v33 = v12.new();
v14.throttleChangedSignal = v33;
local v34 = v12.new();
v14.landedSignal = v34;
v14.IDLE_THROTTLE = 0.1;
v14.init = function() --[[ Line: 120 ]] --[[ Name: init ]]
    v31:Start();
    local function v46(v35) --[[ Line: 123 ]] --[[ Name: setCharacterDependencies ]]
        local v36 = v35:WaitForChild("Humanoid", 30);
        if not v36 then
            warn("Jetpack: Failed to retrieve local humanoid.");
            return;
        else
            local v37 = v36.RootPart or v35:WaitForChild("HumanoidRootPart", 30);
            if not v37 then
                warn("Jetpack: Failed to retrieve local humanoid root part.");
                return;
            else
                local l_Animator_0 = v36:FindFirstChildOfClass("Animator");
                local v39 = nil;
                v39 = l_Animator_0.AnimationPlayed:Connect(function(v40) --[[ Line: 138 ]]
                    local l_v36_State_0 = v36:GetState();
                    if v15 and v15.throttle > 0 and (l_v36_State_0 == Enum.HumanoidStateType.Freefall or l_v36_State_0 == Enum.HumanoidStateType.Flying) then
                        v40:Stop();
                    end;
                end);
                local l_v36_State_1 = v36:GetState();
                local v43 = nil;
                v43 = v36.StateChanged:Connect(function(v44, v45) --[[ Line: 147 ]]
                    l_v36_State_1 = v44;
                    if v45 == Enum.HumanoidStateType.Landed and v15 then
                        v14.setThrottle(v15, 0);
                        v34:Fire();
                    end;
                end);
                v16 = {
                    humanoid = v36, 
                    model = v35, 
                    animator = l_Animator_0, 
                    humanoidRootPart = v37, 
                    animationPlayedConnection = v39, 
                    stateChangedConnection = v43, 
                    lastState = l_v36_State_1
                };
                return;
            end;
        end;
    end;
    if l_LocalPlayer_0.Character then
        v46(l_LocalPlayer_0.Character);
    end;
    l_LocalPlayer_0.CharacterAdded:Connect(function(v47) --[[ Line: 171 ]]
        v46(v47);
    end);
    l_LocalPlayer_0.CharacterRemoving:Connect(function() --[[ Line: 174 ]]
        if not v16 then
            return;
        else
            if v16.animationPlayedConnection then
                v16.animationPlayedConnection:Disconnect();
            end;
            if v16.stateChangedConnection then
                v16.stateChangedConnection:Disconnect();
            end;
            v16 = nil;
            return;
        end;
    end);
end;
local function v64(v48, v49, v50, v51) --[[ Line: 188 ]] --[[ Name: createArm ]]
    local l_v49_FirstChild_0 = v49:FindFirstChild(v48 .. "Shoulder");
    local l_v50_FirstChild_0 = v50:FindFirstChild(v48 .. "Elbow");
    local l_v49_FirstChild_1 = v49:FindFirstChild(v48 .. "ShoulderRigAttachment");
    local l_v49_FirstChild_2 = v49:FindFirstChild(v48 .. "ShoulderAttachment");
    local l_v49_FirstChild_3 = v49:FindFirstChild(v48 .. "ElbowRigAttachment");
    local l_v50_FirstChild_1 = v50:FindFirstChild(v48 .. "ElbowRigAttachment");
    local l_v51_FirstChild_0 = v51:FindFirstChild(v48 .. "GripAttachment");
    if not l_v49_FirstChild_0 or not l_v50_FirstChild_0 then
        return nil;
    elseif not l_v49_FirstChild_1 or not l_v49_FirstChild_2 then
        return nil;
    elseif not l_v49_FirstChild_3 or not l_v50_FirstChild_1 then
        return nil;
    else
        local l_Magnitude_0 = (l_v49_FirstChild_2.WorldPosition - l_v49_FirstChild_3.WorldPosition).Magnitude;
        local l_Magnitude_1 = (l_v50_FirstChild_1.WorldPosition - l_v51_FirstChild_0.WorldPosition).Magnitude;
        local v61 = l_v49_FirstChild_1.WorldCFrame:ToObjectSpace(l_v49_FirstChild_1.WorldCFrame.Rotation + l_v49_FirstChild_2.WorldPosition);
        local v62 = l_v49_FirstChild_1.WorldCFrame:ToObjectSpace(l_v49_FirstChild_3.WorldCFrame);
        local v63 = l_v50_FirstChild_1.WorldCFrame:ToObjectSpace(l_v51_FirstChild_0.WorldCFrame);
        return {
            upperArm = v49, 
            lowerArm = v50, 
            upperArmLength = l_Magnitude_0, 
            lowerArmLength = l_Magnitude_1, 
            shoulderJoint = l_v49_FirstChild_0, 
            elbowJoint = l_v50_FirstChild_0, 
            shoulderRigToShoulder = v61, 
            shoulderRigToElbowRig = v62, 
            elbowRigToGrip = v63
        };
    end;
end;
local function v71(v65, v66) --[[ Line: 228 ]] --[[ Name: createLeg ]]
    local l_v66_FirstChild_0 = v66:FindFirstChild(v65 .. "UpperLeg");
    local l_v66_FirstChild_1 = v66:FindFirstChild(v65 .. "LowerLeg");
    if not l_v66_FirstChild_0 or not l_v66_FirstChild_1 then
        return nil;
    else
        local l_l_v66_FirstChild_0_FirstChild_0 = l_v66_FirstChild_0:FindFirstChild(v65 .. "Hip");
        local l_l_v66_FirstChild_1_FirstChild_0 = l_v66_FirstChild_1:FindFirstChild(v65 .. "Knee");
        if not l_l_v66_FirstChild_0_FirstChild_0 or not l_l_v66_FirstChild_1_FirstChild_0 then
            return nil;
        else
            return {
                upperLeg = l_v66_FirstChild_0, 
                lowerLeg = l_v66_FirstChild_1, 
                hipJoint = l_l_v66_FirstChild_0_FirstChild_0, 
                kneeJoint = l_l_v66_FirstChild_1_FirstChild_0
            };
        end;
    end;
end;
v14.createRigFromModel = function(v72) --[[ Line: 249 ]] --[[ Name: createRigFromModel ]]
    local l_LeftUpperArm_0 = v72:FindFirstChild("LeftUpperArm");
    local l_LeftLowerArm_0 = v72:FindFirstChild("LeftLowerArm");
    local l_LeftHand_0 = v72:FindFirstChild("LeftHand");
    local v76 = nil;
    if l_LeftUpperArm_0 and l_LeftLowerArm_0 and l_LeftHand_0 then
        v76 = v64("Left", l_LeftUpperArm_0, l_LeftLowerArm_0, l_LeftHand_0);
    end;
    local l_RightUpperArm_0 = v72:FindFirstChild("RightUpperArm");
    local l_RightLowerArm_0 = v72:FindFirstChild("RightLowerArm");
    local l_RightHand_0 = v72:FindFirstChild("RightHand");
    local v80 = nil;
    if l_RightUpperArm_0 and l_RightLowerArm_0 and l_RightHand_0 then
        v80 = v64("Right", l_RightUpperArm_0, l_RightLowerArm_0, l_RightHand_0);
    end;
    local v81 = v71("Left", v72);
    local v82 = v71("Right", v72);
    return {
        leftArm = v76, 
        rightArm = v80, 
        leftLeg = v81, 
        rightLeg = v82
    };
end;
local function v88(v83) --[[ Line: 278 ]] --[[ Name: sharedOnJetpackEquipped ]]
    local l_shared_0 = v83.shared;
    local l_owner_0 = l_shared_0.owner;
    if not l_owner_0 then
        return;
    else
        local l_Character_0 = l_owner_0.Character;
        if not l_Character_0 then
            return;
        else
            v83.rig = v14.createRigFromModel(l_Character_0);
            local v87 = RaycastParams.new();
            v87.FilterType = Enum.RaycastFilterType.Blacklist --[[ 2021 ]];
            v87.FilterDescendantsInstances = {
                v83.shared.model, 
                l_Character_0
            };
            v83.raycastParams = v87;
            if l_shared_0.closeToGroundSound then
                l_shared_0.closeToGroundSound.sound.Volume = 0;
                l_shared_0.closeToGroundSound.sound:Play();
            end;
            return;
        end;
    end;
end;
local l_UserInputService_1 = game:GetService("UserInputService");
local function _(v90) --[[ Line: 303 ]] --[[ Name: sharedOnJetpackUnequipped ]]
    local l_shared_1 = v90.shared;
    v90.rig = nil;
    if l_shared_1.closeToGroundSound then
        l_shared_1.closeToGroundSound.sound:Stop();
    end;
end;
v14.onJetpackEquipped = function(v93) --[[ Line: 311 ]] --[[ Name: onJetpackEquipped ]]
    if not v16 then
        return;
    else
        v88(v93);
        v15 = v93;
        local l_root_0 = v93.shared.root;
        local l_VectorForce_0 = Instance.new("VectorForce");
        l_VectorForce_0.Attachment0 = l_root_0:FindFirstChild("Force");
        l_VectorForce_0.ApplyAtCenterOfMass = true;
        l_VectorForce_0.Force = Vector3.zero;
        l_VectorForce_0.RelativeTo = Enum.ActuatorRelativeTo.World;
        l_VectorForce_0.Parent = l_root_0;
        local l_BodyGyro_0 = Instance.new("BodyGyro");
        l_BodyGyro_0.Parent = v16.humanoidRootPart;
        v93.vectorForce = l_VectorForce_0;
        v93.bodyGyro = l_BodyGyro_0;
        return;
    end;
end;
v14.onJetpackUnequipped = function(v97) --[[ Line: 336 ]] --[[ Name: onJetpackUnequipped ]]
    local l_shared_2 = v97.shared;
    v97.rig = nil;
    if l_shared_2.closeToGroundSound then
        l_shared_2.closeToGroundSound.sound:Stop();
    end;
    v14.setThrottle(v97, 0);
    v15 = nil;
    if v16 then
        l_shared_2 = v16.humanoid:GetState();
        v24();
        v16.humanoid.AutoRotate = true;
        v16.humanoid:ChangeState(Enum.HumanoidStateType.Running);
    end;
    if v97.vectorForce then
        v97.vectorForce:Destroy();
        v97.vectorForce = nil;
    end;
    if v97.bodyGyro then
        v97.bodyGyro:Destroy();
        v97.bodyGyro = nil;
    end;
    v31:StopSustained(0.1);
    v18 = 0;
end;
v14.bystanderOnJetpackEquipped = function(v99) --[[ Line: 361 ]] --[[ Name: bystanderOnJetpackEquipped ]]
    v88(v99);
    v99.lastVel = v99.shared.root.AssemblyLinearVelocity;
end;
v14.bystanderOnJetpackUnequipped = function(v100) --[[ Line: 365 ]] --[[ Name: bystanderOnJetpackUnequipped ]]
    local l_shared_3 = v100.shared;
    v100.rig = nil;
    if l_shared_3.closeToGroundSound then
        l_shared_3.closeToGroundSound.sound:Stop();
    end;
end;
local v102 = CFrame.Angles(1.5707963267948966, 0, 0);
local function _(v103, v104, v105) --[[ Line: 371 ]] --[[ Name: getRotationForPivotPoint ]]
    local v106 = v104 - v103;
    local v107 = v105 - v103;
    return v106:Cross(v107).Unit, -v106:Angle(v107);
end;
local function v140(v109, v110, v111) --[[ Line: 377 ]] --[[ Name: armIK ]]
    local l_shoulderJoint_0 = v109.shoulderJoint;
    local _ = v109.upperArm;
    local l_Part0_0 = l_shoulderJoint_0.Part0;
    if not l_Part0_0 then
        return;
    else
        local v115 = l_Part0_0.CFrame * l_shoulderJoint_0.C0;
        local v116 = v110 - v115.Position;
        local v117 = v115:VectorToObjectSpace(v110 - v115.Position);
        local v118 = v115:PointToObjectSpace((v115 * v109.shoulderRigToShoulder).Position);
        local v119 = math.asin(v118.X / v116.Magnitude);
        local v120 = v115 * (CFrame.lookAt(Vector3.zero, v117.Unit) * CFrame.Angles(0, 0, v111) * CFrame.Angles(0, v119, 0)) * v102;
        local v121 = v120 * CFrame.new(v118.X, 0, 0);
        local _ = v120 * CFrame.new(v118.X, 0, v118.Z);
        local v123 = v109.upperArmLength - v118.Y;
        local l_Magnitude_2 = (v110 - v121.Position).Magnitude;
        local v125, v126 = v7.solve2d(l_Magnitude_2, v123, v109.lowerArmLength);
        if v125 ~= v125 or v126 ~= v126 then
            return;
        else
            v120 = v120 * CFrame.Angles(-v125, 0, 0);
            local v127 = v120 * CFrame.new(v118.X, 0, 0) * CFrame.new(0, -v123, 0);
            local v128 = v120 * v109.shoulderRigToElbowRig;
            local l_Position_0 = v120.Position;
            local l_Position_1 = v127.Position;
            local l_Position_2 = v128.Position;
            local v132 = l_Position_1 - l_Position_0;
            local v133 = l_Position_2 - l_Position_0;
            local l_Unit_0 = v132:Cross(v133).Unit;
            local v135 = -v132:Angle(v133);
            l_Position_0 = CFrame.fromAxisAngle(v120:VectorToObjectSpace(l_Unit_0), v135);
            if l_Position_0 == l_Position_0 then
                v120 = v120 * l_Position_0;
            end;
            l_Unit_0 = v120 * v109.shoulderRigToElbowRig;
            v135 = v127;
            l_Position_0 = v127 * CFrame.Angles(3.141592653589793 - v126, 0, 0) * CFrame.new(0, -v109.lowerArmLength, 0);
            l_Position_1 = v127 * v109.elbowRigToGrip;
            v133 = v127.Position;
            local l_Position_3 = l_Position_0.Position;
            local l_Position_4 = l_Position_1.Position;
            local v138 = l_Position_3 - v133;
            local v139 = l_Position_4 - v133;
            l_Position_2 = v138:Cross(v139).Unit;
            v132 = -v138:Angle(v139);
            v133 = CFrame.fromAxisAngle(v127:VectorToObjectSpace(l_Position_2), v132);
            if v133 == v133 then
                v127 = v127 * v133;
            end;
            l_Position_2 = v115.Rotation:ToObjectSpace(v120.Rotation).Rotation;
            v133 = (v115.Rotation * l_Position_2 * v109.shoulderRigToElbowRig).Rotation:ToObjectSpace(v127.Rotation).Rotation;
            v109.shoulderJoint.Transform = l_Position_2;
            v109.elbowJoint.Transform = v133;
            return;
        end;
    end;
end;
local function _(v141, v142, v143, v144) --[[ Line: 443 ]] --[[ Name: armsIK ]]
    local l_leftArm_0 = v141.leftArm;
    local l_rightArm_0 = v141.rightArm;
    if l_leftArm_0 then
        v140(l_leftArm_0, v142, -v144);
    end;
    if l_rightArm_0 then
        v140(l_rightArm_0, v143, v144);
    end;
end;
local _ = function(v148) --[[ Line: 454 ]] --[[ Name: ik ]]
    local l_shared_4 = v148.shared;
    if l_shared_4.owner and v148.rig then
        local _ = l_shared_4.root.CFrame;
        local l_leftHandPos_0 = v148.leftHandPos;
        local l_rightHandPos_0 = v148.rightHandPos;
        if l_leftHandPos_0 and l_rightHandPos_0 then
            local l_rig_0 = v148.rig;
            local l_leftArm_1 = l_rig_0.leftArm;
            local l_rightArm_1 = l_rig_0.rightArm;
            if l_leftArm_1 then
                v140(l_leftArm_1, l_leftHandPos_0, -0.3490658503988659);
            end;
            if l_rightArm_1 then
                v140(l_rightArm_1, l_rightHandPos_0, 0.3490658503988659);
            end;
        end;
    end;
end;
local function v168(v157) --[[ Line: 469 ]] --[[ Name: legs ]]
    local l_shared_5 = v157.shared;
    local l_owner_1 = l_shared_5.owner;
    local l_rig_1 = v157.rig;
    if l_owner_1 and l_rig_1 and l_rig_1.leftLeg and l_rig_1.rightLeg then
        local l_root_1 = l_shared_5.root;
        local l_AssemblyLinearVelocity_0 = l_root_1.AssemblyLinearVelocity;
        local v163 = CFrame.lookAt(l_root_1.Position, l_root_1.Position + l_root_1.CFrame.LookVector):VectorToObjectSpace(l_AssemblyLinearVelocity_0);
        local v164 = math.clamp(v163.X, -50, 50) / 50 * 0.5;
        local v165 = -math.clamp(v163.Z, -50, 50) / 50 * 0.5;
        local v166 = CFrame.Angles(v165, 0, v164);
        l_rig_1.leftLeg.hipJoint.Transform = v166;
        l_rig_1.rightLeg.hipJoint.Transform = v166;
        local v167 = -math.min(math.max(-v163.Y, 0), 70) / 70 * 0.9 - 0.1;
        l_rig_1.leftLeg.kneeJoint.Transform = CFrame.Angles(v167, 0, 0);
        l_rig_1.rightLeg.kneeJoint.Transform = CFrame.Angles(v167, 0, 0);
    end;
end;
local function _(v169, v170, v171) --[[ Line: 496 ]] --[[ Name: lerp ]]
    return v169 + v171 * (v170 - v169);
end;
local function v179(v173) --[[ Line: 500 ]] --[[ Name: handleSound ]]
    local l_thrustSounds_0 = v173.shared.thrustSounds;
    if #l_thrustSounds_0 == 0 then
        return;
    else
        local l_throttle_0 = v173.throttle;
        for _, v177 in pairs(l_thrustSounds_0) --[[ 2021 ]] do
            local v178 = math.max(l_throttle_0 - v177.minThrottle, 0) / (v177.maxThrottle - v177.minThrottle);
            v177.sound.PlaybackSpeed = v177.minPlaybackSpeed + v178 * (v177.maxPlaybackSpeed - v177.minPlaybackSpeed);
        end;
        return;
    end;
end;
local _ = function(v180) --[[ Line: 512 ]] --[[ Name: preSimulationShared ]]
    local l_shared_6 = v180.shared;
    if l_shared_6.owner and v180.rig then
        local _ = l_shared_6.root.CFrame;
        local l_leftHandPos_1 = v180.leftHandPos;
        local l_rightHandPos_1 = v180.rightHandPos;
        if l_leftHandPos_1 and l_rightHandPos_1 then
            local l_rig_2 = v180.rig;
            local l_leftArm_2 = l_rig_2.leftArm;
            local l_rightArm_2 = l_rig_2.rightArm;
            if l_leftArm_2 then
                v140(l_leftArm_2, l_leftHandPos_1, -0.3490658503988659);
            end;
            if l_rightArm_2 then
                v140(l_rightArm_2, l_rightHandPos_1, 0.3490658503988659);
            end;
        end;
    end;
    v168(v180);
    v179(v180);
end;
local v189 = 1;
v14._setMaxThrottle = function(v190) --[[ Line: 520 ]] --[[ Name: _setMaxThrottle ]]
    if v190 > 1 or v190 < 0 then
        return;
    else
        v189 = v190;
        v32.maxThrottle = v190;
        return;
    end;
end;
local function v202(v191, v192, v193) --[[ Line: 528 ]] --[[ Name: sharedOnSetThrottle ]]
    if v192 == 0 and v193 > 0 then
        if v191.shared.startSound then
            v191.shared.startSound:Play();
        end;
        for _, v195 in pairs(v191.shared.thrustSounds) --[[ 2021 ]] do
            v195.sound:Play();
        end;
    elseif v192 <= 0 or v193 <= 0 then
        if v191.shared.endSound then
            v191.shared.endSound:Play();
        end;
        for _, v197 in pairs(v191.shared.thrustSounds) --[[ 2021 ]] do
            v197.sound.PlaybackSpeed = v197.minPlaybackSpeed;
            if v197.sound.Playing then
                v197.sound:Stop();
            end;
        end;
    end;
    for _, v199 in pairs(v191.particles) --[[ 2021 ]] do
        local l_minThrottle_0 = v199.minThrottle;
        local l_maxThrottle_0 = v199.maxThrottle;
        if l_minThrottle_0 <= v193 and v193 <= l_maxThrottle_0 then
            v199.particleEmitter.Enabled = true;
        else
            v199.particleEmitter.Enabled = false;
        end;
    end;
end;
v14.setThrottle = function(v203, v204) --[[ Line: 561 ]] --[[ Name: setThrottle ]]
    local l_throttle_1 = v203.throttle;
    if not v16 then
        v203.throttle = 0;
        return;
    elseif v203.throttle == v204 then
        return;
    elseif v189 < v204 or v204 < 0 then
        return;
    else
        local l_humanoid_2 = v16.humanoid;
        local l_animator_0 = v16.animator;
        if not v203.vectorForce or not v203.bodyGyro then
            v203.throttle = 0;
            return;
        else
            if l_throttle_1 == 0 and v204 > 0 then
                l_humanoid_2:SetStateEnabled(Enum.HumanoidStateType.Running, true);
                v29(Enum.HumanoidStateType.Running);
                l_humanoid_2:ChangeState(Enum.HumanoidStateType.Flying);
                l_humanoid_2.AutoRotate = false;
                for _, v209 in l_animator_0:GetPlayingAnimationTracks() do
                    v209:Stop();
                end;
            elseif l_throttle_1 <= 0 or v204 <= 0 then
                v24();
                v16.humanoid.AutoRotate = true;
                v16.humanoid:ChangeState(Enum.HumanoidStateType.Running);
                v31:StopSustained(0.1);
                v18 = 0;
                v203.vectorForce.Force = Vector3.zero;
                v203.bodyGyro.MaxTorque = Vector3.zero;
            end;
            v202(v203, l_throttle_1, v204);
            v33:Fire(l_throttle_1, v204);
            v203.throttle = v204;
            return;
        end;
    end;
end;
v14.safeSetThrottle = function(v210, v211) --[[ Line: 606 ]] --[[ Name: safeSetThrottle ]]
    if not v16 then
        return;
    else
        local _ = v210.throttle;
        if v16.humanoid:GetState() == Enum.HumanoidStateType.Flying and v211 == 0 then
            v211 = 0.1;
        end;
        v14.setThrottle(v210, v211);
        return;
    end;
end;
local function v221(v213, v214, v215) --[[ Line: 621 ]] --[[ Name: setParticlesAreEnabled ]]
    for _, v217 in pairs(v213) --[[ 2021 ]] do
        local l_particleEmitter_0 = v217.particleEmitter;
        if v214 then
            if v215 then
                local l_l_particleEmitter_0_Attribute_0 = l_particleEmitter_0:GetAttribute("UpRate");
                if l_l_particleEmitter_0_Attribute_0 then
                    l_particleEmitter_0.Rate = l_l_particleEmitter_0_Attribute_0;
                end;
            else
                local l_l_particleEmitter_0_Attribute_1 = l_particleEmitter_0:GetAttribute("DownRate");
                if l_l_particleEmitter_0_Attribute_1 then
                    l_particleEmitter_0.Rate = l_l_particleEmitter_0_Attribute_1;
                end;
            end;
        end;
        l_particleEmitter_0.Enabled = v214;
    end;
end;
local l_zAxis_0 = Vector3.zAxis;
local v223 = 0;
local v224 = 0;
local v225 = 0;
local l_None_0 = Enum.HumanoidStateType.None;
v14.preSimulation = function(v227, v228) --[[ Line: 645 ]] --[[ Name: preSimulation ]]
    if not v16 then
        return;
    elseif v228.throttle == 0 then
        return;
    else
        local l_throttle_3 = v228.throttle;
        local l_humanoid_3 = v16.humanoid;
        local l_l_humanoid_3_State_0 = l_humanoid_3:GetState();
        local l_vectorForce_0 = v228.vectorForce;
        local l_bodyGyro_0 = v228.bodyGyro;
        if not l_vectorForce_0 or not l_bodyGyro_0 then
            return;
        else
            local v234 = l_UserInputService_1.MouseBehavior == Enum.MouseBehavior.LockCenter;
            if (l_l_humanoid_3_State_0 == Enum.HumanoidStateType.Freefall or l_l_humanoid_3_State_0 == Enum.HumanoidStateType.Flying) and l_throttle_3 > 0 and not l_humanoid_3.Sit then
                local l_l_v4_Controls_0_MoveVector_0 = l_v4_Controls_0:GetMoveVector();
                local l_MoveDirection_0 = l_humanoid_3.MoveDirection;
                local v237 = nil;
                if l_MoveDirection_0.Magnitude > 0 then
                    v237 = CFrame.lookAt(Vector3.zero, l_MoveDirection_0);
                    l_zAxis_0 = l_MoveDirection_0;
                else
                    v237 = CFrame.lookAt(Vector3.zero, l_zAxis_0);
                end;
                local l_humanoidRootPart_0 = v16.humanoidRootPart;
                if not l_humanoidRootPart_0 then
                    return;
                else
                    if v234 then
                        local l_RightVector_0 = workspace.CurrentCamera.CFrame.RightVector;
                        local l_yAxis_0 = Vector3.yAxis;
                        v237 = CFrame.fromMatrix(Vector3.zero, l_RightVector_0, l_yAxis_0);
                    end;
                    local l_AssemblyMass_0 = l_humanoidRootPart_0.AssemblyMass;
                    local l_AssemblyLinearVelocity_1 = l_humanoidRootPart_0.AssemblyLinearVelocity;
                    local v243 = -0.03 * l_AssemblyLinearVelocity_1 * Vector3.new(math.abs(l_AssemblyLinearVelocity_1.X), 3 * math.abs(l_AssemblyLinearVelocity_1.Y), (math.abs(l_AssemblyLinearVelocity_1.Z)));
                    local v244 = l_humanoidRootPart_0.CFrame.UpVector * 325 * l_throttle_3 + v243;
                    if l_l_v4_Controls_0_MoveVector_0.Magnitude > 0 and l_throttle_3 > 0.1 then
                        if v234 then
                            local v245 = l_l_v4_Controls_0_MoveVector_0.X * -0.47123889803846897;
                            local v246 = l_l_v4_Controls_0_MoveVector_0.Z * 0.47123889803846897;
                            v237 = v237 * CFrame.Angles(v246, 0, v245);
                        else
                            v237 = v237 * CFrame.Angles(-0.47123889803846897, 0, 0);
                        end;
                    end;
                    local v247, v248, v249 = l_humanoidRootPart_0.CFrame:ToEulerAnglesYXZ();
                    local v250, v251, v252 = v237:ToEulerAnglesYXZ();
                    local v253 = math.clamp(v250 - v247, -3.141592653589793, 3.141592653589793) / 3.141592653589793;
                    local v254 = math.clamp(v251 - v248, -3.141592653589793, 3.141592653589793) / 3.141592653589793;
                    local _ = math.clamp(v252 - v249, -3.141592653589793, 3.141592653589793) / 3.141592653589793;
                    if v228.leftHand then
                        local l_LeftJoystick_0 = v228.shared.model:FindFirstChild("LeftJoystick");
                        local _ = l_LeftJoystick_0:GetPivot();
                        local l_Weld_0 = l_LeftJoystick_0:FindFirstChild("Weld");
                        local v259 = l_throttle_3 * 3.141592653589793 * -0.4;
                        v223 = v223 + (v259 - v223) * 0.1;
                        l_Weld_0.C0 = CFrame.new(0, -l_LeftJoystick_0.Size.Y * 0.5, 0) * CFrame.Angles(v223, 0, 0);
                        v228.leftHandPos = v228.leftHand.WorldPosition;
                    end;
                    if v228.rightHand then
                        local l_RightJoystick_0 = v228.shared.model:FindFirstChild("RightJoystick");
                        local _ = l_RightJoystick_0:GetPivot();
                        local l_Weld_1 = l_RightJoystick_0:FindFirstChild("Weld");
                        local v263 = math.clamp(v253, -0.25, 0.25) / 0.25 * 3.141592653589793 * 0.4;
                        local v264 = math.clamp(v254, -0.25, 0.25) / 0.25 * 3.141592653589793 * 0.4;
                        v224 = v224 + (v263 - v224) * 0.1;
                        v225 = v225 + (v264 - v225) * 0.1;
                        local _ = l_humanoidRootPart_0.AssemblyAngularVelocity;
                        l_Weld_1.C0 = CFrame.new(0, -l_RightJoystick_0.Size.Y * 0.5, 0) * CFrame.Angles(v224, 0, v225);
                        v228.rightHandPos = v228.rightHand.WorldPosition;
                    end;
                    l_bodyGyro_0.MaxTorque = 100000 * Vector3.one;
                    l_bodyGyro_0.CFrame = v237;
                    l_vectorForce_0.Force = l_AssemblyMass_0 * v244;
                    local l_leftOut_0 = v228.leftOut;
                    local l_leftGround_0 = v228.leftGround;
                    local l_rightOut_0 = v228.rightOut;
                    local l_rightGround_0 = v228.rightGround;
                    local l_raycastParams_0 = v228.raycastParams;
                    local v271 = nil;
                    local v272 = nil;
                    if l_leftOut_0 and l_leftGround_0 then
                        local v273 = workspace:Raycast(l_leftOut_0.WorldPosition, l_leftOut_0.WorldCFrame.UpVector * -15, l_raycastParams_0);
                        if v273 then
                            local v274 = CFrame.lookAt(v273.Position, v273.Position + v273.Normal) * CFrame.Angles(-1.5707963267948966, 0, 0);
                            l_leftGround_0.WorldCFrame = v274 + v274.UpVector * 2;
                            v221(v228.leftGroundParticles, true, l_throttle_3 == 1);
                            v271 = true;
                        else
                            v221(v228.leftGroundParticles, false);
                        end;
                    end;
                    if l_rightOut_0 and l_rightGround_0 then
                        local v275 = workspace:Raycast(l_rightOut_0.WorldPosition, l_rightOut_0.WorldCFrame.UpVector * -15, l_raycastParams_0);
                        if v275 then
                            local v276 = CFrame.lookAt(v275.Position, v275.Position + v275.Normal) * CFrame.Angles(-1.5707963267948966, 0, 0);
                            l_rightGround_0.WorldCFrame = v276 + v276.UpVector * 2;
                            v221(v228.rightGroundParticles, true, l_throttle_3 == 1);
                            v272 = true;
                        else
                            v221(v228.rightGroundParticles, false);
                        end;
                    end;
                    if (v271 or v272) and v228.shared.closeToGroundSound and v228.closeToGroundSoundLerpAlpha ~= 1 then
                        v228.closeToGroundSoundLerpAlpha = math.min(v228.closeToGroundSoundLerpAlpha + v227 / v228.shared.closeToGroundSound.lerpTime, 1);
                        v228.shared.closeToGroundSound.sound.Volume = v228.closeToGroundSoundLerpAlpha * v228.shared.closeToGroundSound.volume;
                    elseif not v271 and not v272 and v228.shared.closeToGroundSound and v228.closeToGroundSoundLerpAlpha ~= 0 then
                        v228.closeToGroundSoundLerpAlpha = math.max(v228.closeToGroundSoundLerpAlpha - v227 / v228.shared.closeToGroundSound.lerpTime, 0);
                        v228.shared.closeToGroundSound.sound.Volume = v228.closeToGroundSoundLerpAlpha * v228.shared.closeToGroundSound.volume;
                    end;
                    if v271 and v272 and v18 ~= 1 then
                        v18 = 1;
                        local v277 = v10.new(1.2, 7, 0.5, 2);
                        v277.PositionInfluence = Vector3.new(0.25, 0.25, 0.25, 0) * 1.2;
                        v277.RotationInfluence = Vector3.new(1, 1, 4, 0);
                        v31:ShakeSustain(v277);
                    elseif not v271 and not v272 then
                        if l_throttle_3 == 1 and v18 ~= 2 then
                            v31:StopSustained();
                            local v278 = v10.new(0.72, 4.2, 0.5, 2);
                            v278.PositionInfluence = Vector3.new(0.25, 0.25, 0.25, 0);
                            v278.RotationInfluence = Vector3.new(1, 1, 4, 0);
                            v31:ShakeSustain(v278);
                            v18 = 2;
                        elseif l_throttle_3 < 1 and v18 ~= 3 then
                            v31:StopSustained();
                            local v279 = v10.new(0.42, 2.4499999999999997, 0.5, 2);
                            v279.PositionInfluence = Vector3.new(0.25, 0.25, 0.25, 0);
                            v279.RotationInfluence = Vector3.new(1, 1, 4, 0);
                            v31:ShakeSustain(v279);
                            v18 = 3;
                        end;
                    end;
                end;
            else
                l_bodyGyro_0.MaxTorque = Vector3.zero;
                l_vectorForce_0.Force = Vector3.zero;
                if l_throttle_3 > 0 then
                    v14.setThrottle(v228, 0);
                    l_throttle_3 = 0;
                end;
                if l_humanoid_3.Sit then
                    l_humanoid_3:ChangeState(Enum.HumanoidStateType.Seated);
                end;
                v221(v228.leftGroundParticles, false);
                v221(v228.rightGroundParticles, false);
            end;
            local l_shared_7 = v228.shared;
            if l_shared_7.owner and v228.rig then
                local _ = l_shared_7.root.CFrame;
                local l_leftHandPos_2 = v228.leftHandPos;
                local l_rightHandPos_2 = v228.rightHandPos;
                if l_leftHandPos_2 and l_rightHandPos_2 then
                    local l_rig_3 = v228.rig;
                    local l_leftArm_3 = l_rig_3.leftArm;
                    local l_rightArm_3 = l_rig_3.rightArm;
                    if l_leftArm_3 then
                        v140(l_leftArm_3, l_leftHandPos_2, -0.3490658503988659);
                    end;
                    if l_rightArm_3 then
                        v140(l_rightArm_3, l_rightHandPos_2, 0.3490658503988659);
                    end;
                end;
            end;
            v168(v228);
            v179(v228);
            l_None_0 = l_l_humanoid_3_State_0;
            return;
        end;
    end;
end;
v14.bystanderPreSimulation = function(v287, v288) --[[ Line: 836 ]] --[[ Name: bystanderPreSimulation ]]
    local _ = os.clock();
    if v287.leftHand then
        v287.leftHandPos = v287.leftHand.WorldPosition;
    end;
    if v287.rightHand then
        v287.rightHandPos = v287.rightHand.WorldPosition;
    end;
    local l_root_2 = v287.shared.root;
    local l_lastVel_0 = v287.lastVel;
    if not l_lastVel_0 then
        return;
    else
        local l_AssemblyLinearVelocity_2 = l_root_2.AssemblyLinearVelocity;
        local v293 = l_AssemblyLinearVelocity_2:Dot(Vector3.yAxis) > 0;
        local v294 = false;
        local l_owner_2 = v287.shared.owner;
        if not l_owner_2 then
            return;
        else
            local l_Character_1 = l_owner_2.Character;
            if not l_Character_1 then
                return;
            else
                local l_Humanoid_0 = l_Character_1:FindFirstChild("Humanoid");
                if not l_Humanoid_0 then
                    return;
                else
                    local l_l_Humanoid_0_State_0 = l_Humanoid_0:GetState();
                    local v299 = false;
                    if l_l_Humanoid_0_State_0 == Enum.HumanoidStateType.Flying then
                        v299 = not v293;
                    end;
                    if l_l_Humanoid_0_State_0 == Enum.HumanoidStateType.Flying then
                        v294 = v293;
                        if not v293 and l_AssemblyLinearVelocity_2.Magnitude < l_lastVel_0.Magnitude then
                            v294 = true;
                        end;
                    end;
                    local v300 = v299 and 0.1 or (not v294 or v299) and 0 or 1;
                    local l_throttle_4 = v287.throttle;
                    v287.throttle = v300;
                    if v300 ~= l_throttle_4 then
                        v202(v287, l_throttle_4, v300);
                    end;
                    if v300 == 0 then
                        v221(v287.leftGroundParticles, false);
                        v221(v287.rightGroundParticles, false);
                        v179(v287);
                        return;
                    else
                        local l_leftOut_1 = v287.leftOut;
                        local l_leftGround_1 = v287.leftGround;
                        local l_rightOut_1 = v287.rightOut;
                        local l_rightGround_1 = v287.rightGround;
                        local l_raycastParams_1 = v287.raycastParams;
                        local v307 = nil;
                        local v308 = nil;
                        if l_leftOut_1 and l_leftGround_1 then
                            local v309 = workspace:Raycast(l_leftOut_1.WorldPosition, l_leftOut_1.WorldCFrame.UpVector * -15, l_raycastParams_1);
                            if v309 then
                                local v310 = CFrame.lookAt(v309.Position, v309.Position + v309.Normal) * CFrame.Angles(-1.5707963267948966, 0, 0);
                                l_leftGround_1.WorldCFrame = v310 + v310.UpVector * 2;
                                v221(v287.leftGroundParticles, true, v300 == 1);
                                v307 = true;
                            else
                                v221(v287.leftGroundParticles, false);
                            end;
                        end;
                        if l_rightOut_1 and l_rightGround_1 then
                            local v311 = workspace:Raycast(l_rightOut_1.WorldPosition, l_rightOut_1.WorldCFrame.UpVector * -15, l_raycastParams_1);
                            if v311 then
                                local v312 = CFrame.lookAt(v311.Position, v311.Position + v311.Normal) * CFrame.Angles(-1.5707963267948966, 0, 0);
                                l_rightGround_1.WorldCFrame = v312 + v312.UpVector * 2;
                                v221(v287.rightGroundParticles, true, v300 == 1);
                                v308 = true;
                            else
                                v221(v287.rightGroundParticles, false);
                            end;
                        end;
                        if (v307 or v308) and v287.shared.closeToGroundSound and v287.closeToGroundSoundLerpAlpha ~= 1 then
                            v287.closeToGroundSoundLerpAlpha = math.min(v287.closeToGroundSoundLerpAlpha + v288 / v287.shared.closeToGroundSound.lerpTime, 1);
                            v287.shared.closeToGroundSound.sound.Volume = v287.closeToGroundSoundLerpAlpha * v287.shared.closeToGroundSound.volume;
                        elseif not v307 and not v308 and v287.shared.closeToGroundSound and v287.closeToGroundSoundLerpAlpha ~= 0 then
                            v287.closeToGroundSoundLerpAlpha = math.max(v287.closeToGroundSoundLerpAlpha - v288 / v287.shared.closeToGroundSound.lerpTime, 0);
                            v287.shared.closeToGroundSound.sound.Volume = v287.closeToGroundSoundLerpAlpha * v287.shared.closeToGroundSound.volume;
                        end;
                        v287.lastVel = l_AssemblyLinearVelocity_2;
                        local l_shared_8 = v287.shared;
                        if l_shared_8.owner and v287.rig then
                            local _ = l_shared_8.root.CFrame;
                            local l_leftHandPos_3 = v287.leftHandPos;
                            local l_rightHandPos_3 = v287.rightHandPos;
                            if l_leftHandPos_3 and l_rightHandPos_3 then
                                local l_rig_4 = v287.rig;
                                local l_leftArm_4 = l_rig_4.leftArm;
                                local l_rightArm_4 = l_rig_4.rightArm;
                                if l_leftArm_4 then
                                    v140(l_leftArm_4, l_leftHandPos_3, -0.3490658503988659);
                                end;
                                if l_rightArm_4 then
                                    v140(l_rightArm_4, l_rightHandPos_3, 0.3490658503988659);
                                end;
                            end;
                        end;
                        v168(v287);
                        v179(v287);
                        l_shared_8 = os.clock();
                        return;
                    end;
                end;
            end;
        end;
    end;
end;
return v14;