-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_Players_0 = game:GetService("Players");
local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local l_SoundService_0 = game:GetService("SoundService");
local l_TweenService_0 = game:GetService("TweenService");
local _ = game:GetService("RunService");
local l_SoundRegions_0 = workspace.SoundRegions;
local l_Music_0 = l_SoundService_0.Music;
local _ = workspace.CurrentCamera;
local function _(v8, v9, v10, v11) --[[ Line: 12 ]] --[[ Name: tween ]]
	-- upvalues: l_TweenService_0 (copy)
	local v12 = TweenInfo.new(v9, v11 or Enum.EasingStyle.Quint);
	local v13 = l_TweenService_0:Create(v8, v12, v10);
	v13:Play();
	return v13;
end;
local function v18(v15) --[[ Line: 19 ]] --[[ Name: isAnyMusicPlaying ]]
	for _, v17 in v15:GetChildren() do
		if v17:IsA("Sound") and v17.Playing then
			return true;
		end;
	end;
	return false;
end;
local l_DaytimeTrack_0 = l_Music_0.DaytimeTrack;
local l_NightTimeTrack_0 = l_Music_0.NightTimeTrack;
local l_GiftingTrack_0 = l_Music_0.GiftingTrack;
local l_ShopTrack_0 = l_Music_0.ShopTrack;
local l_CampfireTrack_0 = l_Music_0.CampfireTrack;
local _ = l_Music_0.MineTrack;
local _ = l_Music_0.GuitarTrack;
local l_NothingTrack_0 = l_Music_0.NothingTrack;
-- local l_AdidasTrack_0 = l_Music_0.AdidasTrack;
local l_DaytimeTrack_1 = l_Music_0:FindFirstChild("DaytimeTrack");
local v29 = nil;
l_SoundRegions_0.Parent = workspace;
game:GetService("RunService").Heartbeat:Connect(function() --[[ Line: 45 ]]
	-- upvalues: l_DaytimeTrack_0 (copy), l_NightTimeTrack_0 (copy), v18 (copy), l_SoundService_0 (copy), l_NothingTrack_0 (copy), l_GiftingTrack_0 (copy), l_Players_0 (copy), l_SoundRegions_0 (copy), l_ReplicatedStorage_0 (copy), l_ShopTrack_0 (copy), l_CampfireTrack_0 (copy), l_AdidasTrack_0 (copy), l_DaytimeTrack_1 (ref), v29 (ref), l_TweenService_0 (copy)
	local l_l_DaytimeTrack_0_0 = l_DaytimeTrack_0;
	if game.Lighting.ClockTime >= 0 and game.Lighting.ClockTime < 6 then
		l_l_DaytimeTrack_0_0 = l_NightTimeTrack_0;
	end;
	if v18(l_SoundService_0.GlassAnimals) then
		l_l_DaytimeTrack_0_0 = l_NothingTrack_0;
	elseif v18(l_SoundService_0.RewindMusic) then
		l_l_DaytimeTrack_0_0 = l_NothingTrack_0;
	elseif workspace:FindFirstChild("GiftIsland") then
		l_l_DaytimeTrack_0_0 = l_GiftingTrack_0;
	elseif workspace:GetAttribute("LiveEventPlaying") then
		l_l_DaytimeTrack_0_0 = l_NothingTrack_0;
	elseif l_Players_0.LocalPlayer.Character and l_Players_0.LocalPlayer.Character.PrimaryPart then
		local v31 = OverlapParams.new();
		v31.FilterDescendantsInstances = {
			l_SoundRegions_0.Shop, 
			l_SoundRegions_0.Island, 
			l_SoundRegions_0.Mine, 
			l_SoundRegions_0.Guitar, 
			-- l_SoundRegions_0.Adidas
		};
		v31.FilterType = Enum.RaycastFilterType.Whitelist --[[ 2021 ]];
		v31.RespectCanCollide = false;
		v31.BruteForceAllSlow = true;
		local v32 = workspace:GetPartsInPart(l_Players_0.LocalPlayer.Character.PrimaryPart, v31)[1];
		if l_Players_0.LocalPlayer:FindFirstChild("PlayerScripts") == nil then
			return;
		elseif v32 == l_SoundRegions_0.Shop then
			l_ReplicatedStorage_0.OceanActor.OceanAnimation:SetAttribute("Disabled", false);
			l_l_DaytimeTrack_0_0 = l_ShopTrack_0;
		elseif v32 == l_SoundRegions_0.Island then
			l_ReplicatedStorage_0.OceanActor.OceanAnimation:SetAttribute("Disabled", false);
			l_l_DaytimeTrack_0_0 = l_CampfireTrack_0;
	--	elseif v32 == l_SoundRegions_0.Adidas then
	--		l_ReplicatedStorage_0.OceanActor.OceanAnimation:SetAttribute("Disabled", false);
	--		l_l_DaytimeTrack_0_0 = l_AdidasTrack_0;
		end;
	end;
	if l_l_DaytimeTrack_0_0 ~= l_DaytimeTrack_1 then
		local l_l_DaytimeTrack_1_0 = l_DaytimeTrack_1;
		print((("started stopping %s"):format(l_l_DaytimeTrack_1_0)));
		if v29 then
			v29:Cancel();
		end;
		local v34 = {
			Volume = 0
		};
		local v35 = TweenInfo.new(2, Enum.EasingStyle.Quint);
		local v36 = l_TweenService_0:Create(l_l_DaytimeTrack_1_0, v35, v34);
		v36:Play();
		v29 = v36;
		v29.Completed:Once(function() --[[ Line: 97 ]]
			-- upvalues: l_l_DaytimeTrack_1_0 (copy)
			print((("no longer playing %s"):format(l_l_DaytimeTrack_1_0)));
			l_l_DaytimeTrack_1_0.Playing = false;
		end);
		l_DaytimeTrack_1 = l_l_DaytimeTrack_0_0;
		print((("started playing %s"):format(l_DaytimeTrack_1)));
		l_DaytimeTrack_1.Playing = true;
		local l_l_DaytimeTrack_1_1 = l_DaytimeTrack_1;
		v34 = {
			Volume = 0.2
		};
		v35 = TweenInfo.new(2, Enum.EasingStyle.Quint);
		l_TweenService_0:Create(l_l_DaytimeTrack_1_1, v35, v34):Play();
	end;
end);