-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_LocalPlayer_0 = game:GetService("Players").LocalPlayer;
local _ = game:GetService("PhysicsService");
local _ = game:GetService("ContentProvider");
local l_RunService_0 = game:GetService("RunService");
local l_Lighting_0 = game:GetService("Lighting");
local l_TweenService_0 = game:GetService("TweenService");
local l_Debris_0 = game:GetService("Debris");
local v7 = require(script.Parent.Parent.Parent);
local l_Parent_0 = script.Parent;
local v9 = require(l_Parent_0.Parent);
local l_Assets_0 = l_Parent_0:WaitForChild("Assets");
local _ = l_Parent_0:WaitForChild("Events");
local l_CurrentCamera_0 = workspace.CurrentCamera;
local v13 = Random.new();
local v14 = {
	Color3.fromRGB(224, 248, 255), 
	Color3.fromRGB(142, 187, 255), 
	Color3.fromRGB(185, 222, 255), 
	Color3.fromRGB(133, 180, 255), 
	Color3.fromRGB(216, 234, 255), 
	Color3.fromRGB(183, 194, 255), 
	Color3.fromRGB(179, 251, 255)
};
local function v18(v15) --[[ Line: 40 ]] --[[ Name: Emit ]]
	for _, v17 in pairs(v15:GetChildren()) do
		if v17:IsA("ParticleEmitter") then
			v17:Emit(v17:GetAttribute("EmitCount"));
		elseif v17:IsA("Sound") then
			v17:Play();
		end;
	end;
end;
local function v23(v19, v20) --[[ Line: 50 ]] --[[ Name: Enable ]]
	for _, v22 in pairs(v19:GetChildren()) do
		if v22:IsA("ParticleEmitter") or v22:IsA("Trail") or v22:IsA("Beam") then
			v22.Enabled = v20;
		elseif v22:IsA("Sound") then
			if v20 then
				v22:Play();
			else
				v22:Stop();
			end;
		end;
	end;
end;
local function _(v24, v25, v26) --[[ Line: 64 ]] --[[ Name: playSound ]]
	local v27 = v24:Clone();
	v27.Parent = v25;
	v27.Volume = v26;
	v27:Play();
	task.delay(75, function() --[[ Line: 71 ]]
		-- upvalues: v27 (copy)
		if not v27.Parent then
			return;
		else
			v27:Destroy();
			return;
		end;
	end);
	return v27;
end;
local function v35(v29, v30, v31) --[[ Line: 79 ]] --[[ Name: ScaleModel ]]
	-- upvalues: l_TweenService_0 (copy), l_RunService_0 (copy)
	local l_NumberValue_0 = Instance.new("NumberValue");
	local v33 = l_TweenService_0:Create(l_NumberValue_0, v30, {
		Value = v29
	});
	v33:Play();
	local v34 = l_RunService_0.RenderStepped:Connect(function() --[[ Line: 88 ]]
		-- upvalues: v31 (copy), l_NumberValue_0 (copy)
		v31(l_NumberValue_0.Value);
	end);
	v33.Completed:Once(function() --[[ Line: 92 ]]
		-- upvalues: v34 (copy), v33 (copy), l_NumberValue_0 (copy)
		v34:Disconnect();
		v33:Destroy();
		l_NumberValue_0:Destroy();
	end);
end;
local _ = function(v36, v37) --[[ Line: 100 ]] --[[ Name: wiggleBones ]]
	-- upvalues: l_TweenService_0 (copy), v13 (copy)
	local v38 = {};
	for _, v40 in pairs(v37) do
		v38[v40] = v40.CFrame;
	end;
	local v41 = false;
	task.spawn(function() --[[ Line: 109 ]]
		-- upvalues: v41 (ref), v37 (copy), l_TweenService_0 (ref), v38 (copy), v13 (ref), v36 (copy)
		while not v41 do
			for _, v43 in ipairs(v37) do
				l_TweenService_0:Create(v43, TweenInfo.new(0.2, Enum.EasingStyle.Linear, Enum.EasingDirection.InOut), {
					CFrame = v38[v43] * CFrame.new(v13:NextNumber(-1, 1) * v36, v13:NextNumber(-1, 1) * v36, v13:NextNumber(-1, 1) * v36) * CFrame.Angles(math.rad((v13:NextNumber(-1, 1))), math.rad((v13:NextNumber(-1, 1))), (math.rad((v13:NextNumber(-1, 1)))))
				}):Play();
			end;
			task.wait(0.2);
		end;
	end);
	return function() --[[ Line: 121 ]]
		-- upvalues: v41 (ref)
		v41 = true;
	end;
end;
local function v50(v45, v46, v47, v48) --[[ Line: 126 ]] --[[ Name: pulse ]]
	-- upvalues: l_Lighting_0 (copy), l_TweenService_0 (copy), l_Debris_0 (copy)
	local l_BloomEffect_0 = Instance.new("BloomEffect");
	l_BloomEffect_0.Parent = l_Lighting_0;
	l_BloomEffect_0.Size = v45;
	l_BloomEffect_0.Threshold = v47;
	l_TweenService_0:Create(l_BloomEffect_0, TweenInfo.new(v48 / 2, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
		Intensity = v46
	}):Play();
	task.delay(v48 / 2, function() --[[ Line: 137 ]]
		-- upvalues: l_TweenService_0 (ref), l_BloomEffect_0 (copy), v48 (copy), l_Debris_0 (ref)
		l_TweenService_0:Create(l_BloomEffect_0, TweenInfo.new(v48 * 1.5, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
			Intensity = 0, 
			Threshold = 4
		}):Play();
		l_Debris_0:AddItem(l_BloomEffect_0, v48 * 1.5);
	end);
end;
local function _(v51) --[[ Line: 147 ]] --[[ Name: setCamera ]]
	-- upvalues: l_CurrentCamera_0 (copy), l_RunService_0 (copy)
	l_CurrentCamera_0.CameraType = Enum.CameraType.Scriptable;
	local v52 = l_RunService_0.RenderStepped:Connect(function() --[[ Line: 150 ]]
		-- upvalues: l_CurrentCamera_0 (ref), v51 (copy)
		l_CurrentCamera_0.CFrame = v51.CFrame;
	end);
	return function() --[[ Line: 154 ]]
		-- upvalues: l_CurrentCamera_0 (ref), v52 (copy)
		l_CurrentCamera_0.CameraType = Enum.CameraType.Custom;
		v52:Disconnect();
	end;
end;
local function v58(v54, v55) --[[ Line: 160 ]] --[[ Name: setLerpCamera ]]
	-- upvalues: l_CurrentCamera_0 (copy), l_RunService_0 (copy)
	l_CurrentCamera_0.CameraType = Enum.CameraType.Custom;
	local v57 = l_RunService_0.RenderStepped:Connect(function(v56) --[[ Line: 163 ]]
		-- upvalues: l_CurrentCamera_0 (ref), v54 (copy), v55 (copy)
		l_CurrentCamera_0.CFrame = l_CurrentCamera_0.CFrame:Lerp(CFrame.lookAt(l_CurrentCamera_0.CFrame.Position, v54.Position), v56 / v55);
	end);
	return function() --[[ Line: 167 ]]
		-- upvalues: l_CurrentCamera_0 (ref), v57 (copy)
		l_CurrentCamera_0.CameraType = Enum.CameraType.Custom;
		v57:Disconnect();
	end;
end;
local _ = function(v59, _) --[[ Line: 173 ]] --[[ Name: setLookAtCamera ]]
	-- upvalues: l_RunService_0 (copy), l_CurrentCamera_0 (copy)
	local v62 = l_RunService_0.RenderStepped:Connect(function(_) --[[ Line: 174 ]]
		-- upvalues: l_CurrentCamera_0 (ref), v59 (copy)
		l_CurrentCamera_0.CFrame = CFrame.lookAt(l_CurrentCamera_0.CFrame.Position, v59.Position) * CFrame.new(0, 0, -125);
	end);
	return function() --[[ Line: 178 ]]
		-- upvalues: l_CurrentCamera_0 (ref), v62 (copy)
		l_CurrentCamera_0.CameraType = Enum.CameraType.Custom;
		v62:Disconnect();
	end;
end;
local _ = function(v64, v65, v66) --[[ Line: 184 ]] --[[ Name: setCameraParticles ]]
	-- upvalues: l_RunService_0 (copy), l_CurrentCamera_0 (copy), v23 (copy)
	v64 = v64:Clone();
	v64.Parent = v66;
	local v68 = l_RunService_0.RenderStepped:Connect(function(_) --[[ Line: 188 ]]
		-- upvalues: v64 (ref), l_CurrentCamera_0 (ref), v65 (copy)
		v64.CFrame = l_CurrentCamera_0.CFrame * v65;
	end);
	v23(v64, true);
	return function() --[[ Line: 194 ]]
		-- upvalues: v68 (copy), v64 (ref)
		v68:Disconnect();
		v64:Destroy();
	end, v64;
end;
local function v77(v70, v71, v72, v73) --[[ Line: 200 ]] --[[ Name: tweenParticleColor ]]
	local v74 = math.floor(v71 * 60);
	for v75 = 0, v74 do
		local v76 = v75 / v74;
		v70.Color = ColorSequence.new(v72:Lerp(v73, v76));
		task.wait(0.016666666666666666);
	end;
end;
local function v80(v78) --[[ Line: 214 ]] --[[ Name: makeIcy ]]
	-- upvalues: l_TweenService_0 (copy), v13 (copy), v14 (copy)
	local v79 = l_TweenService_0:Create(v78, TweenInfo.new(v13:NextNumber(2, 7) * 1.25, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
		Color = v14[v13:NextInteger(1, #v14)]
	});
	v79:Play();
	task.delay(v79.TweenInfo.Time, function() --[[ Line: 221 ]]
		-- upvalues: v79 (copy)
		v79:Destroy();
	end);
end;
local v108 = {
	Intro = function(_, v82, v83, v84) --[[ Line: 228 ]] --[[ Name: Intro ]]
		-- upvalues: v7 (copy), l_Assets_0 (copy), l_TweenService_0 (copy), v18 (copy), v35 (copy), v23 (copy), v58 (copy)
		local l_CameraShaker_0 = v7.Utils.CameraShaker;
		local _ = v7.Utils.ForceEnable;
		local _ = v7.Utils.Transitions;
		local _ = v7.Utils.Bezier;
		local l_Rift_0 = v7.Utils.Rift;
		local _ = v7.Utils.Lightning;
		local v91 = l_Rift_0:Rift(v82.MapPositions.component_positions.presentStart.WorldCFrame, 3, false, {
			AutoSlowBeams = true
		});
		task.delay(8, function() --[[ Line: 241 ]]
			-- upvalues: v91 (copy)
			v91();
		end);
		local v92 = l_Assets_0.Models.GiftBox:Clone();
		v92:PivotTo(v82.MapPositions.component_positions.presentStart.WorldCFrame);
		v92.Parent = v83;
		l_TweenService_0:Create(v92.Root, TweenInfo.new(3, Enum.EasingStyle.Linear, Enum.EasingDirection.Out), {
			CFrame = v82.MapPositions.component_positions.presentEnd.WorldCFrame
		}):Play();
		task.delay(3, function() --[[ Line: 253 ]]
			-- upvalues: v18 (ref), v92 (copy), v35 (ref), l_CameraShaker_0 (copy)
			v18(v92.Root.Splash);
			local l_v92_Scale_0 = v92:GetScale();
			v35(-10, TweenInfo.new(0.3, Enum.EasingStyle.Sine, Enum.EasingDirection.Out, 0, true), function(v94) --[[ Line: 257 ]]
				-- upvalues: v92 (ref), l_v92_Scale_0 (copy)
				v92:ScaleTo(l_v92_Scale_0 + v94);
			end);
			l_CameraShaker_0.inst:Shake(l_CameraShaker_0.mod.Presets.PresentHitWater);
		end);
		task.wait(3.25);
		local v95 = l_Assets_0.Models.Crystal1:Clone();
		v95.Parent = v83;
		v95:PivotTo(v92.Root.CFrame);
		v23(v95.Root.Traveling, true);
		l_TweenService_0:Create(v92.Root.GiftTop, TweenInfo.new(3, Enum.EasingStyle.Exponential, Enum.EasingDirection.Out), {
			C1 = CFrame.new(0, -500, 0)
		}):Play();
		local l_Top_0 = v92.Top;
		l_Top_0.Parent = workspace;
		local l_l_Top_0_Scale_0 = l_Top_0:GetScale();
		v35(l_l_Top_0_Scale_0 - 0.1, TweenInfo.new(2, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), function(v98) --[[ Line: 280 ]]
			-- upvalues: l_Top_0 (copy), l_l_Top_0_Scale_0 (copy)
			l_Top_0:ScaleTo(l_l_Top_0_Scale_0 - v98);
		end);
		v18(v92.Root.LidFly);
		l_TweenService_0:Create(v95.Root, TweenInfo.new(8, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
			CFrame = v95.Root.CFrame * CFrame.new(0, 125, 0)
		}):Play();
		v35(15, TweenInfo.new(6, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), function(v99) --[[ Line: 290 ]]
			-- upvalues: v95 (copy)
			v95:ScaleTo(1 + v99);
		end);
		table.insert(v84, {
			v95.PrimaryPart.Rot, 
			"y", 
			3, 
			"C0"
		});
		v23(v92.Root.Open, true);
		for _, v101 in pairs(v92.Root.Open:GetChildren()) do
			if v101.Name == "Trail" then
				local l_Width0_0 = v101.Beam.Width0;
				local l_Width1_0 = v101.Beam.Width1;
				l_TweenService_0:Create(v101.Beam, TweenInfo.new(2, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
					Width0 = l_Width0_0, 
					Width1 = l_Width1_0
				}):Play();
				v101.Beam.Enabled = true;
			end;
		end;
		task.wait(8);
		l_TweenService_0:Create(v95.Root, TweenInfo.new(10, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
			CFrame = v82.MapPositions.component_positions.startCrystal.WorldCFrame
		}):Play();
		v35(14, TweenInfo.new(10, Enum.EasingStyle.Sine, Enum.EasingDirection.In), function(v104) --[[ Line: 318 ]]
			-- upvalues: v95 (copy)
			v95:ScaleTo(15 - v104);
		end);
		v23(v92.Root.Open, false);
		for _, v106 in pairs(v92.Root.Open:GetChildren()) do
			if v106.Name == "Trail" then
				l_TweenService_0:Create(v106.Beam, TweenInfo.new(2, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
					Brightness = 0
				}):Play();
				task.delay(2, function() --[[ Line: 330 ]]
					-- upvalues: v106 (copy)
					v106.Beam.Enabled = false;
				end);
			end;
		end;
		local v107 = v58(v95.Root, 3);
		task.wait(10);
		v107();
		v23(v95.Root.Traveling, false);
		return v95;
	end
};
v108.PlayEffect = function(_, v110, _) --[[ Line: 344 ]] --[[ Name: PlayEffect ]]
	-- upvalues: v9 (copy), v7 (copy), l_TweenService_0 (copy), l_Lighting_0 (copy), l_Assets_0 (copy), l_LocalPlayer_0 (copy), v108 (copy), v23 (copy), v35 (copy), v77 (copy), v18 (copy), v50 (copy), v80 (copy), v13 (copy)
	if not v9[v110.EventName] then
		return;
	else
		local l_Folder_0 = Instance.new("Folder");
		l_Folder_0.Parent = workspace;
		l_Folder_0.Name = "Debris " .. v110.EventName;
		local l_Folder_1 = Instance.new("Folder");
		l_Folder_1.Parent = workspace;
		l_Folder_1.Name = "IceCubesDebris " .. v110.EventName;
		local l_Map_0 = workspace:WaitForChild("Map");
		local l_CameraShaker_1 = v7.Utils.CameraShaker;
		local _ = v7.Utils.ForceEnable;
		local l_Transitions_1 = v7.Utils.Transitions;
		local _ = v7.Utils.Bezier;
		local _ = v7.Utils.Rift;
		local _ = v7.Utils.Lightning;
		local v121 = true;
		local v122 = {};
		task.spawn(function() --[[ Line: 369 ]]
			-- upvalues: v121 (ref), v122 (copy)
			while v121 do
				for _, v124 in pairs(v122) do
					if v124[1]:IsA("BasePart") then
						local v125 = v124[1];
						local l_CFrame_0 = v125.CFrame;
						local l_Angles_0 = CFrame.Angles;
						local v128 = false;
						if v124[2] == "x" then
							v128 = math.rad(v124[3]);
						end;
						local v129 = false;
						if v124[2] == "y" then
							v129 = math.rad(v124[3]);
						end;
						local v130 = false;
						if v124[2] == "z" then
							v130 = math.rad(v124[3]);
						end;
						v125.CFrame = l_CFrame_0 * l_Angles_0(v128, v129, v130);
					elseif v124[1]:IsA("Weld") then
						local v131 = v124[1];
						local v132 = v124[4];
						local v133 = v131[v132];
						local l_Angles_1 = CFrame.Angles;
						local v135 = false;
						if v124[2] == "x" then
							v135 = math.rad(v124[3]);
						end;
						local v136 = false;
						if v124[2] == "y" then
							v136 = math.rad(v124[3]);
						end;
						local v137 = false;
						if v124[2] == "z" then
							v137 = math.rad(v124[3]);
						end;
						v131[v132] = v133 * l_Angles_1(v135, v136, v137);
					end;
				end;
				task.wait();
			end;
		end);
		l_TweenService_0:Create(l_Lighting_0, TweenInfo.new(2.5, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
			ClockTime = 0
		}):Play();
		local l_ChristmasEvent_0 = l_Assets_0.Sound.ChristmasEvent;
		local l_l_LocalPlayer_0_0 = l_LocalPlayer_0;
		local v140 = l_ChristmasEvent_0:Clone();
		v140.Parent = l_l_LocalPlayer_0_0;
		v140.Volume = 1;
		v140:Play();
		local l_v140_0 = v140 --[[ copy: 17 -> 24 ]];
		task.delay(75, function() --[[ Line: 71 ]]
			-- upvalues: l_v140_0 (copy)
			if not l_v140_0.Parent then
				return;
			else
				l_v140_0:Destroy();
				return;
			end;
		end);
		l_ChristmasEvent_0 = OverlapParams.new();
		l_ChristmasEvent_0.FilterType = Enum.RaycastFilterType.Whitelist --[[ 2021 ]];
		l_ChristmasEvent_0.FilterDescendantsInstances = {
			l_Map_0:WaitForChild("Adverts"), 
			l_Map_0:WaitForChild("Buildings"), 
			l_Map_0:WaitForChild("Adverts"), 
			l_Map_0:WaitForChild("Decoration"), 
			l_Map_0:WaitForChild("Environment")
		};
		l_l_LocalPlayer_0_0 = workspace:GetPartBoundsInRadius(v110.MapPositions.component_positions.startCrystal.WorldCFrame.Position, 165, l_ChristmasEvent_0);
		v140 = v108:Intro(v110, l_Folder_0, v122);
		l_TweenService_0:Create(v140.PrimaryPart, TweenInfo.new(15, Enum.EasingStyle.Linear, Enum.EasingDirection.In), {
			CFrame = v110.MapPositions.component_positions.endCrystal.WorldCFrame * v140:GetPivot().Rotation
		}):Play();
		v23(v140.Root.Main, true);
		v35(5, TweenInfo.new(25, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), function(v142) --[[ Line: 419 ]]
			-- upvalues: v140 (copy)
			v140:ScaleTo(math.clamp(v142, 0.05, 5) + 1);
		end);
		local v143 = l_Assets_0.Particles.Snow:Clone();
		v143.Parent = l_Folder_0;
		v143.CFrame = v110.MapPositions.weather_positions.snow_flurry.WorldCFrame;
		local v144 = l_Assets_0.Models.SnowFloor:Clone();
		v144.Parent = workspace;
		v144.CFrame = v110.MapPositions.weather_positions.snow_floor_start.WorldCFrame;
		local v145 = {
			v143, 
			"y", 
			0.45
		};
		table.insert(v122, v145);
		l_CameraShaker_1.inst:ShakeSustain(l_CameraShaker_1.mod.Presets.CrystalCharging);
		task.delay(10.625, function() --[[ Line: 437 ]]
			-- upvalues: v140 (copy), l_TweenService_0 (ref), v77 (ref), v23 (ref), v143 (copy), v18 (ref), l_CameraShaker_1 (copy), v50 (ref), l_l_LocalPlayer_0_0 (copy), v80 (ref)
			local v146 = TweenInfo.new(3, Enum.EasingStyle.Sine, Enum.EasingDirection.Out);
			for _, v148 in pairs(v140:GetDescendants()) do
				if v148:IsA("BasePart") then
					l_TweenService_0:Create(v148, v146, {
						Color = Color3.fromRGB(255, 255, 255)
					}):Play();
				elseif v148:IsA("Decal") then
					l_TweenService_0:Create(v148, v146, {
						Color3 = Color3.fromRGB(255, 255, 255)
					}):Play();
				elseif v148:IsA("ParticleEmitter") then
					task.spawn(v77, v148, 2.4, v148.Color.Keypoints[1].Value, Color3.fromRGB(255, 255, 255));
				end;
			end;
			v23(v143, true);
			v23(v140.Root.Intense, true);
			v23(v140.Root.Main, false);
			v18(v140.Root.Explosion);
			l_CameraShaker_1.inst:Shake(l_CameraShaker_1.mod.Presets.CrystalExplode);
			task.delay(0.25, function() --[[ Line: 467 ]]
				-- upvalues: l_CameraShaker_1 (ref)
				l_CameraShaker_1.inst:ShakeSustain(l_CameraShaker_1.mod.Presets.CrystalStorm);
			end);
			v50(25, 1, 3, 1.25);
			task.spawn(function() --[[ Line: 473 ]]
				-- upvalues: l_l_LocalPlayer_0_0 (ref), v80 (ref)
				for _, v150 in ipairs(l_l_LocalPlayer_0_0) do
					if v150:IsA("BasePart") and v150.Transparency ~= 1 and v150.Material ~= Enum.Material.Neon then
						v80(v150);
					end;
				end;
			end);
		end);
		task.delay(15.625, function() --[[ Line: 482 ]]
			-- upvalues: l_TweenService_0 (ref), l_Lighting_0 (ref), v145 (copy), v23 (ref), v143 (copy)
			l_TweenService_0:Create(l_Lighting_0.Atmosphere, TweenInfo.new(3.75, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
				Color = Color3.fromRGB(255, 255, 255), 
				Decay = Color3.fromRGB(255, 255, 255), 
				Glare = 2.04, 
				Haze = 2.05, 
				Density = 0.3
			}):Play();
			v145[3] = 0.6;
			v23(v143.Core, true);
		end);
		task.delay(16.25, function() --[[ Line: 498 ]]
			-- upvalues: l_Assets_0 (ref), l_Folder_1 (copy), v13 (ref), v110 (copy), l_TweenService_0 (ref)
			for _ = 1, 50 do
				local v152 = l_Assets_0.Models.IceCube:Clone();
				v152.Parent = l_Folder_1;
				v152.Size = Vector3.new(10, 10, 10, 0) * v13:NextNumber(1.5, 3.4);
				v152.CFrame = v110.MapPositions.weather_positions.ice_cube_start.WorldCFrame * CFrame.new(v13:NextNumber(-110, 110), -v152.Size.Y / 2, v13:NextNumber(-110, 110)) * CFrame.Angles(math.rad((v13:NextNumber(-360, 360))), math.rad((v13:NextNumber(-360, 360))), (math.rad((v13:NextNumber(-360, 360)))));
				l_TweenService_0:Create(v152, TweenInfo.new(v13:NextNumber(10, 15) * 1.25, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
					Position = v152.Position + Vector3.new(0, v110.MapPositions.weather_positions.ice_cube_end.WorldCFrame.Position.Y + v152.Size.Y / 2, 0)
				}):Play();
				task.wait();
			end;
		end);
		task.delay(18.75, function() --[[ Line: 517 ]]
			-- upvalues: v143 (copy), v23 (ref), l_TweenService_0 (ref), v121 (ref), v35 (ref), v140 (copy)
			for _, v154 in pairs(v143.Beams:GetChildren()) do
				v23(v154, true);
				v154:SetAttribute("direction", math.random(1, 2) == 1 and "up" or "down");
				local l_Y_0 = v154["0"].CFrame.Y;
				local l_Y_1 = v154["1"].CFrame.Y;
				v154["0"].CFrame = CFrame.new(0, 0, 0);
				v154["1"].CFrame = CFrame.new(0, 0, 0);
				l_TweenService_0:Create(v154["0"], TweenInfo.new(0.8125, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
					CFrame = CFrame.new(0, l_Y_0, 0)
				}):Play();
				l_TweenService_0:Create(v154["1"], TweenInfo.new(0.8125, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
					CFrame = CFrame.new(0, l_Y_1, 0)
				}):Play();
			end;
			task.spawn(function() --[[ Line: 538 ]]
				-- upvalues: v121 (ref), v143 (ref), l_TweenService_0 (ref)
				while v121 do
					for _, v158 in pairs(v143.Beams:GetChildren()) do
						if v158:GetAttribute("direction") == "up" then
							l_TweenService_0:Create(v158, TweenInfo.new(3.75, Enum.EasingStyle.Linear, Enum.EasingDirection.Out), {
								CFrame = v158.CFrame * CFrame.new(0, -45, 0)
							}):Play();
							v158:SetAttribute("direction", "down");
						else
							l_TweenService_0:Create(v158, TweenInfo.new(3.75, Enum.EasingStyle.Linear, Enum.EasingDirection.Out), {
								CFrame = v158.CFrame * CFrame.new(0, 45, 0)
							}):Play();
							v158:SetAttribute("direction", "up");
						end;
					end;
					task.wait(3.75);
				end;
			end);
			v35(2, TweenInfo.new(3.75, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), function(v159) --[[ Line: 560 ]]
				-- upvalues: v140 (ref)
				v140:ScaleTo(5 + v159);
			end);
		end);
		local v160 = nil;
		local v161 = nil;
		task.delay(25, function() --[[ Line: 566 ]]
			-- upvalues: l_TweenService_0 (ref), v144 (copy), v110 (copy), v160 (ref), v161 (ref), l_Transitions_1 (copy), l_CameraShaker_1 (copy), v121 (ref), l_Folder_0 (copy), v7 (ref), l_Lighting_0 (ref), l_Folder_1 (copy), v13 (ref)
			l_TweenService_0:Create(v144, TweenInfo.new(6.5625, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
				CFrame = v110.MapPositions.weather_positions.snow_floor_end.WorldCFrame
			}):Play();
			task.delay(1.875, function() --[[ Line: 572 ]]
				-- upvalues: v160 (ref), v161 (ref), l_Transitions_1 (ref), l_CameraShaker_1 (ref), v121 (ref), l_Folder_0 (ref), v7 (ref), l_Lighting_0 (ref), l_Folder_1 (ref), l_TweenService_0 (ref), v13 (ref), v144 (ref), v110 (ref)
				local v162, v163 = l_Transitions_1:White(5, true);
				v160 = v162;
				v161 = v163;
				task.delay(5, function() --[[ Line: 575 ]]
					-- upvalues: l_CameraShaker_1 (ref), v121 (ref), l_Folder_0 (ref), v7 (ref), l_Lighting_0 (ref), l_Folder_1 (ref), l_TweenService_0 (ref), v13 (ref), v144 (ref), v110 (ref), v160 (ref), v161 (ref)
					local v164 = false;
					local function v171() --[[ Line: 578 ]] --[[ Name: loadOut ]]
						-- upvalues: l_CameraShaker_1 (ref), v121 (ref), l_Folder_0 (ref), v7 (ref), l_Lighting_0 (ref), l_Folder_1 (ref), l_TweenService_0 (ref), v13 (ref), v144 (ref), v110 (ref), v160 (ref)
						l_CameraShaker_1.inst:StopSustained(0);
						v121 = false;
						l_Folder_0:Destroy();
						for v165, v166 in pairs(v7.DefaultLighting.lighting) do
							l_Lighting_0[v165] = v166;
						end;
						for v167, v168 in pairs(v7.DefaultLighting.atmosphere) do
							l_Lighting_0.Atmosphere[v167] = v168;
						end;
						for _, v170 in pairs(l_Folder_1:GetChildren()) do
							l_TweenService_0:Create(v170, TweenInfo.new(v13:NextNumber(15, 20) * 1.25, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
								Position = v170.Position + Vector3.new(0, -v170.Size.Y, 0)
							}):Play();
						end;
						l_TweenService_0:Create(v144, TweenInfo.new(25, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
							CFrame = v110.MapPositions.weather_positions.snow_floor_start.WorldCFrame * CFrame.new(0, -10, 0)
						}):Play();
						task.delay(37.5, function() --[[ Line: 603 ]]
							-- upvalues: l_Folder_1 (ref), v144 (ref)
							l_Folder_1:Destroy();
							v144:Destroy();
						end);
						task.delay(2.5, function() --[[ Line: 608 ]]
							-- upvalues: v160 (ref)
							v160(5);
						end);
					end;
					v161(function() --[[ Line: 613 ]]
						-- upvalues: v164 (ref), v171 (copy)
						if v164 then
							return;
						else
							v171();
							v164 = true;
							return;
						end;
					end);
					task.delay(45, function() --[[ Line: 619 ]]
						-- upvalues: v164 (ref), v171 (copy)
						if v164 then
							return;
						else
							v171();
							v164 = true;
							return;
						end;
					end);
				end);
			end);
			l_CameraShaker_1.inst:ShakeSustain(l_CameraShaker_1.mod.Presets.CrystalStormPeak);
		end);
		return;
	end;
end;
return v108;