-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_ContextActionService_0 = game:GetService("ContextActionService");
local l_UserInputService_99 = game:GetService("UserInputService"); --[[ 2021: legacy chat has no ChatInputBarConfiguration; use focused-textbox check ]]
local l_UserInputService_0 = game:GetService("UserInputService");
local l_StarterGui_0 = game:GetService("StarterGui");
local l_GuiService_0 = game:GetService("GuiService");
local l_RunService_0 = game:GetService("RunService");
local l_VRService_0 = game:GetService("VRService");
local l_TweenService_0 = game:GetService("TweenService");
local l_Players_0 = game:GetService("Players");
local l_PlayerGui_0 = l_Players_0.LocalPlayer:WaitForChild("PlayerGui");
local v10 = {
    OpenClose = nil, 
    IsOpen = false, 
    StateChanged = Instance.new("BindableEvent"), 
    ModuleName = "Backpack", 
    KeepVRTopbarOpen = true, 
    VRIsExclusive = true, 
    VRClosesNonExclusive = true, 
    BackpackEmpty = Instance.new("BindableEvent")
};
v10.BackpackEmpty.Name = "BackpackEmpty";
v10.BackpackItemAdded = Instance.new("BindableEvent");
v10.BackpackItemAdded.Name = "BackpackAdded";
v10.BackpackItemRemoved = Instance.new("BindableEvent");
v10.BackpackItemRemoved.Name = "BackpackRemoved";
local l_script_0 = script;
require(script.Attribution);
local v12 = l_GuiService_0.PreferredTransparency or 1;
local v13 = not l_script_0:GetAttribute("OutlineEquipBorder") or false;
local l_l_script_0_Attribute_0 = l_script_0:GetAttribute("InsetIconPadding");
local v15 = l_script_0:GetAttribute("BackgroundTransparency") or 0.3;
local v16 = v15 * v12;
local v17 = UDim.new(0, 8);
local v18 = l_script_0:GetAttribute("BackgroundColor3") or Color3.new(0.09803921568627451, 0.10588235294117647, 0.11372549019607843);
local v19 = l_script_0:GetAttribute("EquipBorderColor3") or Color3.new(0, 0.6352941176470588, 1);
local v20 = l_script_0:GetAttribute("BackgroundTransparency") or 0.3;
local v21 = v20 * v12;
local v22 = l_script_0:GetAttribute("EquipBorderSizePixel") or 5;
local v23 = l_script_0:GetAttribute("CornerRadius") or UDim.new(0, 8);
local v24 = Color3.new(1, 1, 1);
local v25 = v23 - UDim.new(0, 5) or UDim.new(0, 3);
local v26 = l_script_0:GetAttribute("BackgroundColor3") or Color3.new(0.09803921568627451, 0.10588235294117647, 0.11372549019607843);
local v27 = l_script_0:GetAttribute("TextColor3") or Color3.new(1, 1, 1);
local v28 = l_script_0:GetAttribute("TextStrokeTransparency") or 0.5;
local v29 = l_script_0:GetAttribute("TextStrokeColor3") or Color3.new(0, 0, 0);
local v30 = Color3.new(1, 1, 1);
local v31 = v12 * 0.5;
local v32 = Color3.new(1, 1, 1);
local v33 = UDim.new(0, 8);
local v34 = "BuilderSans"; --[[ 2021: legacy Enum.Font only ]]
local v35 = l_script_0:GetAttribute("TextSize") or 16;
local l_Value_0 = Enum.KeyCode.Backspace.Value;
local l_Value_1 = Enum.KeyCode.Zero.Value;
local v38 = 48;
local v39 = {
    [Enum.UserInputType.MouseButton1] = true, 
    [Enum.UserInputType.MouseButton2] = true, 
    [Enum.UserInputType.MouseButton3] = true, 
    [Enum.UserInputType.MouseMovement] = true, 
    [Enum.UserInputType.MouseWheel] = true
};
local v40 = {
    [Enum.UserInputType.Gamepad1] = true, 
    [Enum.UserInputType.Gamepad2] = true, 
    [Enum.UserInputType.Gamepad3] = true, 
    [Enum.UserInputType.Gamepad4] = true, 
    [Enum.UserInputType.Gamepad5] = true, 
    [Enum.UserInputType.Gamepad6] = true, 
    [Enum.UserInputType.Gamepad7] = true, 
    [Enum.UserInputType.Gamepad8] = true
};
local v41 = true;
local v42 = require(script.Parent.topbarplus).new():setName("Inventory"):setImage("rbxasset://textures/ui/TopBar/inventoryOn.png", "Selected"):setImage("rbxasset://textures/ui/TopBar/inventoryOff.png", "Deselected"):setImageScale(1):setCaption("Inventory"):bindToggleKey(Enum.KeyCode.Backquote):autoDeselect(false):setOrder(-1);
v42.toggled:Connect(function() --[[ Line: 157 ]]
    -- upvalues: l_GuiService_0 (copy), v10 (copy)
    if not l_GuiService_0.MenuIsOpen then
        v10.OpenClose();
    end;
end);
local l_ScreenGui_0 = Instance.new("ScreenGui");
l_ScreenGui_0.DisplayOrder = 120;
l_ScreenGui_0.IgnoreGuiInset = true;
l_ScreenGui_0.ResetOnSpawn = false;
l_ScreenGui_0.Name = "BackpackGui";
l_ScreenGui_0.Parent = l_PlayerGui_0;
local v44 = l_GuiService_0:IsTenFootInterface();
if v44 then
    v38 = 100;
    v35 = 24;
end;
local v45 = false;
local v46 = l_UserInputService_0.TouchEnabled and workspace.CurrentCamera.ViewportSize.X < 1024;
local l_LocalPlayer_0 = l_Players_0.LocalPlayer;
local v48 = nil;
local v49 = nil;
local v50 = nil;
local v51 = nil;
local v52 = nil;
local v53 = nil;
local v54 = nil;
local v55 = nil;
local v56 = nil;
local v57 = nil;
local v58 = l_LocalPlayer_0.Character or l_LocalPlayer_0.CharacterAdded:Wait();
local l_Humanoid_0 = v58:WaitForChild("Humanoid");
local l_Backpack_0 = l_LocalPlayer_0:WaitForChild("Backpack");
local v61 = {};
local v62 = nil;
local v63 = {};
local v64 = {};
local v65 = {};
local v66 = 0;
local v67 = nil;
local v68 = false;
local v69 = false;
local v70 = false;
local v71 = false;
local v72 = {};
local v73 = false;
local l_VREnabled_0 = l_VRService_0.VREnabled;
local v75 = l_VREnabled_0 and 6 or v46 and 6 or 10;
local v76 = l_VREnabled_0 and 3 or v46 and 2 or 4;
local v77 = nil;
local function _(v78) --[[ Line: 220 ]] --[[ Name: EvaluateBackpackPanelVisibility ]]
    -- upvalues: v42 (copy), v41 (ref), l_VRService_0 (copy)
    return v78 and v42.enabled and v41 and l_VRService_0.VREnabled;
end;
local function _() --[[ Line: 224 ]] --[[ Name: ShowVRBackpackPopup ]]

end;
local function _() --[[ Line: 230 ]] --[[ Name: FindLowestEmpty ]]
    -- upvalues: v75 (copy), v61 (copy)
    for v81 = 1, v75 do
        local v82 = v61[v81];
        if not v82.Tool then
            return v82;
        end;
    end;
    return nil;
end;
v10.IsInventoryEmpty = function() --[[ Line: 240 ]] --[[ Name: isInventoryEmpty ]]
    -- upvalues: v75 (copy), v61 (copy)
    for v84 = v75 + 1, #v61 do
        local v85 = v61[v84];
        if v85 and v85.Tool then
            return false;
        end;
    end;
    return true;
end;
local function _() --[[ Line: 252 ]] --[[ Name: UseGazeSelection ]]
    return false;
end;
local function v92() --[[ Line: 256 ]] --[[ Name: AdjustHotbarFrames ]]
    -- upvalues: v50 (ref), v75 (copy), v66 (ref), v61 (copy)
    local l_Visible_0 = v50.Visible;
    local v88 = l_Visible_0 and v75 or v66;
    local v89 = 0;
    for v90 = 1, v75 do
        local v91 = v61[v90];
        if v91.Tool or l_Visible_0 then
            v89 = v89 + 1;
            v91:Readjust(v89, v88);
            v91.Frame.Visible = true;
        else
            v91.Frame.Visible = false;
        end;
    end;
end;
local function _() --[[ Line: 273 ]] --[[ Name: UpdateScrollingFrameCanvasSize ]]
    -- upvalues: v52 (ref), v38 (ref), v53 (ref)
    local v93 = math.floor(v52.AbsoluteSize.X / (v38 + 10));
    local v94 = math.ceil((#v53:GetChildren() - 1) / v93) * (v38 + 10) + 10;
    v52.CanvasSize = UDim2.fromOffset(0, v94);
end;
local function v100() --[[ Line: 280 ]] --[[ Name: AdjustInventoryFrames ]]
    -- upvalues: v75 (copy), v61 (copy), v52 (ref), v38 (ref), v53 (ref)
    for v96 = v75 + 1, #v61 do
        local v97 = v61[v96];
        v97.Frame.LayoutOrder = v97.Index;
        v97.Frame.Visible = v97.Tool ~= nil;
    end;
    local v98 = math.floor(v52.AbsoluteSize.X / (v38 + 10));
    local v99 = math.ceil((#v53:GetChildren() - 1) / v98) * (v38 + 10) + 10;
    v52.CanvasSize = UDim2.fromOffset(0, v99);
end;
local function v101() --[[ Line: 289 ]] --[[ Name: UpdateBackpackLayout ]]
    -- upvalues: v49 (ref), v75 (copy), v38 (ref), v50 (ref), v76 (copy), l_VREnabled_0 (copy), v52 (ref), v92 (copy), v100 (copy)
    v49.Size = UDim2.new(0, v75 * (v38 + 10) + 10, 0, v38 + 10 + 10);
    v49.Position = UDim2.new(0.5, -v49.Size.X.Offset / 2, 1, -v49.Size.Y.Offset - 20);
    v50.Size = UDim2.new(0, v49.Size.X.Offset, 0, v49.Size.Y.Offset * v76 + 40 + (l_VREnabled_0 and 80 or 0));
    v50.Position = UDim2.new(0.5, -v50.Size.X.Offset / 2, 1, v49.Position.Y.Offset - v50.Size.Y.Offset);
    v52.Size = UDim2.new(1, v52.ScrollBarThickness + 1, 1, -40 - (l_VREnabled_0 and 80 or 0));
    v52.Position = UDim2.fromOffset(0, 40 + (l_VREnabled_0 and 40 or 0));
    v92();
    v100();
end;
local function _(v102, v103, v104) --[[ Line: 323 ]] --[[ Name: Clamp ]]
    return (math.min(v103, (math.max(v102, v104))));
end;
local function _(v106, v107, v108) --[[ Line: 327 ]] --[[ Name: CheckBounds ]]
    local l_AbsolutePosition_0 = v106.AbsolutePosition;
    local l_AbsoluteSize_0 = v106.AbsoluteSize;
    local v111 = false;
    if l_AbsolutePosition_0.X < v107 then
        v111 = false;
        if v107 <= l_AbsolutePosition_0.X + l_AbsoluteSize_0.X then
            v111 = false;
            if l_AbsolutePosition_0.Y < v108 then
                v111 = v108 <= l_AbsolutePosition_0.Y + l_AbsoluteSize_0.Y;
            end;
        end;
    end;
    return v111;
end;
local function _(v113, v114) --[[ Line: 333 ]] --[[ Name: GetOffset ]]
    return (v113.AbsolutePosition + v113.AbsoluteSize / 2 - v114).Magnitude;
end;
local function _() --[[ Line: 338 ]] --[[ Name: DisableActiveHopper ]]
    -- upvalues: v67 (ref), v63 (copy)
    v67:ToggleSelect();
    v63[v67]:UpdateEquipView();
    v67 = nil;
end;
local function _() --[[ Line: 344 ]] --[[ Name: UnequipAllTools ]]
    -- upvalues: l_Humanoid_0 (ref), v67 (ref), v63 (copy)
    if l_Humanoid_0 then
        l_Humanoid_0:UnequipTools();
        if v67 then
            v67:ToggleSelect();
            v63[v67]:UpdateEquipView();
            v67 = nil;
        end;
    end;
end;
local function _(v118) --[[ Line: 353 ]] --[[ Name: EquipNewTool ]]
    -- upvalues: l_Humanoid_0 (ref), v67 (ref), v63 (copy)
    if l_Humanoid_0 then
        l_Humanoid_0:UnequipTools();
        if v67 then
            v67:ToggleSelect();
            v63[v67]:UpdateEquipView();
            v67 = nil;
        end;
    end;
    l_Humanoid_0:EquipTool(v118);
end;
local function _(v120) --[[ Line: 359 ]] --[[ Name: IsEquipped ]]
    -- upvalues: v58 (ref)
    return v120 and v120.Parent == v58;
end;
local function v122(v123, v124) --[[ Line: 364 ]] --[[ Name: MakeSlot ]]
    -- upvalues: v61 (copy), v21 (ref), v49 (ref), v38 (ref), v75 (copy), v50 (ref), l_UserInputService_0 (copy), v66 (ref), v69 (ref), v45 (ref), l_ContextActionService_0 (copy), v57 (ref), v63 (copy), v62 (ref), v58 (ref), v77 (ref), v22 (copy), v19 (copy), v13 (copy), l_TweenService_0 (copy), v52 (ref), v53 (ref), l_Humanoid_0 (ref), v67 (ref), l_Backpack_0 (ref), v18 (copy), v24 (copy), v23 (copy), l_l_script_0_Attribute_0 (copy), v27 (copy), v28 (copy), v29 (copy), v34 (copy), v35 (ref), v26 (copy), v25 (copy), v122 (copy), v71 (ref), v64 (copy), l_Value_1 (copy), v65 (copy), v42 (copy)
    local v125 = v124 or #v61 + 1;
    local v126 = {
        Tool = nil, 
        Index = v125, 
        Frame = nil
    };
    local v127 = nil;
    local v128 = nil;
    local v129 = nil;
    local v130 = nil;
    local v131 = nil;
    local v132 = nil;
    local v133 = nil;
    local v134 = nil;
    local v135 = nil;
    local function _() --[[ Line: 389 ]] --[[ Name: UpdateSlotFading ]]
        -- upvalues: v127 (ref), v21 (ref)
        v127.SelectionImageObject = nil;
        v127.BackgroundTransparency = v127.Draggable and 0 or v21;
    end;
    v126.Readjust = function(_, v138, v139) --[[ Line: 395 ]] --[[ Name: Readjust ]]
        -- upvalues: v49 (ref), v38 (ref), v127 (ref)
        local v140 = v49.Size.X.Offset / 2;
        local v141 = v38 + 10;
        local v142 = v138 - (v139 / 2 + 0.5);
        v127.Position = UDim2.fromOffset(v140 - v38 / 2 + v141 * v142, 10);
    end;
    v126.Fill = function(v143, v144) --[[ Line: 405 ]] --[[ Name: Fill ]]
        -- upvalues: v129 (ref), v130 (ref), v134 (ref), v131 (ref), v75 (ref), v50 (ref), l_UserInputService_0 (ref), v127 (ref), v66 (ref), v69 (ref), v45 (ref), l_ContextActionService_0 (ref), v57 (ref), v63 (ref), v62 (ref), v61 (ref)
        local v145 = false;
        if not v144 then
            return v143:Clear();
        else
            v143.Tool = v144;
            local function v147() --[[ Line: 414 ]] --[[ Name: assignToolData ]]
                -- upvalues: v144 (copy), v129 (ref), v130 (ref), v134 (ref)
                local l_TextureId_0 = v144.TextureId;
                v129.Image = l_TextureId_0;
                if l_TextureId_0 ~= "" then
                    v130.Visible = false;
                else
                    v130.Visible = true;
                end;
                v130.Text = v144.Name;
                if v134 and v144:IsA("Tool") then
                    v134.Text = v144.ToolTip;
                    v134.Size = UDim2.fromOffset(0, 16);
                    v134.Position = UDim2.new(0.5, 0, 0, -5);
                end;
            end;
            v147();
            if v131 then
                v131:Disconnect();
                v131 = nil;
            end;
            v131 = v144.Changed:Connect(function(v148) --[[ Line: 443 ]]
                -- upvalues: v147 (copy)
                if v148 == "TextureId" or v148 == "Name" or v148 == "ToolTip" then
                    v147();
                end;
            end);
            local v149 = v143.Index <= v75;
            local l_Visible_1 = v50.Visible;
            if (not v149 or l_Visible_1) and not l_UserInputService_0.VREnabled then
                v127.Draggable = true;
            end;
            v143:UpdateEquipView();
            if v149 then
                v66 = v66 + 1;
                if v69 and v66 >= 1 and not v45 then
                    v45 = true;
                    l_ContextActionService_0:BindAction("BackpackHotbarEquip", v57, false, Enum.KeyCode.ButtonL1, Enum.KeyCode.ButtonR1);
                end;
            end;
            v63[v144] = v143;
            local v151;
            for v152 = 1, v75 do
                local v153 = v61[v152];
                if not v153.Tool then
                    v151 = v153;
                    v145 = true;
                end;
                if v145 then
                    break;
                end;
            end;
            if not v145 then
                v151 = nil;
            end;
            v145 = false;
            v62 = v151;
            return;
        end;
    end;
    v126.Clear = function(v154) --[[ Line: 479 ]] --[[ Name: Clear ]]
        -- upvalues: v131 (ref), v129 (ref), v130 (ref), v134 (ref), v127 (ref), v75 (ref), v66 (ref), v45 (ref), l_ContextActionService_0 (ref), v63 (ref), v62 (ref), v61 (ref)
        local v155 = false;
        if not v154.Tool then
            return;
        else
            if v131 then
                v131:Disconnect();
                v131 = nil;
            end;
            v129.Image = "";
            v130.Text = "";
            if v134 then
                v134.Text = "";
                v134.Visible = false;
            end;
            v127.Draggable = false;
            v154:UpdateEquipView(true);
            if v154.Index <= v75 then
                v66 = v66 - 1;
                if v66 < 1 then
                    v45 = false;
                    l_ContextActionService_0:UnbindAction("BackpackHotbarEquip");
                end;
            end;
            v63[v154.Tool] = nil;
            v154.Tool = nil;
            local v156;
            for v157 = 1, v75 do
                local v158 = v61[v157];
                if not v158.Tool then
                    v156 = v158;
                    v155 = true;
                end;
                if v155 then
                    break;
                end;
            end;
            if not v155 then
                v156 = nil;
            end;
            v155 = false;
            v62 = v156;
            return;
        end;
    end;
    v126.UpdateEquipView = function(v159, v160) --[[ Line: 514 ]] --[[ Name: UpdateEquipView ]]
        -- upvalues: v58 (ref), v77 (ref), v126 (copy), v132 (ref), v22 (ref), v19 (ref), v13 (ref), v129 (ref), v127 (ref), l_TweenService_0 (ref), v21 (ref)
        local v161 = false;
        local v162;
        if not (v160 or false) then
            local l_Tool_0 = v159.Tool;
            if l_Tool_0 and l_Tool_0.Parent == v58 then
                v77 = v126;
                if not v132 then
                    v132 = Instance.new("UIStroke");
                    v132.Name = "Border";
                    v132.Thickness = v22;
                    v132.Color = v19;
                    v132.ApplyStrokeMode = Enum.ApplyStrokeMode.Border;
                end;
                if v13 == true then
                    v132.Parent = v129;
                else
                    v132.Parent = v127;
                end;
                v162 = v127:FindFirstChild("SlotStroke");
                if v162 then
                    l_TweenService_0:Create(v162, TweenInfo.new(0.25), {
                        Color = v19
                    }):Play();
                    v161 = true;
                else
                    v161 = true;
                end;
            end;
        end;
        if not v161 then
            if not v161 then
                if v132 then
                    v132.Parent = nil;
                end;
                v162 = v127:FindFirstChild("SlotStroke");
                if v162 then
                    l_TweenService_0:Create(v162, TweenInfo.new(0.25), {
                        Color = Color3.new(1, 1, 1)
                    }):Play();
                end;
            end;
        end;
        v161 = false;
        v127.SelectionImageObject = nil;
        v127.BackgroundTransparency = v127.Draggable and 0 or v21;
    end;
    v126.IsEquipped = function(v164) --[[ Line: 544 ]] --[[ Name: IsEquipped ]]
        -- upvalues: v58 (ref)
        local l_Tool_1 = v164.Tool;
        return l_Tool_1 and l_Tool_1.Parent == v58;
    end;
    v126.Delete = function(v166) --[[ Line: 548 ]] --[[ Name: Delete ]]
        -- upvalues: v127 (ref), v61 (ref), v52 (ref), v38 (ref), v53 (ref)
        v127:Destroy();
        table.remove(v61, v166.Index);
        local v167 = #v61;
        for v168 = v166.Index, v167 do
            v61[v168]:SlideBack();
        end;
        local v169 = math.floor(v52.AbsoluteSize.X / (v38 + 10));
        local v170 = math.ceil((#v53:GetChildren() - 1) / v169) * (v38 + 10) + 10;
        v52.CanvasSize = UDim2.fromOffset(0, v170);
    end;
    v126.Swap = function(v171, v172) --[[ Line: 561 ]] --[[ Name: Swap ]]
        local l_Tool_2 = v171.Tool;
        local l_Tool_3 = v172.Tool;
        v171:Clear();
        if l_Tool_3 then
            v172:Clear();
            v171:Fill(l_Tool_3);
        end;
        if l_Tool_2 then
            v172:Fill(l_Tool_2);
            return;
        else
            v172:Clear();
            return;
        end;
    end;
    v126.SlideBack = function(v175) --[[ Line: 575 ]] --[[ Name: SlideBack ]]
        -- upvalues: v127 (ref)
        v175.Index = v175.Index - 1;
        v127.Name = v175.Index;
        v127.LayoutOrder = v175.Index;
    end;
    v126.TurnNumber = function(_, v177) --[[ Line: 581 ]] --[[ Name: TurnNumber ]]
        -- upvalues: v135 (ref)
        if v135 then
            v135.Visible = v177;
        end;
    end;
    v126.SetClickability = function(v178, v179) --[[ Line: 587 ]] --[[ Name: SetClickability ]]
        -- upvalues: l_UserInputService_0 (ref), v127 (ref), v21 (ref)
        if v178.Tool then
            if l_UserInputService_0.VREnabled then
                v127.Draggable = false;
            else
                v127.Draggable = not v179;
            end;
            v127.SelectionImageObject = nil;
            v127.BackgroundTransparency = v127.Draggable and 0 or v21;
        end;
    end;
    v126.CheckTerms = function(v180, v181) --[[ Line: 598 ]] --[[ Name: CheckTerms ]]
        -- upvalues: v130 (ref), v134 (ref)
        local v182 = 0;
        local _ = function(v183, v184) --[[ Line: 600 ]] --[[ Name: checkEm ]]
            -- upvalues: v182 (ref)
            local _, v186 = v183:lower():gsub(v184, "");
            v182 = v182 + v186;
        end;
        local l_Tool_4 = v180.Tool;
        if l_Tool_4 then
            for v189 in pairs(v181) do
                local v190, v191 = v130.Text:lower():gsub(v189, "");
                v182 = v182 + v191;
                if l_Tool_4:IsA("Tool") then
                    v190, v191 = (v134 and v134.Text or ""):lower():gsub(v189, "");
                    v182 = v182 + v191;
                end;
            end;
        end;
        return v182;
    end;
    v126.Select = function(_) --[[ Line: 618 ]] --[[ Name: Select ]]
        -- upvalues: v126 (copy), v58 (ref), l_Humanoid_0 (ref), v67 (ref), v63 (ref), l_Backpack_0 (ref)
        local l_Tool_5 = v126.Tool;
        if l_Tool_5 then
            if l_Tool_5 and l_Tool_5.Parent == v58 then
                if l_Humanoid_0 then
                    l_Humanoid_0:UnequipTools();
                    if v67 then
                        v67:ToggleSelect();
                        v63[v67]:UpdateEquipView();
                        v67 = nil;
                        return;
                    end;
                end;
            elseif l_Tool_5.Parent == l_Backpack_0 then
                if l_Humanoid_0 then
                    l_Humanoid_0:UnequipTools();
                    if v67 then
                        v67:ToggleSelect();
                        v63[v67]:UpdateEquipView();
                        v67 = nil;
                    end;
                end;
                l_Humanoid_0:EquipTool(l_Tool_5);
            end;
        end;
    end;
    v127 = Instance.new("TextButton");
    v127.Name = tostring(v125);
    v127.BackgroundColor3 = v18;
    v127.BorderColor3 = v24;
    v127.Text = "";
    v127.BorderSizePixel = 0;
    v127.Size = UDim2.fromOffset(v38, v38);
    v127.Active = true;
    v127.Draggable = false;
    v127.BackgroundTransparency = v21;
    v127.MouseButton1Click:Connect(function() --[[ Line: 641 ]]
        -- upvalues: v126 (copy)
        changeSlot(v126);
    end);
    local l_UICorner_0 = Instance.new("UICorner");
    l_UICorner_0.Name = "Corner";
    l_UICorner_0.CornerRadius = v23;
    l_UICorner_0.Parent = v127;
    local l_UIStroke_0 = Instance.new("UIStroke");
    l_UIStroke_0.Name = "SlotStroke";
    l_UIStroke_0.Color = Color3.new(1, 1, 1);
    l_UIStroke_0.Thickness = 3;
    l_UIStroke_0.ApplyStrokeMode = Enum.ApplyStrokeMode.Border;
    l_UIStroke_0.Parent = v127;
    v126.Frame = v127;
    local l_Frame_0 = Instance.new("Frame");
    l_Frame_0.Name = "SelectionObjectClipper";
    l_Frame_0.BackgroundTransparency = 1;
    l_Frame_0.Visible = false;
    l_Frame_0.Parent = v127;
    v133 = Instance.new("ImageLabel");
    v133.Name = "Selector";
    v133.BackgroundTransparency = 1;
    v133.Size = UDim2.fromScale(1, 1);
    v133.Image = "rbxasset://textures/ui/Keyboard/key_selection_9slice.png";
    v133.ScaleType = Enum.ScaleType.Slice;
    v133.SliceCenter = Rect.new(12, 12, 52, 52);
    v133.Parent = l_Frame_0;
    v129 = Instance.new("ImageLabel");
    v129.BackgroundTransparency = 1;
    v129.Name = "Icon";
    v129.Size = UDim2.fromScale(1, 1);
    v129.Position = UDim2.fromScale(0.5, 0.5);
    v129.AnchorPoint = Vector2.new(0.5, 0.5);
    if l_l_script_0_Attribute_0 == true then
        v129.Size = UDim2.new(1, -v22 * 2, 1, -v22 * 2);
    else
        v129.Size = UDim2.fromScale(1, 1);
    end;
    v129.Parent = v127;
    l_Frame_0 = Instance.new("UICorner");
    l_Frame_0.Name = "Corner";
    if l_l_script_0_Attribute_0 == true then
        l_Frame_0.CornerRadius = v23 - UDim.new(0, v22);
    else
        l_Frame_0.CornerRadius = v23;
    end;
    l_Frame_0.Parent = v129;
    v130 = Instance.new("TextLabel");
    v130.BackgroundTransparency = 1;
    v130.Name = "ToolName";
    v130.Text = "";
    v130.TextColor3 = v27;
    v130.TextStrokeTransparency = v28;
    v130.TextStrokeColor3 = v29;
    v130.Font = Enum.Font.GothamSemibold; --[[ 2021 ]]
    v130.TextSize = v35;
    v130.Size = UDim2.new(1, -v22 * 2, 1, -v22 * 2);
    v130.Position = UDim2.fromScale(0.5, 0.5);
    v130.AnchorPoint = Vector2.new(0.5, 0.5);
    v130.TextWrapped = true;
    v130.TextTruncate = Enum.TextTruncate.AtEnd;
    v130.Parent = v127;
    v126.Frame.LayoutOrder = v126.Index;
    if v125 <= v75 then
        v134 = Instance.new("TextLabel");
        v134.Name = "ToolTip";
        v134.Text = "";
        v134.Size = UDim2.fromScale(1, 1);
        v134.TextColor3 = v27;
        v134.TextStrokeTransparency = v28;
        v134.TextStrokeColor3 = v29;
        v134.Font = Enum.Font.GothamSemibold; --[[ 2021 ]]
        v134.TextSize = v35;
        v134.ZIndex = 2;
        v134.TextWrapped = false;
        v134.TextYAlignment = Enum.TextYAlignment.Center;
        v134.BackgroundColor3 = v26;
        v134.BackgroundTransparency = v21;
        v134.AnchorPoint = Vector2.new(0.5, 1);
        v134.BorderSizePixel = 0;
        v134.Visible = false;
        v134.AutomaticSize = Enum.AutomaticSize.X;
        v134.Parent = v127;
        local l_UICorner_1 = Instance.new("UICorner");
        l_UICorner_1.Name = "Corner";
        l_UICorner_1.CornerRadius = v25;
        l_UICorner_1.Parent = v134;
        local l_UIPadding_0 = Instance.new("UIPadding");
        l_UIPadding_0.PaddingLeft = UDim.new(0, 4);
        l_UIPadding_0.PaddingRight = UDim.new(0, 4);
        l_UIPadding_0.PaddingTop = UDim.new(0, 4);
        l_UIPadding_0.PaddingBottom = UDim.new(0, 4);
        l_UIPadding_0.Parent = v134;
        v127.MouseEnter:Connect(function() --[[ Line: 748 ]]
            -- upvalues: v134 (ref)
            if v134.Text ~= "" then
                v134.Visible = true;
            end;
        end);
        v127.MouseLeave:Connect(function() --[[ Line: 753 ]]
            -- upvalues: v134 (ref)
            v134.Visible = false;
        end);
        v126.MoveToInventory = function(v199) --[[ Line: 757 ]] --[[ Name: MoveToInventory ]]
            -- upvalues: v126 (copy), v75 (ref), v122 (ref), v53 (ref), v58 (ref), l_Humanoid_0 (ref), v67 (ref), v63 (ref), v71 (ref), v50 (ref)
            if v126.Index <= v75 then
                local l_Tool_6 = v126.Tool;
                v199:Clear();
                local v201 = v122(v53);
                v201:Fill(l_Tool_6);
                if l_Tool_6 and l_Tool_6.Parent == v58 and l_Humanoid_0 then
                    l_Humanoid_0:UnequipTools();
                    if v67 then
                        v67:ToggleSelect();
                        v63[v67]:UpdateEquipView();
                        v67 = nil;
                    end;
                end;
                if v71 then
                    v201.Frame.Visible = false;
                    v201.Parent = v50;
                end;
            end;
        end;
        if v125 < 10 or v125 == v75 then
            local v202 = v125 < 10 and v125 or 0;
            v135 = Instance.new("TextLabel");
            v135.Name = "Number";
            v135.Text = tostring(v202);
            v135.TextColor3 = Color3.new(1, 1, 1);
            v135.TextStrokeTransparency = 1;
            v135.TextSize = 11;
            v135.Font = Enum.Font.GothamBlack; --[[ 2021 ]]
            v135.Size = UDim2.fromOffset(16, 16);
            v135.Position = UDim2.new(0, -2, 1, 2);
            v135.AnchorPoint = Vector2.new(0, 1);
            v135.BackgroundColor3 = Color3.fromRGB(10, 202, 255);
            v135.BackgroundTransparency = 0;
            v135.Visible = false;
            v135.ZIndex = 3;
            v135.Parent = v127;
            local l_UICorner_2 = Instance.new("UICorner");
            l_UICorner_2.CornerRadius = UDim.new(1, 0);
            l_UICorner_2.Parent = v135;
            v64[l_Value_1 + v202] = v126.Select;
        end;
    end;
    local l_Position_0 = v127.Position;
    local v205 = 0;
    local v206 = nil;
    do
        local l_l_Position_0_0, l_v205_0, l_v206_0 = l_Position_0, v205, v206;
        v127.DragBegin:Connect(function(v210) --[[ Line: 804 ]]
            -- upvalues: v65 (ref), v127 (ref), l_l_Position_0_0 (ref), v42 (ref), v129 (ref), v130 (ref), v135 (ref), l_v206_0 (ref), v53 (ref), v50 (ref), v128 (ref)
            v65[v127] = true;
            l_l_Position_0_0 = v210;
            v127.BorderSizePixel = 2;
            v42:lock();
            v127.ZIndex = 2;
            v129.ZIndex = 2;
            v130.ZIndex = 2;
            v127.Parent.ZIndex = 2;
            if v135 then
                v135.ZIndex = 2;
            end;
            l_v206_0 = v127.Parent;
            if l_v206_0 == v53 then
                local v211 = UDim2.new(0, v127.AbsolutePosition.X - v50.AbsolutePosition.X, 0, v127.AbsolutePosition.Y - v50.AbsolutePosition.Y);
                v127.Parent = v50;
                v127.Position = v211;
                v128 = Instance.new("Frame");
                v128.Name = "FakeSlot";
                v128.LayoutOrder = v127.LayoutOrder;
                v128.Size = v127.Size;
                v128.BackgroundTransparency = 1;
                v128.Parent = v53;
            end;
        end);
        v127.DragStopped:Connect(function(v212, v213) --[[ Line: 847 ]]
            -- upvalues: v128 (ref), v127 (ref), l_l_Position_0_0 (ref), l_v206_0 (ref), v42 (ref), v129 (ref), v130 (ref), v135 (ref), v65 (ref), v126 (copy), v50 (ref), v75 (ref), l_v205_0 (ref), v62 (ref), v49 (ref), v61 (ref), v58 (ref), l_Humanoid_0 (ref), v67 (ref), v63 (ref), v71 (ref)
            if v128 then
                v128:Destroy();
            end;
            local v214 = os.clock();
            v127.Position = l_l_Position_0_0;
            v127.Parent = l_v206_0;
            v127.BorderSizePixel = 0;
            v42:unlock();
            v127.ZIndex = 1;
            v129.ZIndex = 1;
            v130.ZIndex = 1;
            l_v206_0.ZIndex = 1;
            if v135 then
                v135.ZIndex = 1;
            end;
            v65[v127] = nil;
            if not v126.Tool then
                return;
            else
                local l_v50_0 = v50;
                local l_AbsolutePosition_1 = l_v50_0.AbsolutePosition;
                local l_AbsoluteSize_1 = l_v50_0.AbsoluteSize;
                local v218 = false;
                if l_AbsolutePosition_1.X < v212 then
                    v218 = false;
                    if v212 <= l_AbsolutePosition_1.X + l_AbsoluteSize_1.X then
                        v218 = false;
                        if l_AbsolutePosition_1.Y < v213 then
                            v218 = v213 <= l_AbsolutePosition_1.Y + l_AbsoluteSize_1.Y;
                        end;
                    end;
                end;
                if v218 then
                    if v126.Index <= v75 then
                        v126:MoveToInventory();
                    end;
                    if v126.Index > v75 and v214 - l_v205_0 < 0.5 then
                        if v62 then
                            v218 = v126.Tool;
                            v126:Clear();
                            v62:Fill(v218);
                            v126:Delete();
                        end;
                        v214 = 0;
                    end;
                else
                    l_v50_0 = v49;
                    l_AbsolutePosition_1 = l_v50_0.AbsolutePosition;
                    l_AbsoluteSize_1 = l_v50_0.AbsoluteSize;
                    v218 = false;
                    if l_AbsolutePosition_1.X < v212 then
                        v218 = false;
                        if v212 <= l_AbsolutePosition_1.X + l_AbsoluteSize_1.X then
                            v218 = false;
                            if l_AbsolutePosition_1.Y < v213 then
                                v218 = v213 <= l_AbsolutePosition_1.Y + l_AbsoluteSize_1.Y;
                            end;
                        end;
                    end;
                    if v218 then
                        v218 = {
                            1e999, 
                            nil
                        };
                        for v219 = 1, v75 do
                            local v220 = v61[v219];
                            local l_Frame_1 = v220.Frame;
                            local v222 = Vector2.new(v212, v213);
                            local l_Magnitude_0 = (l_Frame_1.AbsolutePosition + l_Frame_1.AbsoluteSize / 2 - v222).Magnitude;
                            if l_Magnitude_0 < v218[1] then
                                v218 = {
                                    l_Magnitude_0, 
                                    v220
                                };
                            end;
                        end;
                        l_v50_0 = v218[2];
                        if l_v50_0 ~= v126 then
                            v126:Swap(l_v50_0);
                            if v126.Index > v75 then
                                l_AbsolutePosition_1 = v126.Tool;
                                if not l_AbsolutePosition_1 then
                                    v126:Delete();
                                else
                                    if l_AbsolutePosition_1 and l_AbsolutePosition_1.Parent == v58 and l_Humanoid_0 then
                                        l_Humanoid_0:UnequipTools();
                                        if v67 then
                                            v67:ToggleSelect();
                                            v63[v67]:UpdateEquipView();
                                            v67 = nil;
                                        end;
                                    end;
                                    if v71 then
                                        v126.Frame.Visible = false;
                                        v126.Frame.Parent = v50;
                                    end;
                                end;
                            end;
                        end;
                    elseif v126.Index <= v75 then
                        v126:MoveToInventory();
                    end;
                end;
                l_v205_0 = v214;
                return;
            end;
        end);
    end;
    v127.Parent = v123;
    v61[v125] = v126;
    if v75 < v125 then
        l_Position_0 = math.floor(v52.AbsoluteSize.X / (v38 + 10));
        v206 = math.ceil((#v53:GetChildren() - 1) / l_Position_0) * (v38 + 10) + 10;
        v52.CanvasSize = UDim2.fromOffset(0, v206);
        if v50.Visible and not v71 then
            l_Position_0 = v52.CanvasSize.Y.Offset - v52.AbsoluteSize.Y;
            v52.CanvasPosition = Vector2.new(0, (math.max(0, l_Position_0)));
        end;
    end;
    return v126;
end;
local function v233(v224) --[[ Line: 957 ]] --[[ Name: OnChildAdded ]]
    -- upvalues: v58 (ref), l_Humanoid_0 (ref), v67 (ref), v63 (copy), v68 (ref), l_LocalPlayer_0 (ref), v62 (ref), v122 (copy), v53 (ref), v61 (copy), l_Backpack_0 (ref), v92 (copy), v75 (copy), v50 (ref), v10 (copy)
    if not v224:IsA("Tool") and not v224:IsA("HopperBin") then
        if v224:IsA("Humanoid") and v224.Parent == v58 then
            l_Humanoid_0 = v224;
        end;
        return;
    else
        if v224.Parent == v58 then

        end;
        if v67 and v224.Parent == v58 then
            v67:ToggleSelect();
            v63[v67]:UpdateEquipView();
            v67 = nil;
        end;
        if not v68 and v224.Parent == v58 and not v63[v224] then
            local l_StarterGear_0 = l_LocalPlayer_0:FindFirstChild("StarterGear");
            if l_StarterGear_0 and l_StarterGear_0:FindFirstChild(v224.Name) then
                v68 = true;
                local v226 = v62 or v122(v53);
                for v227 = v226.Index, 1, -1 do
                    local v228 = v61[v227];
                    local v229 = v227 - 1;
                    if v229 > 0 then
                        v61[v229]:Swap(v228);
                    else
                        v228:Fill(v224);
                    end;
                end;
                for _, v231 in pairs(v58:GetChildren()) do
                    if v231:IsA("Tool") and v231 ~= v224 then
                        v231.Parent = l_Backpack_0;
                    end;
                end;
                v92();
                return;
            end;
        end;
        local v232 = v63[v224];
        if v232 then
            v232:UpdateEquipView();
        else
            v232 = v62 or v122(v53);
            v232:Fill(v224);
            if v232.Index <= v75 and not v50.Visible then
                v92();
            end;
            if v224:IsA("HopperBin") and v224.Active then
                if l_Humanoid_0 then
                    l_Humanoid_0:UnequipTools();
                    if v67 then
                        v67:ToggleSelect();
                        v63[v67]:UpdateEquipView();
                        v67 = nil;
                    end;
                end;
                v67 = v224;
            end;
        end;
        v10.BackpackItemAdded:Fire();
        return;
    end;
end;
local function v241(v234) --[[ Line: 1024 ]] --[[ Name: OnChildRemoved ]]
    -- upvalues: v58 (ref), l_Backpack_0 (ref), v63 (copy), v75 (copy), v50 (ref), v92 (copy), v67 (ref), v10 (copy), v61 (copy)
    local v235 = false;
    if not v234:IsA("Tool") and not v234:IsA("HopperBin") then
        return;
    else
        local l_Parent_0 = v234.Parent;
        if l_Parent_0 == v58 or l_Parent_0 == l_Backpack_0 then
            return;
        else
            local v237 = v63[v234];
            if v237 then
                v237:Clear();
                if v237.Index > v75 then
                    v237:Delete();
                elseif not v50.Visible then
                    v92();
                end;
            end;
            if v234 == v67 then
                v67 = nil;
            end;
            v10.BackpackItemRemoved:Fire();
            local v238;
            for v239 = v75 + 1, #v61 do
                local v240 = v61[v239];
                if v240 and v240.Tool then
                    v238 = false;
                    v235 = true;
                end;
                if v235 then
                    break;
                end;
            end;
            if not v235 then
                v238 = true;
            end;
            v235 = false;
            if v238 then
                v10.BackpackEmpty:Fire();
            end;
            return;
        end;
    end;
end;
local function v251(v242) --[[ Line: 1058 ]] --[[ Name: OnCharacterAdded ]]
    -- upvalues: v61 (copy), v75 (copy), v67 (ref), v72 (ref), v58 (ref), v241 (copy), v233 (copy), l_Backpack_0 (ref), l_LocalPlayer_0 (ref), v92 (copy)
    for v243 = #v61, 1, -1 do
        local v244 = v61[v243];
        if v244.Tool then
            v244:Clear();
        end;
        if v75 < v243 then
            v244:Delete();
        end;
    end;
    v67 = nil;
    for _, v246 in pairs(v72) do
        v246:Disconnect();
    end;
    v72 = {};
    v58 = v242;
    table.insert(v72, v242.ChildRemoved:Connect(v241));
    table.insert(v72, v242.ChildAdded:Connect(v233));
    for _, v248 in pairs(v242:GetChildren()) do
        v233(v248);
    end;
    l_Backpack_0 = l_LocalPlayer_0:WaitForChild("Backpack");
    table.insert(v72, l_Backpack_0.ChildRemoved:Connect(v241));
    table.insert(v72, l_Backpack_0.ChildAdded:Connect(v233));
    for _, v250 in pairs(l_Backpack_0:GetChildren()) do
        v233(v250);
    end;
    v92();
end;
local function v257(v252, v253) --[[ Line: 1097 ]] --[[ Name: OnInputBegan ]]
    -- upvalues: l_TextChatService_0 (copy), v70 (ref), v69 (ref), l_Value_0 (copy), v64 (copy), v50 (ref), v42 (copy)
    if v252.UserInputType == Enum.UserInputType.Keyboard and not v70 and l_UserInputService_99:GetFocusedTextBox() == nil --[[ 2021 ]] and (v69 or v252.KeyCode.Value == l_Value_0) then
        local v255 = v64[v252.KeyCode.Value];
        if v255 then
            v255(v253);
        end;
    end;
    local l_UserInputType_0 = v252.UserInputType;
    if not v253 and (l_UserInputType_0 == Enum.UserInputType.MouseButton1 or l_UserInputType_0 == Enum.UserInputType.Touch) and v50.Visible then
        v42:deselect();
    end;
end;
local function v266() --[[ Line: 1123 ]] --[[ Name: OnUISChanged ]]
    -- upvalues: l_UserInputService_0 (copy), v75 (copy), v61 (copy), v39 (copy), v40 (copy)
    if l_UserInputService_0:GetLastInputType() == Enum.UserInputType.Touch then
        for v258 = 1, v75 do
            v61[v258]:TurnNumber(false);
        end;
        return;
    elseif l_UserInputService_0:GetLastInputType() == Enum.UserInputType.Keyboard then
        for v259 = 1, v75 do
            v61[v259]:TurnNumber(true);
        end;
        return;
    else
        for _, v261 in pairs(v39) do
            if l_UserInputService_0:GetLastInputType() == v261 then
                for v262 = 1, v75 do
                    v61[v262]:TurnNumber(true);
                end;
                return;
            end;
        end;
        for _, v264 in pairs(v40) do
            if l_UserInputService_0:GetLastInputType() == v264 then
                for v265 = 1, v75 do
                    v61[v265]:TurnNumber(false);
                end;
                return;
            end;
        end;
        return;
    end;
end;
local v267 = nil;
local v268 = nil;
local function v269() --[[ Line: 1164 ]]

end;
unbindAllGamepadEquipActions = function() --[[ Line: 1167 ]] --[[ Name: unbindAllGamepadEquipActions ]]
    -- upvalues: l_ContextActionService_0 (copy)
    l_ContextActionService_0:UnbindAction("BackpackHasGamepadFocus");
    l_ContextActionService_0:UnbindAction("BackpackCloseInventory");
end;
v57 = function(_, v271, v272) --[[ Line: 1243 ]]
    -- upvalues: v267 (ref), v268 (ref), l_Humanoid_0 (ref), v67 (ref), v63 (copy), v75 (copy), v61 (copy), v77 (ref)
    if v271 ~= Enum.UserInputState.Begin then
        return;
    elseif v267 and (v267.KeyCode == Enum.KeyCode.ButtonR1 and v272.KeyCode == Enum.KeyCode.ButtonL1 or v267.KeyCode == Enum.KeyCode.ButtonL1 and v272.KeyCode == Enum.KeyCode.ButtonR1) and os.clock() - v268 <= 0.06 then
        if l_Humanoid_0 then
            l_Humanoid_0:UnequipTools();
            if v67 then
                v67:ToggleSelect();
                v63[v67]:UpdateEquipView();
                v67 = nil;
            end;
        end;
        v267 = v272;
        v268 = os.clock();
        return;
    else
        v267 = v272;
        v268 = os.clock();
        task.delay(0.06, function() --[[ Line: 1271 ]]
            -- upvalues: v267 (ref), v272 (copy), v75 (ref), v61 (ref), l_Humanoid_0 (ref), v67 (ref), v63 (ref), v77 (ref)
            if v267 ~= v272 then
                return;
            else
                local v273 = 0;
                v273 = v272.KeyCode == Enum.KeyCode.ButtonL1 and -1 or 1;
                for v274 = 1, v75 do
                    if v61[v274]:IsEquipped() then
                        local v275 = v273 + v274;
                        local v276 = false;
                        if v75 < v275 then
                            v275 = 1;
                            v276 = true;
                        elseif v275 < 1 then
                            v275 = v75;
                            v276 = true;
                        end;
                        local l_v275_0 = v275;
                        while true do
                            if not v61[v275].Tool then
                                v275 = v275 + v273;
                                if v275 == l_v275_0 then
                                    return;
                                elseif v75 < v275 then
                                    v275 = 1;
                                    v276 = true;
                                elseif v275 < 1 then
                                    v275 = v75;
                                    v276 = true;
                                end;
                            elseif v276 then
                                if l_Humanoid_0 then
                                    l_Humanoid_0:UnequipTools();
                                    if v67 then
                                        v67:ToggleSelect();
                                        v63[v67]:UpdateEquipView();
                                        v67 = nil;
                                    end;
                                end;
                                v77 = nil;
                                return;
                            else
                                v61[v275]:Select();
                                return;
                            end;
                        end;
                    end;
                end;
                if v77 and v77.Tool then
                    v77:Select();
                    return;
                else
                    local v278 = v273 == -1 and v75 or 1;
                    local v279 = v273 == -1 and 1 or v75;
                    for v280 = v278, v279, v273 do
                        if v61[v280].Tool then
                            v61[v280]:Select();
                            return;
                        end;
                    end;
                    return;
                end;
            end;
        end);
        return;
    end;
end;
getGamepadSwapSlot = function() --[[ Line: 1338 ]] --[[ Name: getGamepadSwapSlot ]]
    -- upvalues: v61 (copy)
    for v281 = 1, #v61 do
        if v61[v281].Frame.BorderSizePixel > 0 then
            return v61[v281];
        end;
    end;
end;
changeSlot = function(v282) --[[ Line: 1348 ]] --[[ Name: changeSlot ]]
    -- upvalues: l_VRService_0 (copy), v50 (ref), l_GuiService_0 (copy), v51 (ref), v75 (copy)
    local v283 = not l_VRService_0.VREnabled or v50.Visible;
    if v282.Frame == l_GuiService_0.SelectedObject and v283 then
        local v284 = getGamepadSwapSlot();
        if v284 then
            v284.Frame.BorderSizePixel = 0;
            if v284 ~= v282 then
                v282:Swap(v284);
                v51.SelectionImageObject.Visible = false;
                if v282.Index > v75 and not v282.Tool then
                    if l_GuiService_0.SelectedObject == v282.Frame then
                        l_GuiService_0.SelectedObject = v284.Frame;
                    end;
                    v282:Delete();
                end;
                if v284.Index > v75 and not v284.Tool then
                    if l_GuiService_0.SelectedObject == v284.Frame then
                        l_GuiService_0.SelectedObject = v282.Frame;
                    end;
                    v284:Delete();
                    return;
                end;
            end;
        else
            local l_Size_0 = v282.Frame.Size;
            local l_Position_1 = v282.Frame.Position;
            v282.Frame:TweenSizeAndPosition(l_Size_0 + UDim2.fromOffset(10, 10), l_Position_1 - UDim2.fromOffset(5, 5), Enum.EasingDirection.Out, Enum.EasingStyle.Quad, 0.1, true, function() --[[ Line: 1384 ]]
                -- upvalues: v282 (copy), l_Size_0 (copy), l_Position_1 (copy)
                v282.Frame:TweenSizeAndPosition(l_Size_0, l_Position_1, Enum.EasingDirection.In, Enum.EasingStyle.Quad, 0.1, true);
            end);
            v282.Frame.BorderSizePixel = 3;
            v51.SelectionImageObject.Visible = true;
            return;
        end;
    else
        v282:Select();
        v51.SelectionImageObject.Visible = false;
    end;
end;
vrMoveSlotToInventory = function() --[[ Line: 1404 ]] --[[ Name: vrMoveSlotToInventory ]]
    -- upvalues: l_VRService_0 (copy), v51 (ref)
    if not l_VRService_0.VREnabled then
        return;
    else
        local v287 = getGamepadSwapSlot();
        if v287 and v287.Tool then
            v287.Frame.BorderSizePixel = 0;
            v287:MoveToInventory();
            v51.SelectionImageObject.Visible = false;
        end;
        return;
    end;
end;
enableGamepadInventoryControl = function() --[[ Line: 1417 ]] --[[ Name: enableGamepadInventoryControl ]]
    -- upvalues: v50 (ref), v42 (copy), l_ContextActionService_0 (copy), v269 (copy), l_GuiService_0 (copy), v49 (ref)
    local function v289() --[[ Line: 1418 ]]
        -- upvalues: v50 (ref), v42 (ref)
        if getGamepadSwapSlot() then
            local v288 = getGamepadSwapSlot();
            if v288 then
                v288.Frame.BorderSizePixel = 0;
                return;
            end;
        elseif v50.Visible then
            v42:deselect();
        end;
    end;
    l_ContextActionService_0:BindAction("BackpackHasGamepadFocus", v269, false, Enum.UserInputType.Gamepad1);
    l_ContextActionService_0:BindAction("BackpackCloseInventory", v289, false, Enum.KeyCode.ButtonB, Enum.KeyCode.ButtonStart);
    if not false then
        l_GuiService_0.SelectedObject = v49:FindFirstChild("1");
    end;
end;
disableGamepadInventoryControl = function() --[[ Line: 1451 ]] --[[ Name: disableGamepadInventoryControl ]]
    -- upvalues: v75 (copy), v61 (copy), l_GuiService_0 (copy), v48 (ref)
    unbindAllGamepadEquipActions();
    for v290 = 1, v75 do
        local v291 = v61[v290];
        if v291 and v291.Frame then
            v291.Frame.BorderSizePixel = 0;
        end;
    end;
    if l_GuiService_0.SelectedObject and l_GuiService_0.SelectedObject:IsDescendantOf(v48) then
        l_GuiService_0.SelectedObject = nil;
    end;
end;
local function _() --[[ Line: 1466 ]] --[[ Name: bindBackpackHotbarAction ]]
    -- upvalues: v69 (ref), v45 (ref), l_ContextActionService_0 (copy), v57 (ref)
    if v69 and not v45 then
        v45 = true;
        l_ContextActionService_0:BindAction("BackpackHotbarEquip", v57, false, Enum.KeyCode.ButtonL1, Enum.KeyCode.ButtonR1);
    end;
end;
local function _() --[[ Line: 1479 ]] --[[ Name: unbindBackpackHotbarAction ]]
    -- upvalues: v45 (ref), l_ContextActionService_0 (copy)
    disableGamepadInventoryControl();
    v45 = false;
    l_ContextActionService_0:UnbindAction("BackpackHotbarEquip");
end;
gamepadDisconnected = function() --[[ Line: 1485 ]] --[[ Name: gamepadDisconnected ]]
    -- upvalues: v73 (ref)
    v73 = false;
    disableGamepadInventoryControl();
end;
gamepadConnected = function() --[[ Line: 1490 ]] --[[ Name: gamepadConnected ]]
    -- upvalues: v73 (ref), l_GuiService_0 (copy), v48 (ref), v66 (ref), v69 (ref), v45 (ref), l_ContextActionService_0 (copy), v57 (ref), v50 (ref)
    v73 = true;
    l_GuiService_0:AddSelectionParent("BackpackSelection", v48);
    if v66 >= 1 and v69 and not v45 then
        v45 = true;
        l_ContextActionService_0:BindAction("BackpackHotbarEquip", v57, false, Enum.KeyCode.ButtonL1, Enum.KeyCode.ButtonR1);
    end;
    if v50.Visible then
        enableGamepadInventoryControl();
    end;
end;
local function v297(v294) --[[ Line: 1503 ]] --[[ Name: OnIconChanged ]]
    -- upvalues: l_StarterGui_0 (copy), v69 (ref), v48 (ref), v66 (ref), v45 (ref), l_ContextActionService_0 (copy), v57 (ref)
    local l_status_0, _ = pcall(function() --[[ Line: 1505 ]]
        -- upvalues: v294 (copy), l_StarterGui_0 (ref)
        return v294 and l_StarterGui_0:GetCore("TopbarEnabled");
    end);
    if not l_status_0 then
        return;
    else
        v69 = v294;
        v48.Visible = v294;
        if v294 then
            if v66 >= 1 and v69 and not v45 then
                v45 = true;
                l_ContextActionService_0:BindAction("BackpackHotbarEquip", v57, false, Enum.KeyCode.ButtonL1, Enum.KeyCode.ButtonR1);
                return;
            end;
        else
            disableGamepadInventoryControl();
            v45 = false;
            l_ContextActionService_0:UnbindAction("BackpackHotbarEquip");
        end;
        return;
    end;
end;
local function v303(v298, v299) --[[ Line: 1534 ]] --[[ Name: MakeVRRoundButton ]]
    local l_ImageButton_0 = Instance.new("ImageButton");
    l_ImageButton_0.BackgroundTransparency = 1;
    l_ImageButton_0.Name = v298;
    l_ImageButton_0.Size = UDim2.fromOffset(40, 40);
    l_ImageButton_0.Image = "rbxasset://textures/ui/Keyboard/close_button_background.png";
    local l_ImageLabel_0 = Instance.new("ImageLabel");
    l_ImageLabel_0.Name = "Icon";
    l_ImageLabel_0.BackgroundTransparency = 1;
    l_ImageLabel_0.Size = UDim2.fromScale(0.5, 0.5);
    l_ImageLabel_0.Position = UDim2.fromScale(0.25, 0.25);
    l_ImageLabel_0.Image = v299;
    l_ImageLabel_0.Parent = l_ImageButton_0;
    local l_ImageLabel_1 = Instance.new("ImageLabel");
    l_ImageLabel_1.BackgroundTransparency = 1;
    l_ImageLabel_1.Name = "Selection";
    l_ImageLabel_1.Size = UDim2.fromScale(0.9, 0.9);
    l_ImageLabel_1.Position = UDim2.fromScale(0.05, 0.05);
    l_ImageLabel_1.Image = "rbxasset://textures/ui/Keyboard/close_button_selection.png";
    l_ImageButton_0.SelectionImageObject = l_ImageLabel_1;
    return l_ImageButton_0, l_ImageLabel_0, l_ImageLabel_1;
end;
v48 = Instance.new("Frame");
v48.BackgroundTransparency = 1;
v48.Name = "Backpack";
v48.Size = UDim2.fromScale(1, 1);
v48.Visible = false;
v48.Parent = l_ScreenGui_0;
v49 = Instance.new("Frame");
v49.BackgroundTransparency = 1;
v49.Name = "Hotbar";
v49.Size = UDim2.fromScale(1, 1);
v49.Parent = v48;
for v304 = 1, v75 do
    local v305 = v122(v49, v304);
    v305.Frame.Visible = false;
    if not v62 then
        v62 = v305;
    end;
end;
local l_ImageLabel_2 = Instance.new("ImageLabel");
l_ImageLabel_2.BackgroundTransparency = 1;
l_ImageLabel_2.Name = "LeftBumper";
l_ImageLabel_2.Size = UDim2.fromOffset(40, 40);
l_ImageLabel_2.Position = UDim2.new(0, -l_ImageLabel_2.Size.X.Offset, 0.5, -l_ImageLabel_2.Size.Y.Offset / 2);
local l_ImageLabel_3 = Instance.new("ImageLabel");
l_ImageLabel_3.BackgroundTransparency = 1;
l_ImageLabel_3.Name = "RightBumper";
l_ImageLabel_3.Size = UDim2.fromOffset(40, 40);
l_ImageLabel_3.Position = UDim2.new(1, 0, 0.5, -l_ImageLabel_3.Size.Y.Offset / 2);
v50 = Instance.new("Frame");
v50.Name = "Inventory";
v50.Size = UDim2.fromScale(1, 1);
v50.BackgroundTransparency = v16;
v50.BackgroundColor3 = v18;
v50.Active = true;
v50.Visible = false;
v50.Parent = v48;
local l_UICorner_3 = Instance.new("UICorner");
l_UICorner_3.Name = "Corner";
l_UICorner_3.CornerRadius = v17;
l_UICorner_3.Parent = v50;
v51 = Instance.new("TextButton");
v51.Name = "VRInventorySelector";
v51.Position = UDim2.new(0, 0, 0, 0);
v51.Size = UDim2.fromScale(1, 1);
v51.BackgroundTransparency = 1;
v51.Text = "";
v51.Parent = v50;
local l_ImageLabel_4 = Instance.new("ImageLabel");
l_ImageLabel_4.BackgroundTransparency = 1;
l_ImageLabel_4.Name = "Selector";
l_ImageLabel_4.Size = UDim2.fromScale(1, 1);
l_ImageLabel_4.Image = "rbxasset://textures/ui/Keyboard/key_selection_9slice.png";
l_ImageLabel_4.ScaleType = Enum.ScaleType.Slice;
l_ImageLabel_4.SliceCenter = Rect.new(12, 12, 52, 52);
l_ImageLabel_4.Visible = false;
v51.SelectionImageObject = l_ImageLabel_4;
v51.MouseButton1Click:Connect(function() --[[ Line: 1631 ]]
    vrMoveSlotToInventory();
end);
v52 = Instance.new("ScrollingFrame");
v52.BackgroundTransparency = 1;
v52.Name = "ScrollingFrame";
v52.Size = UDim2.fromScale(1, 1);
v52.Selectable = false;
v52.ScrollingDirection = Enum.ScrollingDirection.Y;
v52.BorderSizePixel = 0;
v52.ScrollBarThickness = 8;
v52.ScrollBarImageColor3 = Color3.new(1, 1, 1);
v52.VerticalScrollBarInset = Enum.ScrollBarInset.ScrollBar;
v52.CanvasSize = UDim2.new(0, 0, 0, 0);
v52.Parent = v50;
v53 = Instance.new("Frame");
v53.BackgroundTransparency = 1;
v53.Name = "UIGridFrame";
v53.Selectable = false;
v53.Size = UDim2.new(1, -20, 1, -8);
v53.Position = UDim2.fromOffset(10, 4);
v53.Parent = v52;
v54 = Instance.new("UIGridLayout");
v54.SortOrder = Enum.SortOrder.LayoutOrder;
v54.CellSize = UDim2.fromOffset(v38, v38);
v54.CellPadding = UDim2.fromOffset(10, 10);
v54.Parent = v53;
v55 = v303("ScrollUpButton", "rbxasset://textures/ui/Backpack/ScrollUpArrow.png");
v55.Size = UDim2.fromOffset(34, 34);
v55.Position = UDim2.new(0.5, -v55.Size.X.Offset / 2, 0, 43);
v55.Icon.Position = v55.Icon.Position - UDim2.fromOffset(0, 2);
v55.MouseButton1Click:Connect(function() --[[ Line: 1668 ]]
    -- upvalues: v52 (ref), v38 (ref)
    v52.CanvasPosition = Vector2.new(v52.CanvasPosition.X, (math.min(v52.CanvasSize.Y.Offset - v52.AbsoluteWindowSize.Y, (math.max(0, v52.CanvasPosition.Y - (v38 + 10))))));
end);
v56 = v303("ScrollDownButton", "rbxasset://textures/ui/Backpack/ScrollUpArrow.png");
v56.Rotation = 180;
v56.Icon.Position = v56.Icon.Position - UDim2.fromOffset(0, 2);
v56.Size = UDim2.fromOffset(34, 34);
v56.Position = UDim2.new(0.5, -v56.Size.X.Offset / 2, 1, -v56.Size.Y.Offset - 3);
v56.MouseButton1Click:Connect(function() --[[ Line: 1685 ]]
    -- upvalues: v52 (ref), v38 (ref)
    v52.CanvasPosition = Vector2.new(v52.CanvasPosition.X, (math.min(v52.CanvasSize.Y.Offset - v52.AbsoluteWindowSize.Y, (math.max(0, v52.CanvasPosition.Y + (v38 + 10))))));
end);
v52.Changed:Connect(function(v310) --[[ Line: 1696 ]]
    -- upvalues: v52 (ref), v55 (ref), v56 (ref)
    if v310 == "AbsoluteWindowSize" or v310 == "CanvasPosition" or v310 == "CanvasSize" then
        local v311 = v52.CanvasPosition.Y ~= 0;
        local v312 = v52.CanvasPosition.Y < v52.CanvasSize.Y.Offset - v52.AbsoluteWindowSize.Y;
        v55.Visible = v311;
        v56.Visible = v312;
    end;
end);
v101();
local l_Frame_2 = Instance.new("Frame");
l_Frame_2.Name = "GamepadHintsFrame";
l_Frame_2.Size = UDim2.fromOffset(v49.Size.X.Offset, v44 and 95 or 60);
l_Frame_2.BackgroundTransparency = v16;
l_Frame_2.BackgroundColor3 = v18;
l_Frame_2.Visible = false;
l_Frame_2.Parent = v48;
local l_UIListLayout_0 = Instance.new("UIListLayout");
l_UIListLayout_0.Name = "Layout";
l_UIListLayout_0.Padding = UDim.new(0, 25);
l_UIListLayout_0.FillDirection = Enum.FillDirection.Horizontal;
l_UIListLayout_0.HorizontalAlignment = Enum.HorizontalAlignment.Center;
l_UIListLayout_0.SortOrder = Enum.SortOrder.LayoutOrder;
l_UIListLayout_0.Parent = l_Frame_2;
local l_UICorner_4 = Instance.new("UICorner");
l_UICorner_4.Name = "Corner";
l_UICorner_4.CornerRadius = v17;
l_UICorner_4.Parent = l_Frame_2;
local function v323(v316, v317) --[[ Line: 1732 ]] --[[ Name: addGamepadHint ]]
    -- upvalues: l_Frame_2 (copy), v44 (copy), v34 (copy)
    local l_Frame_3 = Instance.new("Frame");
    l_Frame_3.Name = "HintFrame";
    l_Frame_3.AutomaticSize = Enum.AutomaticSize.XY;
    l_Frame_3.BackgroundTransparency = 1;
    l_Frame_3.Parent = l_Frame_2;
    local l_UIListLayout_1 = Instance.new("UIListLayout");
    l_UIListLayout_1.Name = "Layout";
    l_UIListLayout_1.Padding = v44 and UDim.new(0, 20) or UDim.new(0, 12);
    l_UIListLayout_1.FillDirection = Enum.FillDirection.Horizontal;
    l_UIListLayout_1.SortOrder = Enum.SortOrder.LayoutOrder;
    l_UIListLayout_1.VerticalAlignment = Enum.VerticalAlignment.Center;
    l_UIListLayout_1.Parent = l_Frame_3;
    local l_ImageLabel_5 = Instance.new("ImageLabel");
    l_ImageLabel_5.Name = "HintImage";
    l_ImageLabel_5.Size = v44 and UDim2.fromOffset(60, 60) or UDim2.fromOffset(30, 30);
    l_ImageLabel_5.BackgroundTransparency = 1;
    l_ImageLabel_5.Image = v316;
    l_ImageLabel_5.Parent = l_Frame_3;
    local l_TextLabel_0 = Instance.new("TextLabel");
    l_TextLabel_0.Name = "HintText";
    l_TextLabel_0.AutomaticSize = Enum.AutomaticSize.XY;
    l_TextLabel_0.Font = Enum.Font.GothamSemibold; --[[ 2021 ]]
    l_TextLabel_0.TextSize = v44 and 32 or 19;
    l_TextLabel_0.BackgroundTransparency = 1;
    l_TextLabel_0.Text = v317;
    l_TextLabel_0.TextColor3 = Color3.new(1, 1, 1);
    l_TextLabel_0.TextXAlignment = Enum.TextXAlignment.Left;
    l_TextLabel_0.TextYAlignment = Enum.TextYAlignment.Center;
    l_TextLabel_0.TextWrapped = true;
    l_TextLabel_0.Parent = l_Frame_3;
    local l_UITextSizeConstraint_0 = Instance.new("UITextSizeConstraint");
    l_UITextSizeConstraint_0.MaxTextSize = l_TextLabel_0.TextSize;
    l_UITextSizeConstraint_0.Parent = l_TextLabel_0;
end;
v323(l_UserInputService_0:GetImageForKeyCode(Enum.KeyCode.ButtonX), "Remove From Hotbar");
v323(l_UserInputService_0:GetImageForKeyCode(Enum.KeyCode.ButtonA), "Select/Swap");
v323(l_UserInputService_0:GetImageForKeyCode(Enum.KeyCode.ButtonB), "Close Backpack");
local function v332() --[[ Line: 1776 ]] --[[ Name: resizeGamepadHintsFrame ]]
    -- upvalues: l_Frame_2 (copy), v49 (ref), v44 (copy), v50 (ref)
    l_Frame_2.Size = UDim2.new(v49.Size.X.Scale, v49.Size.X.Offset, 0, v44 and 95 or 60);
    l_Frame_2.Position = UDim2.new(v49.Position.X.Scale, v49.Position.X.Offset, v50.Position.Y.Scale, v50.Position.Y.Offset - l_Frame_2.Size.Y.Offset - 10);
    local v324 = 0;
    local l_l_Frame_2_Children_0 = l_Frame_2:GetChildren();
    local v326 = {};
    for _, v328 in pairs(l_l_Frame_2_Children_0) do
        if v328:IsA("GuiObject") then
            table.insert(v326, v328);
        end;
    end;
    for v329 = 1, #v326 do
        if v326[v329]:IsA("GuiObject") then
            v326[v329].Size = UDim2.new(1, 0, 1, -5);
            v326[v329].Position = UDim2.new(0, 0, 0, 0);
            v324 = v324 + (v326[v329].HintText.Position.X.Offset + v326[v329].HintText.TextBounds.X);
        end;
    end;
    local v330 = (l_Frame_2.AbsoluteSize.X - v324) / (#v326 - 1);
    for v331 = 1, #v326 do
        v326[v331].Position = v331 == 1 and UDim2.new(0, 0, 0, 0) or UDim2.new(0, v326[v331 - 1].Position.X.Offset + v326[v331 - 1].Size.X.Offset + v330, 0, 0);
        v326[v331].Size = UDim2.new(0, v326[v331].HintText.Position.X.Offset + v326[v331].HintText.TextBounds.X, 1, -5);
    end;
end;
local l_Frame_4 = Instance.new("Frame");
l_Frame_4.Name = "Search";
l_Frame_4.BackgroundColor3 = v30;
l_Frame_4.BackgroundTransparency = v31;
l_Frame_4.Size = UDim2.new(0, 190, 0, 30);
l_Frame_4.Position = UDim2.new(1, -l_Frame_4.Size.X.Offset - 5, 0, 5);
l_Frame_4.Parent = v50;
local l_UICorner_5 = Instance.new("UICorner");
l_UICorner_5.Name = "Corner";
l_UICorner_5.CornerRadius = v33;
l_UICorner_5.Parent = l_Frame_4;
local l_UIStroke_1 = Instance.new("UIStroke");
l_UIStroke_1.Name = "Border";
l_UIStroke_1.Color = v32;
l_UIStroke_1.Thickness = 1;
l_UIStroke_1.Transparency = 0;
l_UIStroke_1.Parent = l_Frame_4;
local l_TextBox_0 = Instance.new("TextBox");
l_TextBox_0.BackgroundTransparency = 1;
l_TextBox_0.Name = "TextBox";
l_TextBox_0.Text = "";
l_TextBox_0.TextColor3 = Color3.fromRGB(30, 30, 30);
l_TextBox_0.TextStrokeTransparency = v28;
l_TextBox_0.TextStrokeColor3 = v29;
l_TextBox_0.Font = Enum.Font.GothamSemibold; --[[ 2021 ]]
l_TextBox_0.PlaceholderText = "Search";
l_TextBox_0.PlaceholderColor3 = Color3.fromRGB(120, 120, 120);
l_TextBox_0.TextColor3 = Color3.fromRGB(30, 30, 30);
l_TextBox_0.TextTransparency = 0;
l_TextBox_0.TextStrokeColor3 = v29;
l_TextBox_0.ClearTextOnFocus = false;
l_TextBox_0.TextTruncate = Enum.TextTruncate.AtEnd;
l_TextBox_0.TextSize = v35;
l_TextBox_0.TextXAlignment = Enum.TextXAlignment.Left;
l_TextBox_0.TextYAlignment = Enum.TextYAlignment.Center;
l_TextBox_0.Size = UDim2.new(0, 154, 0, 14);
l_TextBox_0.AnchorPoint = Vector2.new(0, 0.5);
l_TextBox_0.Position = UDim2.new(0, 8, 0.5, 0);
l_TextBox_0.ZIndex = 2;
l_TextBox_0.Parent = l_Frame_4;
local l_TextButton_0 = Instance.new("TextButton");
l_TextButton_0.Name = "X";
l_TextButton_0.Text = "";
l_TextButton_0.Size = UDim2.fromOffset(30, 30);
l_TextButton_0.Position = UDim2.new(1, -l_TextButton_0.Size.X.Offset, 0.5, -l_TextButton_0.Size.Y.Offset / 2);
l_TextButton_0.ZIndex = 4;
l_TextButton_0.Visible = false;
l_TextButton_0.BackgroundTransparency = 1;
l_TextButton_0.Parent = l_Frame_4;
local l_ImageButton_1 = Instance.new("ImageButton");
l_ImageButton_1.Name = "X";
l_ImageButton_1.Image = "rbxasset://textures/ui/InspectMenu/x.png";
l_ImageButton_1.BackgroundTransparency = 1;
l_ImageButton_1.Size = UDim2.new(0, l_Frame_4.Size.Y.Offset - 20, 0, l_Frame_4.Size.Y.Offset - 20);
l_ImageButton_1.AnchorPoint = Vector2.new(0.5, 0.5);
l_ImageButton_1.Position = UDim2.fromScale(0.5, 0.5);
l_ImageButton_1.ZIndex = 1;
l_ImageButton_1.BorderSizePixel = 0;
l_ImageButton_1.ImageColor3 = Color3.new(0, 0, 0);
l_ImageButton_1.Parent = l_TextButton_0;
local function v352() --[[ Line: 1915 ]] --[[ Name: search ]]
    -- upvalues: l_TextBox_0 (copy), v75 (copy), v61 (copy), v50 (ref), v71 (ref), v53 (ref), v52 (ref), v38 (ref), l_TextButton_0 (copy)
    local v339 = {};
    for v340 in l_TextBox_0.Text:gmatch("%S+") do
        v339[v340:lower()] = true;
    end;
    local v341 = {};
    for v342 = v75 + 1, #v61 do
        local v343 = v61[v342];
        table.insert(v341, {
            v343, 
            (v343:CheckTerms(v339))
        });
        v343.Frame.Visible = false;
        v343.Frame.Parent = v50;
    end;
    table.sort(v341, function(v344, v345) --[[ Line: 1930 ]]
        return v344[2] > v345[2];
    end);
    v71 = true;
    local v346 = 0;
    for _, v348 in ipairs(v341) do
        local v349 = v348[1];
        if v348[2] > 0 then
            v349.Frame.Visible = true;
            v349.Frame.Parent = v53;
            v349.Frame.LayoutOrder = v75 + v346;
            v346 = v346 + 1;
        end;
    end;
    v52.CanvasPosition = Vector2.new(0, 0);
    local v350 = math.floor(v52.AbsoluteSize.X / (v38 + 10));
    local v351 = math.ceil((#v53:GetChildren() - 1) / v350) * (v38 + 10) + 10;
    v52.CanvasSize = UDim2.fromOffset(0, v351);
    l_TextButton_0.ZIndex = 3;
end;
local function v357() --[[ Line: 1952 ]] --[[ Name: clearResults ]]
    -- upvalues: l_TextButton_0 (copy), v71 (ref), v75 (copy), v61 (copy), v53 (ref), v52 (ref), v38 (ref)
    if l_TextButton_0.ZIndex > 0 then
        v71 = false;
        for v353 = v75 + 1, #v61 do
            local v354 = v61[v353];
            v354.Frame.LayoutOrder = v354.Index;
            v354.Frame.Parent = v53;
            v354.Frame.Visible = true;
        end;
        l_TextButton_0.ZIndex = 0;
    end;
    local v355 = math.floor(v52.AbsoluteSize.X / (v38 + 10));
    local v356 = math.ceil((#v53:GetChildren() - 1) / v355) * (v38 + 10) + 10;
    v52.CanvasSize = UDim2.fromOffset(0, v356);
end;
local function v358() --[[ Line: 1966 ]] --[[ Name: reset ]]
    -- upvalues: v357 (copy), l_TextBox_0 (copy)
    v357();
    l_TextBox_0.Text = "";
end;
local function v363(v359) --[[ Line: 1971 ]] --[[ Name: onChanged ]]
    -- upvalues: l_TextBox_0 (copy), v357 (copy), v352 (copy), l_TextButton_0 (copy)
    if v359 == "Text" then
        local l_Text_0 = l_TextBox_0.Text;
        if l_Text_0 == "" then
            l_TextBox_0.TextTransparency = 0;
            v357();
        elseif l_Text_0 ~= "" then
            l_TextBox_0.TextTransparency = 0;
            v352();
        end;
        local l_l_TextButton_0_0 = l_TextButton_0;
        local v362 = false;
        if l_Text_0 ~= "" then
            v362 = l_Text_0 ~= "";
        end;
        l_l_TextButton_0_0.Visible = v362;
    end;
end;
local function v365(v364) --[[ Line: 1985 ]] --[[ Name: focusLost ]]
    -- upvalues: v352 (copy)
    if v364 then
        v352();
    end;
end;
l_TextButton_0.MouseButton1Click:Connect(v358);
l_TextBox_0.Changed:Connect(v363);
l_TextBox_0.FocusLost:Connect(v365);
v10.StateChanged.Event:Connect(function(v366) --[[ Line: 1996 ]]
    -- upvalues: v357 (copy), l_TextBox_0 (copy)
    if not v366 then
        v357();
        l_TextBox_0.Text = "";
    end;
end);
v64[Enum.KeyCode.Escape.Value] = function(v367) --[[ Line: 2004 ]]
    -- upvalues: v357 (copy), l_TextBox_0 (copy)
    if v367 then
        v357();
        l_TextBox_0.Text = "";
    end;
end;
l_UserInputService_0.LastInputTypeChanged:Connect(function(v368) --[[ Line: 2009 ]] --[[ Name: detectGamepad ]]
    -- upvalues: l_UserInputService_0 (copy), l_Frame_4 (copy)
    if v368 == Enum.UserInputType.Gamepad1 and not l_UserInputService_0.VREnabled then
        l_Frame_4.Visible = false;
        return;
    else
        l_Frame_4.Visible = true;
        return;
    end;
end);
l_GuiService_0.MenuOpened:Connect(function() --[[ Line: 2020 ]]
    -- upvalues: l_ScreenGui_0 (copy), v42 (copy)
    l_ScreenGui_0.Enabled = false;
    v42:setEnabled(false);
end);
l_GuiService_0.MenuClosed:Connect(function() --[[ Line: 2026 ]]
    -- upvalues: l_ScreenGui_0 (copy), v42 (copy)
    l_ScreenGui_0.Enabled = true;
    v42:setEnabled(true);
end);
l_UICorner_5 = function(_, v370, _) --[[ Line: 2033 ]]
    -- upvalues: l_GuiService_0 (copy), v75 (copy), v61 (copy)
    if v370 ~= Enum.UserInputState.Begin then
        return;
    elseif not l_GuiService_0.SelectedObject then
        return;
    else
        for v372 = 1, v75 do
            if v61[v372].Frame == l_GuiService_0.SelectedObject and v61[v372].Tool then
                v61[v372]:MoveToInventory();
                return;
            end;
        end;
        return;
    end;
end;
local l_l_UICorner_5_0 = l_UICorner_5 --[[ copy: 118 -> 128 ]];
l_UIStroke_1 = function() --[[ Line: 2049 ]] --[[ Name: openClose ]]
    -- upvalues: v65 (copy), v50 (ref), v92 (copy), v49 (ref), v75 (copy), v61 (copy), v73 (ref), v40 (copy), l_UserInputService_0 (copy), v332 (copy), l_Frame_2 (copy), l_ContextActionService_0 (copy), l_l_UICorner_5_0 (copy), v10 (copy)
    if not next(v65) then
        v50.Visible = not v50.Visible;
        local l_Visible_2 = v50.Visible;
        v92();
        v49.Active = not v49.Active;
        for v375 = 1, v75 do
            v61[v375]:SetClickability(not l_Visible_2);
        end;
    end;
    if v50.Visible then
        if v73 then
            if v40[l_UserInputService_0:GetLastInputType()] then
                v332();
                l_Frame_2.Visible = not l_UserInputService_0.VREnabled;
            end;
            enableGamepadInventoryControl();
        end;
    else
        if v73 then
            l_Frame_2.Visible = false;
        end;
        disableGamepadInventoryControl();
    end;
    if v50.Visible then
        l_ContextActionService_0:BindAction("BackpackRemoveSlot", l_l_UICorner_5_0, false, Enum.KeyCode.ButtonX);
    else
        l_ContextActionService_0:UnbindAction("BackpackRemoveSlot");
    end;
    v10.IsOpen = v50.Visible;
    v10.StateChanged:Fire(v50.Visible);
end;
l_StarterGui_0:SetCoreGuiEnabled(Enum.CoreGuiType.Backpack, false);
v10.OpenClose = l_UIStroke_1;
while not l_LocalPlayer_0 do
    task.wait();
    l_LocalPlayer_0 = l_Players_0.LocalPlayer;
end;
l_LocalPlayer_0.CharacterAdded:Connect(v251);
if l_LocalPlayer_0.Character then
    v251(l_LocalPlayer_0.Character);
end;
l_UserInputService_0.InputBegan:Connect(v257);
l_UserInputService_0.TextBoxFocused:Connect(function() --[[ Line: 2112 ]]
    -- upvalues: v70 (ref)
    v70 = true;
end);
l_UserInputService_0.TextBoxFocusReleased:Connect(function() --[[ Line: 2115 ]]
    -- upvalues: v70 (ref)
    v70 = false;
end);
v64[l_Value_0] = function() --[[ Line: 2120 ]]
    -- upvalues: v67 (ref), l_Humanoid_0 (ref), v63 (copy)
    if v67 and l_Humanoid_0 then
        l_Humanoid_0:UnequipTools();
        if v67 then
            v67:ToggleSelect();
            v63[v67]:UpdateEquipView();
            v67 = nil;
        end;
    end;
end;
l_UserInputService_0.LastInputTypeChanged:Connect(v266);
v266();
if l_UserInputService_0:GetGamepadConnected(Enum.UserInputType.Gamepad1) then
    gamepadConnected();
end;
l_UserInputService_0.GamepadConnected:Connect(function(v376) --[[ Line: 2134 ]]
    if v376 == Enum.UserInputType.Gamepad1 then
        gamepadConnected();
    end;
end);
l_UserInputService_0.GamepadDisconnected:Connect(function(v377) --[[ Line: 2139 ]]
    if v377 == Enum.UserInputType.Gamepad1 then
        gamepadDisconnected();
    end;
end);
v10.SetBackpackEnabled = function(_, v379) --[[ Line: 2147 ]] --[[ Name: SetBackpackEnabled ]]
    -- upvalues: v41 (ref)
    v41 = v379;
end;
v10.IsOpened = function(_) --[[ Line: 2152 ]] --[[ Name: IsOpened ]]
    -- upvalues: v10 (copy)
    return v10.IsOpen;
end;
v10.GetBackpackEnabled = function(_) --[[ Line: 2157 ]] --[[ Name: GetBackpackEnabled ]]
    -- upvalues: v41 (ref)
    return v41;
end;
v10.GetStateChangedEvent = function(_) --[[ Line: 2162 ]] --[[ Name: GetStateChangedEvent ]]
    -- upvalues: v10 (copy)
    return v10.StateChanged;
end;
l_RunService_0.Heartbeat:Connect(function() --[[ Line: 2167 ]]
    -- upvalues: v297 (copy), v41 (ref)
    v297(v41);
end);
l_UICorner_5 = function() --[[ Line: 2172 ]] --[[ Name: OnPreferredTransparencyChanged ]]
    -- upvalues: l_GuiService_0 (copy), v16 (ref), v15 (copy), v50 (ref), v21 (ref), v20 (copy), v61 (copy), v31 (ref), l_Frame_4 (copy)
    local l_PreferredTransparency_0 = l_GuiService_0.PreferredTransparency;
    v16 = v15 * l_PreferredTransparency_0;
    v50.BackgroundTransparency = v16;
    v21 = v20 * l_PreferredTransparency_0;
    for _, v385 in ipairs(v61) do
        v385.Frame.BackgroundTransparency = v21;
    end;
    v31 = l_PreferredTransparency_0 * 0.5;
    l_Frame_4.BackgroundTransparency = v31;
end;
l_GuiService_0:GetPropertyChangedSignal("PreferredTransparency"):Connect(l_UICorner_5);
return v10;