-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_LocalPlayer_0 = game:GetService("Players").LocalPlayer;
local l_TweenService_0 = game:GetService("TweenService");
local v2 = {
	transitionUI = nil, 
	didInit = false
};
v2.White = function(_, v4, v5) --[[ Line: 10 ]] --[[ Name: White ]]
	-- upvalues: v2 (copy), l_TweenService_0 (copy)
	if v2.didInit then
		v2:init();
	end;
	v2.transitionUI.White.Visible = true;
	v2.transitionUI.White.BackgroundTransparency --[[ 2021: was GroupTransparency (CanvasGroup, 2022) ]] = 1;
	l_TweenService_0:Create(v2.transitionUI.White, TweenInfo.new(v4, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
		GroupTransparency = 0
	}):Play();
	local v6 = nil;
	if v5 then
		v6 = function(v7) --[[ Line: 25 ]]
			-- upvalues: v2 (ref), v5 (copy)
			v2.transitionUI.White.Video.Visible = true;
			v2.transitionUI.White.Video:Play();
			local v8 = nil;
			task.wait(3.5)
			v2.transitionUI.White.Video.Visible = false;
			v7();
		end;
	end;
	return function(v9) --[[ Line: 42 ]]
		-- upvalues: v2 (ref), l_TweenService_0 (ref)
		v2.transitionUI.White.BackgroundTransparency = 0;
		l_TweenService_0:Create(v2.transitionUI.White, TweenInfo.new(v9, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
			GroupTransparency = 1
		}):Play();
		task.delay(v9, function() --[[ Line: 48 ]]
			-- upvalues: v2 (ref)
			v2.transitionUI.White.Visible = false;
		end);
	end, v6;
end;
v2.init = function(_) --[[ Line: 53 ]] --[[ Name: init ]]
	-- upvalues: v2 (copy), l_LocalPlayer_0 (copy)
	if v2.didInit then
		return;
	else
		v2.transitionUI = script.Assets.Transitions:Clone();
		v2.transitionUI.Parent = l_LocalPlayer_0:WaitForChild("PlayerGui");
		return;
	end;
end;
return v2;