-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- [2021 compat] injected by downgrade tool: table.clear does not exist on this client
local function __2021_clear(t)
	for k in pairs(t) do
		t[k] = nil
	end
end

-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local l_RunService_0 = game:GetService("RunService");
local l_TweenService_0 = game:GetService("TweenService");
local l_LocalPlayer_0 = game:GetService("Players").LocalPlayer;
local l_CanvasGroup_0 = l_LocalPlayer_0.PlayerGui:WaitForChild("JetpackFuel"):WaitForChild("CanvasGroup");
local l_UIStroke_0 = l_CanvasGroup_0:WaitForChild("UIStroke");
local l_Fuel_0 = l_CanvasGroup_0:WaitForChild("Fuel");
local l_Client_0 = l_ReplicatedStorage_0.Slerp.Client;
local v8 = require(l_Client_0.Jetpack);
local v9 = require(l_Client_0.Jetpack.Controller);
local v10 = {};
local v11 = {};
local v12 = {};
local v13 = TweenInfo.new(0.2, Enum.EasingStyle.Sine, Enum.EasingDirection.In);
local v14 = 100;
local function _() --[[ Line: 29 ]] --[[ Name: getHumanoidStateType ]]
	-- upvalues: l_LocalPlayer_0 (copy)
	local l_Character_0 = l_LocalPlayer_0.Character;
	if not l_Character_0 then
		return nil;
	else
		local l_Humanoid_0 = l_Character_0:FindFirstChild("Humanoid");
		if not l_Humanoid_0 then
			return nil;
		else
			return l_Humanoid_0:GetState();
		end;
	end;
end;
local function _(v18) --[[ Line: 41 ]] --[[ Name: getTransparencyKind ]]
	if v18:IsA("CanvasGroup") then
		return "GroupTransparency";
	else
		return "Transparency";
	end;
end;
local _ = function(v20) --[[ Line: 48 ]] --[[ Name: createShowTweens ]]
	-- upvalues: v10 (copy), l_TweenService_0 (copy), v13 (copy)
	for _, v22 in pairs(v10) --[[ 2021 ]] do
		table.insert(v20, (l_TweenService_0:Create(v22, v13, {
			[v22:IsA("CanvasGroup") and "GroupTransparency" or "Transparency"] = v22:GetAttribute("TargetTransparency")
		})));
	end;
end;
local _ = function(v24) --[[ Line: 56 ]] --[[ Name: createHideTweens ]]
	-- upvalues: v10 (copy), l_TweenService_0 (copy), v13 (copy)
	for _, v26 in pairs(v10) --[[ 2021 ]] do
		table.insert(v24, (l_TweenService_0:Create(v26, v13, {
			[v26:IsA("CanvasGroup") and "GroupTransparency" or "Transparency"] = 1
		})));
	end;
end;
local function v32(v28) --[[ Line: 65 ]] --[[ Name: createAndPlayShowTweens ]]
	-- upvalues: v10 (copy), l_TweenService_0 (copy), v13 (copy)
	for _, v30 in pairs(v10) --[[ 2021 ]] do
		local v31 = l_TweenService_0:Create(v30, v13, {
			[v30:IsA("CanvasGroup") and "GroupTransparency" or "Transparency"] = v30:GetAttribute("TargetTransparency")
		});
		v31:Play();
		table.insert(v28, v31);
	end;
end;
local function v37(v33) --[[ Line: 74 ]] --[[ Name: createAndPlayHideTweens ]]
	-- upvalues: v10 (copy), l_TweenService_0 (copy), v13 (copy)
	for _, v35 in pairs(v10) --[[ 2021 ]] do
		local v36 = l_TweenService_0:Create(v35, v13, {
			[v35:IsA("CanvasGroup") and "GroupTransparency" or "Transparency"] = 1
		});
		v36:Play();
		table.insert(v33, v36);
	end;
end;
local _ = function(v38) --[[ Line: 84 ]] --[[ Name: playTweens ]]
	for _, v40 in pairs(v38) --[[ 2021 ]] do
		v40:Play();
	end;
end;
local _ = function(v42) --[[ Line: 89 ]] --[[ Name: cancelTweens ]]
	for _, v44 in pairs(v42) --[[ 2021 ]] do
		v44:Cancel();
	end;
end;
local function v49(v46) --[[ Line: 95 ]] --[[ Name: cancelAndDestroyTweens ]]
	for v47, v48 in pairs(v46) --[[ 2021 ]] do
		v48:Cancel();
		v48:Destroy();
		v46[v47] = nil;
	end;
end;
local _ = function() --[[ Line: 103 ]] --[[ Name: showAnimOld ]]
	-- upvalues: v12 (copy), v11 (copy)
	for _, v51 in pairs(v12) --[[ 2021 ]] do
		v51:Cancel();
	end;
	for _, v53 in pairs(v11) --[[ 2021 ]] do
		v53:Play();
	end;
end;
local _ = function() --[[ Line: 108 ]] --[[ Name: hideAnimOld ]]
	-- upvalues: v11 (copy), v12 (copy)
	for _, v56 in pairs(v11) --[[ 2021 ]] do
		v56:Cancel();
	end;
	for _, v58 in pairs(v12) --[[ 2021 ]] do
		v58:Play();
	end;
end;
local function _() --[[ Line: 114 ]] --[[ Name: showAnim ]]
	-- upvalues: v11 (copy), v49 (copy), v12 (copy), v32 (copy)
	__2021_clear(v11);
	v49(v12);
	v32(v11);
end;
local function _() --[[ Line: 120 ]] --[[ Name: hideAnim ]]
	-- upvalues: v12 (copy), v49 (copy), v11 (copy), v37 (copy)
	__2021_clear(v12);
	v49(v11);
	v37(v12);
end;
local v62 = TweenInfo.new(0.3, Enum.EasingStyle.Quint, Enum.EasingDirection.Out);
local v63 = nil;
local function _(v64) --[[ Line: 128 ]] --[[ Name: setFuelAnim ]]
	-- upvalues: l_TweenService_0 (copy), l_Fuel_0 (copy), v62 (copy), v63 (ref)
	local v65 = UDim2.fromScale(v64, 1);
	local v66 = l_TweenService_0:Create(l_Fuel_0, v62, {
		Size = v65
	});
	if v63 then
		v63:Cancel();
		v63:Destroy();
	end;
	v63 = v66;
	v66:Play();
end;
local function v69(v68) --[[ Line: 141 ]] --[[ Name: setFuelImmediate ]]
	-- upvalues: l_Fuel_0 (copy)
	l_Fuel_0.Size = UDim2.new(v68, 0, 1, 0);
	l_Fuel_0.BackgroundColor3 = Color3.fromRGB(255, 75, 78):Lerp(Color3.fromRGB(116, 255, 116), v68);
end;
return {
	init = function() --[[ Line: 148 ]] --[[ Name: init ]]
		-- upvalues: v10 (copy), l_CanvasGroup_0 (copy), l_UIStroke_0 (copy), v14 (ref), v8 (copy), v12 (copy), v49 (copy), v11 (copy), v37 (copy), v9 (copy), v32 (copy), l_LocalPlayer_0 (copy), l_RunService_0 (copy), v69 (copy)
		v10[1] = l_CanvasGroup_0;
		v10[2] = l_UIStroke_0;
		local v70 = 0;
		local v71 = 1;
		local function _() --[[ Line: 155 ]] --[[ Name: reset ]]
			-- upvalues: v14 (ref), v71 (ref), v8 (ref), v12 (ref), v49 (ref), v11 (ref), v37 (ref)
			v14 = 100;
			v71 = 1;
			v8.setMaxThrottle(v71);
			__2021_clear(v12);
			v49(v11);
			v37(v12);
		end;
		local v73 = nil;
		local function v75() --[[ Line: 163 ]] --[[ Name: canReset ]]
			-- upvalues: v73 (ref)
			if not v73 then
				return false;
			else
				local l_v73_State_0 = v73:GetState();
				if l_v73_State_0 == Enum.HumanoidStateType.Landed or l_v73_State_0 == Enum.HumanoidStateType.Running or l_v73_State_0 == Enum.HumanoidStateType.Jumping or l_v73_State_0 == Enum.HumanoidStateType.Seated or l_v73_State_0 == Enum.HumanoidStateType.Climbing then
					return true;
				else
					return false;
				end;
			end;
		end;
		v8.getJetpackEquippedSignal():Connect(function(_) --[[ Line: 174 ]]

		end);
		v8.getJetpackUnequippedSignal():Connect(function(_) --[[ Line: 177 ]]
			-- upvalues: v75 (copy), v14 (ref), v71 (ref), v8 (ref), v12 (ref), v49 (ref), v11 (ref), v37 (ref)
			if v75() then
				v14 = 100;
				v71 = 1;
				v8.setMaxThrottle(v71);
				__2021_clear(v12);
				v49(v11);
				v37(v12);
				return;
			else
				__2021_clear(v12);
				v49(v11);
				v37(v12);
				return;
			end;
		end);
		v9.throttleChangedSignal:Connect(function(v78, v79) --[[ Line: 184 ]]
			-- upvalues: v70 (ref), v75 (copy), v14 (ref), v71 (ref), v8 (ref), v12 (ref), v49 (ref), v11 (ref), v37 (ref), v32 (ref)
			v70 = v79;
			if v79 == 0 and v78 > 0 then
				if v75() then
					v14 = 100;
					v71 = 1;
					v8.setMaxThrottle(v71);
					__2021_clear(v12);
					v49(v11);
					v37(v12);
					return;
				else
					__2021_clear(v12);
					v49(v11);
					v37(v12);
					return;
				end;
			else
				if v79 > 0 and v78 == 0 then
					__2021_clear(v11);
					v49(v12);
					v32(v11);
				end;
				return;
			end;
		end);
		local v80 = nil;
		local v81 = nil;
		local function v85(v82) --[[ Line: 199 ]] --[[ Name: handleCharacter ]]
			-- upvalues: v80 (ref), v73 (ref), v14 (ref), v71 (ref), v8 (ref), v12 (ref), v49 (ref), v11 (ref), v37 (ref), v81 (ref)
			if v80 then
				v80:Disconnect();
				v80 = nil;
			end;
			v73 = v82:WaitForChild("Humanoid");
			if not v73 then
				return;
			else
				v80 = v73.StateChanged:Connect(function(_, v84) --[[ Line: 208 ]]
					-- upvalues: v14 (ref), v71 (ref), v8 (ref), v12 (ref), v49 (ref), v11 (ref), v37 (ref)
					if v84 == Enum.HumanoidStateType.Landed or v84 == Enum.HumanoidStateType.Seated then
						v14 = 100;
						v71 = 1;
						v8.setMaxThrottle(v71);
						__2021_clear(v12);
						v49(v11);
						v37(v12);
					end;
				end);
				v81 = v73.Died:Connect(function() --[[ Line: 213 ]]
					-- upvalues: v80 (ref), v81 (ref), v73 (ref), v14 (ref), v71 (ref), v8 (ref), v12 (ref), v49 (ref), v11 (ref), v37 (ref)
					if v80 then
						v80:Disconnect();
					end;
					if v81 then
						v81:Disconnect();
					end;
					v80 = nil;
					v81 = nil;
					v73 = nil;
					v14 = 100;
					v71 = 1;
					v8.setMaxThrottle(v71);
					__2021_clear(v12);
					v49(v11);
					v37(v12);
				end);
				return;
			end;
		end;
		local l_Character_1 = l_LocalPlayer_0.Character;
		if l_Character_1 then
			v85(l_Character_1);
		end;
		l_LocalPlayer_0.CharacterAdded:Connect(function(v87) --[[ Line: 231 ]]
			-- upvalues: v85 (copy)
			v85(v87);
		end);
		l_RunService_0.PostSimulation:Connect(function(v88) --[[ Line: 235 ]]
			-- upvalues: v70 (ref), v14 (ref), v69 (ref), v71 (ref), v8 (ref)
			if v70 > 0 then
				v14 = math.max(v14 - v70 * 2 * v88, 0);
				v69(v14 / 100);
				if v14 == 0 and v71 ~= 0 then
					v71 = 0;
					v8.setMaxThrottle(v71);
				end;
			end;
		end);
	end
};