-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- [2021 compat] injected by downgrade tool: table.clear does not exist on this client
local function __2021_clear(t)
	for k in pairs(t) do
		t[k] = nil
	end
end

-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local v0 = {
    scr = script
};
v0.cache = function(_) --[[ Line: 5 ]] --[[ Name: cache ]]
    -- upvalues: v0 (copy)
    local v2 = {
        items = {}, 
        folder = Instance.new("Folder")
    };
    v2.folder.Parent = v0.scr;
    v2.addToCache = function(v3) --[[ Line: 14 ]] --[[ Name: addToCache ]]
        -- upvalues: v2 (copy)
        if table.find(v2.items, v3) then
            return;
        else
            table.insert(v2.items, v3);
            v3.Parent = v2.folder;
            return;
        end;
    end;
    v2.getFromCache = function() --[[ Line: 20 ]] --[[ Name: getFromCache ]]
        -- upvalues: v2 (copy)
        local v4 = v2.items[1];
        if v4 then
            table.remove(v2.items, 1);
            return v4;
        else
            return;
        end;
    end;
    v2.destroy = function() --[[ Line: 28 ]] --[[ Name: destroy ]]
        -- upvalues: v2 (copy)
        __2021_clear(v2.items);
        v2.folder:Destroy();
    end;
    return v2;
end;
return v0;