-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local v0 = require(game:GetService("ReplicatedStorage").Icon);
local l_SocialService_0 = game:GetService("SocialService");
local l_LocalPlayer_0 = game:GetService("Players").LocalPlayer;
v0.new():setImage("rbxassetid://10885655986"):setLabel("Invite"):setCaption("Earn a free booth!"):bindEvent("deselected", function()
    pcall(function()
        l_SocialService_0:PromptGameInvite(l_LocalPlayer_0); -- [2021] no ExperienceInviteOptions
    end);
end):oneClick();