-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
local l_Services_0 = require(script.Parent:WaitForChild("Services"));
local l_CameraShaker_0 = require(script.Parent:WaitForChild("CameraShaker"));
return {
    Emit = function(v5) --[[ Line: 8 ]] --[[ Name: Emit ]]
        for _, v7 in pairs(v5) do
            if v7:IsA("ParticleEmitter") then
                v7:Emit(v7:GetAttributes().EmitCount);
            end;
        end;
    end, 
    EnableParticles = function(v8, v9) --[[ Line: 16 ]] --[[ Name: EnableParticles ]]
        for _, v11 in pairs(v8:GetDescendants()) do
            if v11:IsA("ParticleEmitter") then
                v11.Enabled = v9;
            end;
        end;
    end, 
    ReturnPlayerPosition = function(v12) --[[ Line: 24 ]] --[[ Name: ReturnPlayerPosition ]]
        local l_Character_0 = v12.Character;
        local l_HumanoidRootPart_0 = l_Character_0:FindFirstChild("HumanoidRootPart");
        if l_Character_0 and l_HumanoidRootPart_0 then
            local v15 = RaycastParams.new();
            v15.FilterType = Enum.RaycastFilterType.Blacklist --[[ 2021 ]];
            v15.FilterDescendantsInstances = l_Character_0:GetDescendants();
            local v16 = workspace:Raycast(l_HumanoidRootPart_0.Position, -l_HumanoidRootPart_0.CFrame.UpVector * 50, v15);
            if v16 then
                return v16.Position;
            else
                return l_HumanoidRootPart_0.Position;
            end;
        else
            return;
        end;
    end, 
    ReturnClosestPlayer = function(v17) --[[ Line: 43 ]] --[[ Name: ReturnClosestPlayer ]]
        -- upvalues: l_Services_0 (copy)
        local v18 = 1000;
        local v19 = nil;
        for _, v21 in pairs(l_Services_0.Players:GetPlayers()) do
            local l_Character_1 = v21.Character;
            if l_Character_1 then
                local v23 = l_Character_1:WaitForChild("HumanoidRootPart", 5);
                if v23 then
                    local l_Magnitude_0 = (v23.Position - v17).Magnitude;
                    if l_Magnitude_0 < v18 then
                        v19 = v21;
                        v18 = l_Magnitude_0;
                    end;
                end;
            end;
        end;
        return v18, v19;
    end, 
    ReturnRandomPlayer = function() --[[ Line: 65 ]] --[[ Name: ReturnRandomPlayer ]]
        -- upvalues: l_Services_0 (copy)
        if #l_Services_0.Players:GetPlayers() <= 1 then
            return l_Services_0.Players:GetPlayers()[1];
        else
            return l_Services_0.Players:GetPlayers()[math.random(1, #l_Services_0.Players:GetPlayers())];
        end;
    end, 
    TweenSound = function(v35, v36, v37) --[[ Line: 97 ]] --[[ Name: TweenSound ]]
        -- upvalues: l_Services_0 (copy)
        if v37 ~= 0 then
            v35.Volume = 0;
        end;
        l_Services_0.TweenService:Create(v35, TweenInfo.new(v36, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
            Volume = v37
        }):Play();
    end, 
    TweenCamera = function(v38, v39) --[[ Line: 104 ]] --[[ Name: TweenCamera ]]
        -- upvalues: l_Services_0 (copy)
        local l_CurrentCamera_0 = workspace.CurrentCamera;
        l_CurrentCamera_0.CameraType = Enum.CameraType.Scriptable;
        l_Services_0.TweenService:Create(l_CurrentCamera_0, TweenInfo.new(v38, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut), {
            CFrame = v39
        }):Play();
    end, 
    ChangeTransparencyOfModel = function(v41, v42) --[[ Line: 111 ]] --[[ Name: ChangeTransparencyOfModel ]]
        for _, v44 in pairs(v41:GetDescendants()) do
            if v44:IsA("BasePart") then
                v44.Transparency = v42;
            end;
        end;
        if v41:IsA("BasePart") then
            v41.Transparency = v42;
        end;
    end, 
};