-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")
local remotes = require(game.ReplicatedStorage.Remotes);
local StartMinigame = remotes.Event("MiniGameStart")
local ShotsModule = require(script.Shots)
local ClubFolder = script.Parent 
local heartTemplate = script:FindFirstChild("Heart")
local IslandLocations = {
	Vector3.new(-397.675, -3.106, -383.194),
	Vector3.new(688.069, -2.013, -311.711),
	Vector3.new(818.568, -1.581, 600.258),
}
local _cancelprompt = remotes.Event("CancelPromptPurchase");
local _giftsent = remotes.Event('GiftSentAlert');
local _chatalert = remotes.Event("ChatDonationAlert");
local _newgiftbuxbalance = remotes.Event("NewGiftbuxBalance");
local _newdonated = remotes.Event('DonatedChanged');
local _purchaseboothstarted = remotes.Event("PurchaseBoothStarted");
local _alreadyowned = remotes.Event("AlreadyOwned");
local _newpurchasedbooth = remotes.Event('NewPurchasedBooths');
local _notifydonation = remotes.Event("NotifyDonationParticipants");
local _donationsound = remotes.Event("PlayDonationSound");
local _nogiftbux = remotes.Event("InsufficientGiftbux");
local _purchasepopup = remotes.Event("PurchasePopup");
local _sendinchat = remotes.Event("JustPostSomethingInChatPleaseOkThanksYourTheBest");
local function getRandomPointInCircle(center, radius)
	local angle = math.rad(math.random(0, 360))
	local r = math.sqrt(math.random()) * radius
	local x = center.X + r * math.cos(angle)
	local z = center.Z + r * math.sin(angle)
	local y = center.Y + 5
	return Vector3.new(x, y, z)
end
local function createNewIsland()
	local _Color = "255, 70, 153"
	_sendinchat:FireAllClients(string.format('<font color="rgb('.._Color..')" size="19"><b>[SERVER]: Valentines island</b> has been spawned! 💖</font>'))
	local newIsland = script.ValentinesIsland:Clone()
	newIsland.Parent = workspace
	local spawnPosition = IslandLocations[math.random(1, #IslandLocations)]
	newIsland.Terrain.ValentinesIsland:SetPrimaryPartCFrame(CFrame.new(spawnPosition.X, spawnPosition.Y, spawnPosition.Z)) 
	if workspace:FindFirstChild("Hitbox") then
		workspace:FindFirstChild("Hitbox").Position = spawnPosition
	end
	local hitbox = newIsland.Terrain.ValentinesIsland.Hitbox
	local debounce = {}
	local RunService = game:GetService("RunService")
	local debounce = {}
	if not workspace:FindFirstChild("Hitbox") then
		newIsland.Terrain.ValentinesIsland.Hitbox.Parent = workspace;
	else
		hitbox = workspace:FindFirstChild("Hitbox")
	end
	RunService.Heartbeat:Connect(function()
		for _, player in pairs(game.Players:GetPlayers()) do
			local character = player.Character
			if character then
				local humanoidRootPart = character:FindFirstChild("HumanoidRootPart")
				if humanoidRootPart and workspace:FindFirstChild("Hitbox") then
					local overlapParams = OverlapParams.new()
					overlapParams.FilterDescendantsInstances = { 
						workspace:FindFirstChild("Hitbox")
					}
					overlapParams.FilterType = Enum.RaycastFilterType.Whitelist --[[ 2021 ]]
					overlapParams.RespectCanCollide = false
					overlapParams.BruteForceAllSlow = true
					local insideHitbox = workspace:GetPartsInPart(humanoidRootPart, overlapParams)[1]
					if insideHitbox == hitbox and workspace:FindFirstChild("ValentinesIsland") then
						if not debounce[player] then
							debounce[player] = true
							if not player:GetAttribute("InEvent") then
								player:SetAttribute("InEvent", true)
								if not player.Backpack:FindFirstChild("ValentinesRaygun") and not character:FindFirstChild("ValentinesRaygun") then
									local ValentinesGun = game.ServerStorage.ValentinesRaygun:Clone()
									ValentinesGun.Parent = player.Backpack
									character.Humanoid:EquipTool(ValentinesGun)
									local shots = ShotsModule.GetShots(player.UserId);
									StartMinigame:FireClient(player, "start", shots)
								end
							end
							task.wait(0.5) 
							debounce[player] = nil
						end
					else
						if player:GetAttribute("InEvent") then
							player:SetAttribute("InEvent", nil)

							local backpackGun = player.Backpack:FindFirstChild("ValentinesRaygun")
							local characterGun = character:FindFirstChild("ValentinesRaygun")

							StartMinigame:FireClient(player, "", "")

							if characterGun then
								
								character.Humanoid:UnequipTools();
								characterGun.Handle.GunsEnabled.Value = false;
								
								characterGun:Destroy()
							elseif backpackGun then
								character.Humanoid:UnequipTools();
								backpackGun.Handle.GunsEnabled.Value = false;
								backpackGun:Destroy()
							end
						end
					end
				end
			end
		end
	end)
	return newIsland
end
local function spawnHearts(island)
	local grass = island:FindFirstChild("Grass")
	if not grass then return end
	local center = grass.Position
	local radius = grass.Size.X / 2
	local heartFolder = game.Workspace:FindFirstChild("ValentinesHeart")
	if not heartFolder then
		heartFolder = Instance.new("Folder")
		heartFolder.Name = "ValentinesHeart"
		heartFolder.Parent = game.Workspace
	end
	if #heartFolder:GetChildren() == 0 then
		for i = 1, 10 do
			if heartTemplate then
				local heart = heartTemplate:Clone()
				heart.Parent = heartFolder
				heart.Size = Vector3.new(0,0,0)
				local cometween = TweenService:Create(heart, TweenInfo.new(0.5, Enum.EasingStyle.Back), {Size = Vector3.new(6.126, 5.391, 3.775)})
				cometween:Play()
				heart.Position = getRandomPointInCircle(center, radius)
				local floatTweenInfo = TweenInfo.new(3, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut, -1, true)
				local floatTween = TweenService:Create(heart, floatTweenInfo, {Position = heart.Position + Vector3.new(0, 2, 0)})
				floatTween:Play()
			end
		end
	end
end
local function removeAllHearts()
	local heartFolder = game.Workspace:FindFirstChild("ValentinesHeart")
	if heartFolder then
		for _, heart in pairs(heartFolder:GetChildren()) do
			if heart:IsA("Model") or heart:IsA("Part") then
				local disappearTween = TweenService:Create(heart, TweenInfo.new(0.5, Enum.EasingStyle.Back), {Size = Vector3.new(0, 0, 0)})
				disappearTween:Play()
				disappearTween.Completed:Connect(function()
					heart:Destroy()
				end)
			end
		end
		task.wait(1)
		heartFolder:Destroy()
	end
end
local function heartChecker()
	while task.wait(1.5) do
		local heartFolder = game.Workspace:FindFirstChild("ValentinesHeart")
		if not heartFolder or #heartFolder:GetChildren() == 0 then
			local activeIsland = game.Workspace:FindFirstChild("ValentinesIsland")
			if activeIsland then
				spawnHearts(activeIsland.Terrain.ValentinesIsland)
			end
		end
	end
end
local function replaceIsland()
	while task.wait(math.random(150, 200)) do
		if not (#game.Players:GetChildren() >= 5) then
			return;
		end;
		local newIsland = createNewIsland()
		spawnHearts(newIsland.Terrain.ValentinesIsland)
		task.wait(125);
		removeAllHearts()
		for _, Bullets in pairs(workspace:GetChildren()) do
			if Bullets:IsA("Part") and Bullets.Name == "GunBullet" then
				Bullets:Destroy();
			end;
		end;
		newIsland:Destroy()
		task.wait(2) 
	end
end
game.ServerStorage.EventBooth.Event:Connect(function(player: plr)
	task.wait(0.5);
	local TankBoothDatastore = game:GetService("DataStoreService"):GetDataStore("TankBoothV1");
	if TankBoothDatastore:GetAsync(player.UserId) then
		player:SetAttribute("GiftBuxs", player:GetAttribute("GiftBuxs") + 100);
		return
	else
		TankBoothDatastore:SetAsync(player.UserId, true);
		player:SetAttribute("GiftBuxs", player:GetAttribute("GiftBuxs") + 100);
		print('sigma')
		if not TankBoothDatastore:GetAsync(player.UserId) then
			return
		else
			local _booths = require(game.ServerStorage.Booths);
			local _table = {
				['price'] = _booths.Booths["TankBooth"].price;
				['name'] = _booths.Booths["TankBooth"].name;
				['id'] = _booths.Booths["TankBooth"].name;
				['icon'] = {
					['Image'] = _booths.Booths["TankBooth"].icon.Image;
					['ImageRectOffset'] = _booths.Booths["TankBooth"].icon.ImageRectOffset;
					['ImageRectSize'] = _booths.Booths["TankBooth"].icon.ImageRectSize;
				};
				['hoverIcon'] = {
					['Image'] = _booths.Booths["TankBooth"].hoverIcon.Image;
					['ImageRectOffset'] = _booths.Booths["TankBooth"].hoverIcon.ImageRectOffset;
					['ImageRectSize'] = _booths.Booths["TankBooth"].hoverIcon.ImageRectSize;
				};
			};
			require(game.ServerScriptService.Modules.Data):PurcharseBooth(player.UserId, "TankBooth");
			_newpurchasedbooth:FireClient(player, _table);
		end
	end;
end);



task.spawn(replaceIsland)
task.spawn(heartChecker)
