-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local l_Players_0 = game:GetService("Players");
local l_TeleportService_0 = game:GetService("TeleportService");
local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local l_TweenService_0 = game:GetService("TweenService");
-- [2021] VoiceChatService does not exist on this client; stubbed (voice always "disabled")
local l_VoiceChatService_0 = { IsVoiceEnabledForUserIdAsync = function() return false end };
local l_SoundService_0 = game:GetService("SoundService");
local l_StarterGui_0 = game:GetService("StarterGui");
local v7 = require(l_ReplicatedStorage_0.Remotes);
local l_LocalPlayer_0 = l_Players_0.LocalPlayer;
local l_ScreenGui_0 = l_LocalPlayer_0.PlayerGui:WaitForChild("ScreenGui");
local l_UITemplates_0 = l_StarterGui_0:WaitForChild("UITemplates");
tween = function(v11, v12, v13) --[[ Line: 17 ]] --[[ Name: tween ]]
    l_TweenService_0:Create(v11, TweenInfo.new(v12, Enum.EasingStyle.Quint), v13):Play();
end;
local function _(v14, v15) --[[ Line: 22 ]] --[[ Name: popup ]]
    spawn(function() --[[ Line: 23 ]]
        if l_ScreenGui_0.Popups:GetAttribute("Enabled") then
            l_SoundService_0.SFX.BellRing:Play();
            local v16 = l_UITemplates_0[v14 .. "Popup"];
            if not v16 then
                print("NOPE");
                return;
            else
                local v17 = v16:Clone();
                v17.Message.Text = v15;
                v17.Transparency = 1;
                v17.UIScale.Scale = 0;
                v17.Parent = l_ScreenGui_0.Popups;
                tween(v17, 0.5, {
                    Transparency = 0
                });
                tween(v17.UIScale, 0.3, {
                    Scale = 1
                }, Enum.EasingStyle.Back);
                tween(v17.Message, 1, {
                    MaxVisibleGraphemes = #v15
                });
                wait(4);
                tween(v17, 0.25, {
                    Transparency = 1
                });
                tween(v17.UIScale, 0.5, {
                    Scale = 0
                }, Enum.EasingStyle.Back);
                wait(0.5);
                v17:Destroy();
            end;
        end;
    end);
end;
local v19 = require(l_ReplicatedStorage_0.FeaturePlaces);
local v20 = require(script.RolesList);
local function v24() --[[ Line: 55 ]] --[[ Name: setupMap ]]
    if not v19.IsLegacyMap then
        task.defer(function() --[[ Line: 62 ]]
            local v21 = l_VoiceChatService_0:IsVoiceEnabledForUserIdAsync(l_LocalPlayer_0.UserId);
            local v22 = false;
            pcall(function() --[[ Line: 65 ]]
                v22 = v7.Function("AmIVip"):InvokeServer();
            end);
            local v23 = v21 or l_LocalPlayer_0.UserId == 151848836;
            if v19.IsVoiceChatOnly then
                if not v23 then
                    l_LocalPlayer_0:Kick("You don't have access to voice chat servers!");
                end;
                workspace.Map.Functional.VoiceChatTP.PromptPart.ProximityPrompt.ObjectText = "Public (Currently in VC)";
                workspace.Map.Functional.VoiceChatTP.PromptPart.ProximityPrompt.Triggered:Connect(function() --[[ Line: 74 ]]
                    l_ScreenGui_0.ServerSelector.Visible = true;
                end);
            elseif v19.IsDeluxeVoiceChatOnly then
                if not v22 and not v20.ADMINS[l_LocalPlayer_0.UserId] then
                    l_LocalPlayer_0:Kick("You need to be subscribed to PLS DONATE's VIP to access deluxe voice chat servers!");
                end;
                if not v23 and not v20.ADMINS[l_LocalPlayer_0.UserId] then
                    l_LocalPlayer_0:Kick("You don't have access to voice chat servers!");
                end;
                workspace.Map.Functional.VoiceChatTP.PromptPart.ProximityPrompt.ObjectText = "Public (Currently in Deluxe VC)";
                workspace.Map.Functional.VoiceChatTP.PromptPart.ProximityPrompt.Triggered:Connect(function() --[[ Line: 85 ]]
                    l_ScreenGui_0.ServerSelector.Visible = true;
                end);
            else
                workspace.Map.Functional.VoiceChatTP.PromptPart.ProximityPrompt.Triggered:Connect(function() --[[ Line: 89 ]]
                    l_ScreenGui_0.ServerSelector.Visible = true;
                end);
            end;
        end);
        return;
    else
        workspace.Map.NewMapTP.TextSign.ProximityPrompt.Triggered:Connect(function() --[[ Line: 95 ]]
            l_TeleportService_0:Teleport(v19.LivePlaceId, l_LocalPlayer_0);
        end);
        return;
    end;
end;
v24();
workspace.ChildAdded:Connect(function(v25) --[[ Line: 102 ]]
    if v25.Name == "Map" then
        v24();
    end;
end);