-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- [2021] Experience Events (RSVP) do not exist pre-2023 and can't work on Pekora.
-- The "Notify me" button is hidden; the countdown itself keeps working (Timer script is separate).
script.Parent.Visible = false
