-- ============================================================
-- 2021 CLIENT (PEKORA) REPLACEMENT -- generated by downgrade tool
-- Paste this whole file over the matching script in your 2021 Studio.
-- All changes are marked with [2021] or 2021 comments.
-- ============================================================
-- decompiled using medal by alpaca and jujhar

local v1 = game:GetService("ReplicatedStorage")
local v_u_2 = game:GetService("UserInputService")
local v3 = game:GetService("CollectionService")
local v_u_4 = game:GetService("TweenService")
local v_u_5 = game:GetService("RunService")
local v_u_6 = game:GetService("Players")
local v_u_7 = v_u_6.LocalPlayer
local v_u_8 = v_u_7:GetMouse()
local v_u_9 = v_u_7.UserId
local v_u_10 = workspace.CurrentCamera
local v_u_11 = require(v1:WaitForChild("Slerp"):WaitForChild("Shared"):WaitForChild("MinigamesUtil")).TicTacToe
local v_u_12 = v1.Slerp.RemoteEvents:WaitForChild("TicTacToeEvent")
local v_u_13 = nil
local v_u_14 = nil
local v_u_15 = {}
local v_u_16 = {}
local v_u_17 = TweenInfo.new(1, Enum.EasingStyle.Sine)
local v_u_18 = TweenInfo.new(0.75, Enum.EasingStyle.Sine)
local v_u_19 = TweenInfo.new(0.5, Enum.EasingStyle.Linear)
local v_u_20 = TweenInfo.new(0.1, Enum.EasingStyle.Sine)
local v_u_21 = TweenInfo.new(0.5, Enum.EasingStyle.Exponential)
local v_u_22 = TweenInfo.new(0.25, Enum.EasingStyle.Cubic, Enum.EasingDirection.In)
local v_u_23 = v_u_19.Time * 2
local v_u_24 = RaycastParams.new()
v_u_24.FilterType = Enum.RaycastFilterType.Whitelist --[[ 2021 ]]
v_u_24.IgnoreWater = true
local v_u_25 = v_u_11.Nought:Clone()
v_u_25.Transparency = 0.5
local v_u_26 = v_u_11.Cross:Clone()
v_u_26.Transparency = 0.5
local v_u_27 = v_u_11.CorfirmTile:Clone()
local v_u_28 = v_u_27.Size
local v_u_29 = v_u_11.RejectTile:Clone()
local v_u_30 = v_u_29.Size
local v31 = Instance.new("Part")
v31.TopSurface = Enum.SurfaceType.Smooth
v31.BottomSurface = Enum.SurfaceType.Smooth
v31.Color = Color3.fromRGB(200, 50, 50)
v31.Material = Enum.Material.Plastic
v31.CanCollide = false
v31.CanQuery = false
v31.CanTouch = false
v31.Anchored = true
v31.Name = "Line"
local function PlaceSymbol(p38, p39, p40, p41) -- line: 118
	-- upvalues: (copy) v_u_16, (copy) v_u_11, (copy) v_u_4, (copy) v_u_21
	local v42 = v_u_16[p38]
	local v43 = v42.BoardAttachments[p39]
	local v44 = v42.RaycastBoard
	local v45 = v42.Symbols
	local v46 = tostring(p39)
	if p40 ~= 0 and not v45:FindFirstChild(v46) then
		print(p40)
		local v47
		if p40 == 1 then
			v47 = v_u_11.Nought:Clone()
		else
			v47 = v_u_11.Cross:Clone()
		end
		local v48 = v47.Size
		v47.CFrame = v43.WorldCFrame * CFrame.new(0, v44.Size.Y * 0.5, 0)
		v47.Size = Vector3.zero
		v47.Name = v46
		v47.Parent = v45
		local v49 = v_u_4:Create(v47, v_u_21, {
			["CFrame"] = v47.CFrame * CFrame.new(0, v48.Y * 0.5, 0),
			["Size"] = v48
		})
		if p41 then
			v49.Completed:Once(p41)
		end
		v49:Play()
	end
end
local function RemoveSymbol(p50, p51) -- line: 148
	-- upvalues: (copy) v_u_16, (copy) v_u_4, (copy) v_u_22
	local v_u_52 = v_u_16[p50].Symbols:FindFirstChild((tostring(p51)))
	if v_u_52 then
		local v53 = v_u_4:Create(v_u_52, v_u_22, {
			["Size"] = Vector3.zero,
			["CFrame"] = v_u_52.CFrame * CFrame.new(0, -v_u_52.Size.Y, 0)
		})
		v53.Completed:Once(function()
			-- upvalues: (copy) v_u_52
			v_u_52:Destroy()
		end)
		v53:Play()
	end
end
local function PlaceObject(p54, p55, p56, p57) -- line: 163
	-- upvalues: (copy) v_u_16, (copy) v_u_4, (copy) v_u_21
	local v58 = v_u_16[p54].RaycastBoard
	p55.CFrame = p57.WorldCFrame * CFrame.new(0, v58.Size.Y * 0.5, 0)
	p55.Size = Vector3.zero
	p55.Parent = p54
	v_u_4:Create(p55, v_u_21, {
		["CFrame"] = p57.WorldCFrame * CFrame.new(0, p56.Y * 0.5, 0),
		["Size"] = p56
	}):Play()
end
local function RemoveObject(p_u_59, p_u_60) -- line: 177
	-- upvalues: (copy) v_u_4, (copy) v_u_22
	local v61 = v_u_4:Create(p_u_59, v_u_22, {
		["Size"] = Vector3.zero,
		["CFrame"] = p_u_59.CFrame * CFrame.new(0, -p_u_59.Size.Y, 0)
	})
	v61.Completed:Once(function()
		-- upvalues: (copy) p_u_59, (copy) p_u_60
		p_u_59.Parent = nil
		p_u_59.Size = p_u_60
	end)
	v61:Play()
end
local function SetupInteractiveConnections(p_u_62) -- line: 188
	-- upvalues: (copy) v_u_16, (copy) v_u_24, (ref) v_u_13, (copy) v_u_8, (copy) v_u_2, (copy) v_u_10, (copy) v_u_9, (copy) v_u_12, (copy) v_u_25, (copy) v_u_26, (ref) v_u_14, (copy) v_u_5, (copy) v_u_4, (copy) v_u_20
	local v_u_63 = v_u_16[p_u_62]
	local v_u_64 = v_u_63.RaycastBoard
	local v_u_65 = v_u_63.BoardAttachments
	local v_u_66 = v_u_63.Leave
	v_u_24.FilterDescendantsInstances = { v_u_64, v_u_66 }
	v_u_13 = v_u_8.Button1Down:Connect(function()
		-- upvalues: (ref) v_u_2, (ref) v_u_24, (ref) v_u_10, (copy) v_u_65, (copy) v_u_64, (copy) v_u_63, (copy) p_u_62, (ref) v_u_9, (ref) v_u_12, (copy) v_u_66
		local v67 = v_u_2:GetMouseLocation()
		local v68 = v_u_24
		local v69 = v_u_10:ViewportPointToRay(v67.X, v67.Y)
		local v70 = v69.Origin
		local v71 = v69.Direction * 50
		local v72 = workspace:Raycast(v70, v71, v68)
		local v73
		if v72 then
			v73 = v72.Instance
		else
			v73 = v72
		end
		if v72 then
			local v74 = v72.Position
			local v75 = (1 / 0)
			local v76 = nil
			for _, v77 in pairs(v_u_65) --[[ 2021 ]] do
				local v78 = (v77.WorldPosition - v74).Magnitude
				if v78 <= v75 then
					v76 = v77
					v75 = v78
				end
			end
			if v76 then
				local _ = v73 == v_u_64
				if not v_u_63.Symbols:FindFirstChild(v76.Name) and p_u_62:GetAttribute("ActivePlayer") == v_u_9 then
					local v79 = v_u_12
					local v80 = p_u_62
					local v81 = {}
					local v82 = v76.Name
					v81.Move = tonumber(v82)
					v79:FireServer(v80, v81)
					return
				end
				if v73 == v_u_66 then
					v_u_12:FireServer(p_u_62, {
						["Leave"] = true
					})
					v_u_10.CameraType = Enum.CameraType.Custom
				end
			end
		end
	end)
	local v_u_83
	if p_u_62:GetAttribute("Player1") == v_u_9 then
		v_u_83 = v_u_25
	else
		v_u_83 = v_u_26
	end
	local v_u_84 = nil
	v_u_14 = v_u_5.PreRender:Connect(function()
		-- upvalues: (copy) p_u_62, (ref) v_u_9, (ref) v_u_2, (ref) v_u_24, (ref) v_u_10, (copy) v_u_64, (copy) v_u_63, (ref) v_u_84, (copy) v_u_83, (ref) v_u_4, (ref) v_u_20
		if p_u_62:GetAttribute("ActivePlayer") == v_u_9 then
			local v85 = v_u_2:GetMouseLocation()
			local v86 = v_u_24
			local v87 = v_u_10:ViewportPointToRay(v85.X, v85.Y)
			local v88 = v87.Origin
			local v89 = v87.Direction * 50
			local v90 = workspace:Raycast(v88, v89, v86)
			local v91
			if v90 then
				v91 = v90.Instance
			else
				v91 = v90
			end
			if v90 and v91 == v_u_64 then
				local v92 = v90.Position
				local v93 = (1 / 0)
				local v94 = nil
				for _, v95 in pairs(v_u_63.BoardAttachments) --[[ 2021 ]] do
					local v96 = (v95.WorldPosition - v92).Magnitude
					if v96 <= v93 then
						v94 = v95
						v93 = v96
					end
				end
				if v94 then
					local v97 = v94 ~= v_u_84
					local v98 = v_u_63.Symbols:FindFirstChild(v94.Name)
					if v97 and not v98 then
						local v99 = v94.WorldCFrame * CFrame.new(0, (v_u_64.Size.Y + v_u_83.Size.Y) * 0.5, 0)
						if v_u_83.Parent then
							v_u_4:Create(v_u_83, v_u_20, {
								["CFrame"] = v99
							}):Play()
						else
							v_u_83.CFrame = v99
							v_u_83.Parent = workspace
						end
						v_u_84 = v94
						return
					end
					if (v94 == nil or v98) and v_u_83.Parent ~= nil then
						v_u_83.Parent = nil
						v_u_84 = nil
						return
					end
				end
			end
		elseif v_u_83.Parent ~= nil then
			v_u_83.Parent = nil
			v_u_84 = nil
		end
	end)
end
local function CleanUpInteractiveConnections(_) -- line: 264
	-- upvalues: (ref) v_u_13, (ref) v_u_14, (copy) v_u_25, (copy) v_u_26, (copy) v_u_24
	if v_u_13 and v_u_13.Connected then
		v_u_13:Disconnect()
		v_u_13 = nil
	end
	if v_u_14 and v_u_14.Connected then
		v_u_14:Disconnect()
		v_u_14 = nil
		v_u_25.Parent = nil
		v_u_26.Parent = nil
	end
	v_u_24.FilterDescendantsInstances = {}
end
local function SetupReplicationConnections(p_u_100) -- line: 281
	-- upvalues: (copy) v_u_16, (copy) v_u_11, (copy) PlaceSymbol, (copy) v_u_4, (copy) v_u_19
	local _ = v_u_16[p_u_100].DisplayLabel
	p_u_100:GetAttributeChangedSignal("GameData"):Connect(function()
		-- upvalues: (ref) v_u_11, (copy) p_u_100, (ref) PlaceSymbol
		local v101 = v_u_11.DecodeGameData(p_u_100:GetAttribute("GameData"))
		if v101 ~= v_u_11.BlankData then
			for v102, v103 in pairs(v101) --[[ 2021 ]] do
				PlaceSymbol(p_u_100, v102, v103)
			end
		end
	end)
	p_u_100:GetAttributeChangedSignal("GameMessage"):Connect(function()
		-- upvalues: (ref) v_u_16, (copy) p_u_100, (ref) v_u_4, (ref) v_u_19
		if not v_u_16[p_u_100].IgnoreServerMessage then
			local v104 = p_u_100
			local v105 = p_u_100:GetAttribute("GameMessage")
			local v106 = v_u_16[v104].DisplayLabel
			v106.MaxVisibleGraphemes = 0
			v106.Text = v105
			v_u_4:Create(v106, v_u_19, {
				["MaxVisibleGraphemes"] = #v105
			}):Play()
		end
	end)
end
local function LeaveGame(p107) -- line: 301
	-- upvalues: (copy) v_u_16, (copy) RemoveSymbol, (copy) v_u_7, (copy) CleanUpInteractiveConnections, (copy) v_u_10, (copy) v_u_6, (copy) SetCharacterVisible, (copy) v_u_15, (copy) v_u_9
	for _, v109 in v_u_16[p107.TicTacToe].Symbols:GetChildren() do
		local v110 = RemoveSymbol
		local v111 = v109.Name
		v110(p107.TicTacToe, (tonumber(v111)))
	end
	if p107.Index == "Player1" then
		p107.TicTacToe.RaycastBoard.Prompts["1"].PlayTicTacToe.Enabled = true
	elseif p107.Index == "Player2" then
		p107.TicTacToe.RaycastBoard.Prompts["2"].PlayTicTacToe.Enabled = true
	end
	if p107.Player == v_u_7 then
		CleanUpInteractiveConnections(p107.TicTacToe)
		v_u_10.CameraType = Enum.CameraType.Custom
	end
end
local function RematchGame(...) -- line: 344
	local Table = ...
	-- upvalues: (copy) v_u_16, (copy) v_u_6, (copy) v_u_9, (copy) CleanUpInteractiveConnections, (copy) v_u_4, (copy) v_u_19, (copy) v_u_22, (copy) v_u_23, (copy) RemoveSymbol, (copy) PlaceObject, (copy) v_u_27, (copy) v_u_28, (copy) v_u_29, (copy) v_u_30, (copy) v_u_24, (copy) RemoveObject, (copy) v_u_8, (copy) v_u_2, (copy) v_u_10, (copy) v_u_12, (copy) PlaceSymbol, (copy) v_u_18
	local v_u_123 = v_u_16[Table.TicTacToe]
	local v_u_124 = v_u_123.Line
	local v125 = Table.TicTacToe:GetAttribute("Player1")
	local v126 = Table.TicTacToe:GetAttribute("Player2")
	local v127 = v_u_6:GetPlayerByUserId(v125)
	local v128 = v_u_6:GetPlayerByUserId(v126)
	local v_u_129 = v125 == v_u_9 and true or v126 == v_u_9
	if v_u_129 then
		CleanUpInteractiveConnections(Table.TicTacToe)
	end
	local v130
	if Table.Win == 0 then
		v130 = "It\'s a draw!"
	elseif Table.Win == 1 then
		v130 = ("%s wins!"):format(v127.DisplayName)
	end
	if Table.Win == 2 then
		v130 = ("%s wins!"):format(v128.DisplayName)
	end
	local v131 = v_u_16[Table.TicTacToe].DisplayLabel
	v131.MaxVisibleGraphemes = 0
	v131.Text = v130
	v_u_4:Create(v131, v_u_19, {
		["MaxVisibleGraphemes"] = #v130
	}):Play()
	local function BounceSymbols(p132, p133) -- line: 358
		local v134 = #p132
		local v135 = nil
		for v136, v137 in pairs(p132) --[[ 2021 ]] do
			if v137:IsA("BasePart") then
				local v138 = v137.Size
				local v139 = v137.CFrame
				local v_u_140 = v_u_4:Create(v137, v_u_22, {
					["Size"] = v137.Size * 0.75,
					["CFrame"] = v137.CFrame * CFrame.new(0, -(v137.Size.Y * 0.25), 0),
					["Color"] = Color3.fromRGB(175, 45, 45)
				})
				local v_u_141 = v_u_4:Create(v137, v_u_22, {
					["Size"] = v138,
					["CFrame"] = v139
				})
				v_u_140.Completed:Once(function()
					-- upvalues: (copy) v_u_141
					v_u_141:Play()
				end)
				if v136 == v134 then
					v_u_141.Completed:Once(function()
						-- upvalues: (ref) v_u_23, (ref) v_u_123, (ref) RemoveSymbol, (ref) p_u_118, (ref) v_u_4, (ref) v_u_124, (ref) v_u_22, (ref) v_u_16, (ref) v_u_19, (ref) v_u_129, (ref) PlaceObject, (ref) v_u_27, (ref) v_u_28, (ref) v_u_29, (ref) v_u_30, (ref) v_u_24, (ref) RemoveObject, (ref) v_u_8, (ref) v_u_2, (ref) v_u_10, (ref) v_u_12
						task.wait(v_u_23)
						for _, v142 in v_u_123.Symbols:GetChildren() do
							local v143 = RemoveSymbol
							local v144 = Table.TicTacToe
							local v145 = v142.Name
							v143(v144, (tonumber(v145)))
						end
						local v146 = v_u_4:Create(v_u_124, v_u_22, {
							["Transparency"] = 1
						})
						v146:Play()
						v146.Completed:Wait()
						v_u_124.Parent = nil
						v_u_124.Transparency = 0
						local v147 = v_u_16[Table.TicTacToe].DisplayLabel
						v147.MaxVisibleGraphemes = 0
						v147.Text = "Rematch?"
						v_u_4:Create(v147, v_u_19, {
							["MaxVisibleGraphemes"] = 8
						}):Play()
						if v_u_129 then
							PlaceObject(Table.TicTacToe, v_u_27, v_u_28, v_u_123.BoardAttachments[4])
							PlaceObject(Table.TicTacToe, v_u_29, v_u_30, v_u_123.BoardAttachments[6])
							v_u_24.FilterDescendantsInstances = { v_u_27, v_u_29, v_u_123.Leave }
							local v_u_148 = nil
							local function CleanUpRematch() -- line: 398
								-- upvalues: (ref) v_u_16, (ref) p_u_118, (ref) v_u_24, (ref) RemoveObject, (ref) v_u_27, (ref) v_u_28, (ref) v_u_29, (ref) v_u_30, (ref) v_u_148
								v_u_16[Table.TicTacToe].RemovingRematchButtons = true
								v_u_24.FilterDescendantsInstances = {}
								RemoveObject(v_u_27, v_u_28)
								RemoveObject(v_u_29, v_u_30)
								if v_u_148 and v_u_148.Connected then
									v_u_148:Disconnect()
								end
							end
							v_u_148 = v_u_8.Button1Down:Connect(function()
								-- upvalues: (ref) v_u_2, (ref) v_u_24, (ref) v_u_10, (ref) v_u_27, (ref) v_u_12, (ref) p_u_118, (copy) CleanUpRematch, (ref) v_u_29, (ref) v_u_123
								local v149 = v_u_2:GetMouseLocation()
								local v150 = v_u_24
								local v151 = v_u_10:ViewportPointToRay(v149.X, v149.Y)
								local v152 = v151.Origin
								local v153 = v151.Direction * 50
								local v154 = workspace:Raycast(v152, v153, v150)
								if v154 then
									v154 = v154.Instance
								end
								if v154 == v_u_27 then
									v_u_12:FireServer(Table.TicTacToe, {
										RematchType = true,
										Rematch = true
									})
									CleanUpRematch()
								elseif v154 == v_u_29 or v154 == v_u_123.Leave then
									v_u_12:FireServer(Table.TicTacToe, {
										RematchType = true,
										Rematch = false
									})
									CleanUpRematch()
								end
							end)
						end
					end)
				end
				if p133 then
					if v135 then
						v135.Completed:Once(function()
							-- upvalues: (copy) v_u_140
							v_u_140:Play()
						end)
					else
						v_u_140:Play()
					end
					v135 = v_u_140
				else
					v_u_140:Play()
				end
			end
		end
	end
	-- upvalues: (copy) Table.Pattern, (copy) v_u_123, (copy) v_u_124, (copy) p_u_118, (ref) v_u_4, (ref) v_u_18, (copy) BounceSymbols
	if Table.Pattern then
		wait(0.5)
		local v155 = v_u_123.Symbols
		local v156 = Table.Pattern[1]
		local v157 = v155:FindFirstChild((tostring(v156)))
		local v158 = v_u_123.Symbols
		local v159 = Table.Pattern[#Table.Pattern]
		local v160 = v158:FindFirstChild((tostring(v159)))
		local v161 = (Table.Pattern == { 1, 5, 9 } or Table.Pattern == { 3, 5, 7 }) and 0.625 or 0.375
		v_u_124.Size = Vector3.new(0.25, 0.15, 0)
		v_u_124.CFrame = CFrame.lookAt(v157.Position, v160.Position) * CFrame.new(0, 0, v157.Size.Z * v161)
		v_u_124.Parent = Table.TicTacToe
		local v162 = v_u_124.CFrame.LookVector
		local v163 = (v157.Position - v162 * v157.Size.X * v161 - v160.Position + v162 * v160.Size.X * v161).Magnitude + 0.8
		v_u_4:Create(v_u_124, v_u_18, {
			["Position"] = v_u_124.Position + v_u_124.CFrame.Rotation * -Vector3.zAxis * v163 * 0.5,
			["Size"] = v_u_124.Size + Vector3.zAxis * v163
		}):Play()
		local v164 = {}
		for _, v165 in pairs(Table.Pattern) --[[ 2021 ]] do
			local v166 = v_u_123.Symbols:FindFirstChild((tostring(v165)))
			if v166 then
				table.insert(v164, v166)
			end
		end
		BounceSymbols(v164, true)
	else
		wait(0.5)
		BounceSymbols(v_u_123.Symbols:GetChildren())
	end
end
local function EndGame(p167) -- line: 482
	-- upvalues: (copy) v_u_9, (copy) v_u_16, (copy) v_u_4, (copy) v_u_19, (copy) v_u_23, (copy) SetupInteractiveConnections, (copy) CleanUpInteractiveConnections, (copy) RemoveObject, (copy) v_u_27, (copy) v_u_28, (copy) v_u_29, (copy) v_u_30, (copy) RemoveSymbol, (copy) v_u_10, (copy) v_u_6, (copy) v_u_7, (copy) SetCharacterVisible, (copy) v_u_15
	local v169 = p167.TicTacToe:GetAttribute("Player1")
	local v170 = p167.TicTacToe:GetAttribute("Player2")
	local v171 = v169 == v_u_9 and true or v170 == v_u_9
	local v172 = v_u_16[p167.TicTacToe]
	v172.IgnoreServerMessage = true
	if p167.isRematch then
		local v173 = v_u_16[p167.TicTacToe].DisplayLabel
		v173.MaxVisibleGraphemes = 0
		v173.Text = "Rematch Accepted!"
		v_u_4:Create(v173, v_u_19, {
			["MaxVisibleGraphemes"] = 17
		}):Play()
		task.wait(v_u_23)
		if v171 then
			local v174 = p167.TicTacToe:GetAttribute("GameMessage")
			local v175 = v_u_16[p167.TicTacToe].DisplayLabel
			v175.MaxVisibleGraphemes = 0
			v175.Text = v174
			v_u_4:Create(v175, v_u_19, {
				["MaxVisibleGraphemes"] = #v174
			}):Play()
			SetupInteractiveConnections(p167.TicTacToe)
		end
	else
		if v171 and not v_u_16[p167.TicTacToe].RemovingRematchButtons then
			CleanUpInteractiveConnections(p167.TicTacToe)
			RemoveObject(v_u_27, v_u_28)
			RemoveObject(v_u_29, v_u_30)
		end
		for _, v176 in v_u_16[p167.TicTacToe].Symbols:GetChildren() do
			local v177 = RemoveSymbol
			local v178 = v176.Name
			v177(p167.TicTacToe, (tonumber(v178)))
		end
		local v179 = p167.isRematch == false and "Rematch Rejected" or "Inactivity Detected"
		local v180 = v_u_16[p167.TicTacToe].DisplayLabel
		v180.MaxVisibleGraphemes = 0
		v180.Text = v179
		v_u_4:Create(v180, v_u_19, {
			["MaxVisibleGraphemes"] = #v179
		}):Play()
		task.wait(v_u_23)
		if v171 then
			v_u_10.CameraType = Enum.CameraType.Custom
		end
		local v184 = v_u_16[p167.TicTacToe].DisplayLabel
		v184.MaxVisibleGraphemes = 0
		v184.Text = "Waiting for players"
		v_u_4:Create(v184, v_u_19, {
			["MaxVisibleGraphemes"] = 19
		}):Play()
	end
	v172.IgnoreServerMessage = false
	v172.RemovingRematchButtons = false
end
for _, v_u_185 in v3:GetTagged("TicTacToe") do
	local v_u_186 = v_u_185:WaitForChild("RaycastBoard")
	local v187 = v_u_186:WaitForChild("Prompts")
	local v188 = v_u_186:WaitForChild("Grid")
	local v189 = v_u_185:WaitForChild("Backboard"):WaitForChild("Screen"):WaitForChild("DisplayGui")
	local v190 = v189:WaitForChild("DisplayTextLabel")
	local v191 = {}
	for _, v192 in v188:GetChildren() do
		local v193 = v192.Name
		local v194 = tonumber(v193)
		if v194 and v192:IsA("Attachment") then
			v191[v194] = v192
		end
	end
	v_u_16[v_u_185] = {
		["RaycastBoard"] = v_u_186,
		["BoardAttachments"] = v191,
		["Display"] = v189,
		["DisplayLabel"] = v190,
		["Symbols"] = v_u_185:WaitForChild("Symbols"),
		["Leave"] = v_u_185:WaitForChild("Leave"),
		["Line"] = v31:Clone(),
		["IgnoreServerMessage"] = false,
		["RemovingRematchButtons"] = false
	}
	for _, v_u_195 in v187:GetChildren() do
		local v_u_196 = v_u_195:WaitForChild("PlayTicTacToe")
		v_u_196.Triggered:Connect(function(p197)
			-- upvalues: (copy) v_u_7, (copy) v_u_196, (copy) v_u_12, (copy) v_u_185, (copy) v_u_195, (copy) v_u_10, (copy) v_u_4, (copy) v_u_17, (copy) v_u_186, (copy) SetupInteractiveConnections, (copy) SetCharacterVisible, (copy) v_u_15, (copy) v_u_6, (copy) v_u_9
			if p197 == v_u_7 then
				local v198 = v_u_7.Character
				if not v198 then
					return
				end
				local v199 = v198:FindFirstChild("Humanoid")
				if not v199 then
					return
				end
				if v199.SeatPart or v199.Sit then
					v199.Sit = false
				end
				v_u_196.Enabled = false
				local v200 = v_u_12
				local v201 = v_u_185
				local v202 = {}
				local v203 = v_u_195.Name
				v202.Join = tonumber(v203)
				v200:FireServer(v201, v202)
				v_u_10.CameraType = Enum.CameraType.Scriptable
				local v204 = v_u_4:Create(v_u_10, v_u_17, {
					["CFrame"] = v_u_186.Camera.WorldCFrame
				})
				v204.Completed:Once(function()
					-- upvalues: (ref) v_u_10, (ref) SetupInteractiveConnections, (ref) v_u_185
					v_u_10.CameraType = Enum.CameraType.Scriptable
					SetupInteractiveConnections(v_u_185)
				end)
				v204:Play()
			end
		end)
	end
	v190.Text = v_u_185:GetAttribute("GameMessage")
	SetupReplicationConnections(v_u_185)
	local v230 = v_u_185:GetAttribute("GameData")
	if v230 then
		local v231 = v_u_11.DecodeGameData(v230)
		if v231 ~= v_u_11.BlankData then
			for v232, v233 in pairs(v231) --[[ 2021 ]] do
				if v233 ~= 0 then
					PlaceSymbol(v_u_185, v232, v233)
				end
			end
		end
	end
end
v_u_12.OnClientEvent:Connect(function(p234, ...)
	-- upvalues: (copy) LeaveGame, (copy) RematchGame, (copy) EndGame
	if p234 == "LeaveGame" then
		LeaveGame(...)
		return
	elseif p234 == "RematchGame" then
		RematchGame(...)
	elseif p234 == "EndGame" then
		EndGame(...)
	end
end)
